/**
 * A.14 — Books.
 *
 * The 12 Book tokens plus the six cards that generate them.
 *
 * B100: every Book is cost 1, `Temporary`, typed `Token` + `Book`, grants
 * +1 Action via `stats.actions`, is `notPurchasable` and has `rarity: 'token'`.
 */
import type { CardDefinition, PoolSpec } from '@engine/types';

/** Pull one card from the twelve-Book sub-catalog. */
const bookPool: { pool: PoolSpec } = { pool: { catalog: 'book' } };

export const cards: CardDefinition[] = [
  // -------------------------------------------------------------------------
  // The 12 Books
  // -------------------------------------------------------------------------
  {
    id: 'book_of_lethal_kill',
    name: 'Book of Lethal Kill',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: ['Legacy'],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [
      {
        op: 'conditional',
        if: { not: { expr: 'sumOfDeckCosts % 13' } },
        then: [
          { op: 'gain', stat: 'money', amount: 13 },
          { op: 'gain', stat: 'buys', amount: 13 },
        ],
      },
    ],
    triggers: [],
    text: '+1 Action. If your deck’s total cost is divisible by 13, +13 Money and +13 Buys.',
    flavor: 'Thirteen is a lethal number.',
    complexity: 'T2',
    subsystems: ['S-TOKEN', 'S-EFFECTS'],
    notPurchasable: true,
    art: { key: 'book_of_lethal_kill', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'book_of_conspiracy',
    name: 'Book of Conspiracy',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: ['Legacy'],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1, prophet: 3 },
    effects: [],
    triggers: [],
    text: '+1 Action, +3 Prophet.',
    flavor: 'It was them. It was always them.',
    complexity: 'T1',
    subsystems: ['S-TOKEN', 'S-PROPHET'],
    notPurchasable: true,
    art: { key: 'book_of_conspiracy', status: 'placeholder' },
  },
  {
    id: 'book_of_books',
    name: 'Book of Books',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: ['Legacy'],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: bookPool, to: 'hand', count: 2 }],
    triggers: [],
    text: '+1 Action. Add two Books to your hand.',
    flavor: 'Recursion, bound in leather.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'book_of_books', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'book_of_flame',
    name: 'Book of Flame',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: ['Legacy'],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [
      { op: 'trash', target: { zone: 'hand', count: 1, pick: 'choose' } },
      {
        op: 'conditional',
        if: { ifPrevious: true },
        then: [{ op: 'gain', stat: 'money', amount: 5 }],
      },
    ],
    triggers: [],
    text: '+1 Action. Trash a card in your hand for +5 Money.',
    flavor: 'Burns brighter for what it eats.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'book_of_flame', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'book_of_knowledge',
    name: 'Book of Knowledge',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: ['Legacy'],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1, cards: 5 },
    effects: [],
    triggers: [],
    text: '+1 Action, +5 Cards.',
    flavor: 'Read it once and you will never need to again.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'book_of_knowledge', status: 'placeholder' },
  },
  {
    id: 'book_of_random',
    name: 'Book of Random',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: [],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [
      {
        op: 'random',
        branches: [
          {
            weight: 1,
            effects: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse' } }, to: 'hand', count: 1 }],
          },
          {
            weight: 1,
            effects: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse' } }, to: 'hand', count: 2 }],
          },
          {
            weight: 1,
            effects: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse' } }, to: 'hand', count: 3 }],
          },
          {
            weight: 1,
            effects: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse' } }, to: 'hand', count: 4 }],
          },
          {
            weight: 1,
            effects: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse' } }, to: 'hand', count: 5 }],
          },
        ],
      },
    ],
    triggers: [],
    text: '+1 Action. Add 1–5 random cards from the Entire Universe to your hand.',
    flavor: 'The index is also random.',
    complexity: 'T3',
    subsystems: ['S-TOKEN', 'S-EFFECTS'],
    notPurchasable: true,
    art: { key: 'book_of_random', status: 'placeholder', anim: 'shuffle' },
  },
  {
    id: 'book_of_frost',
    name: 'Book of Frost',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: [],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [{ op: 'discardDownTo', amount: 1, who: 'eachOpponent' }],
    triggers: [],
    text: '+1 Action. Each opponent discards down to 1 card.',
    flavor: 'Winter, abridged.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'book_of_frost', status: 'placeholder' },
  },
  {
    id: 'book_of_curses',
    name: 'Book of Curses',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: [],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: 'cursed_pig', to: 'gy', who: 'eachOpponent', count: 3 }],
    triggers: [],
    text: '+1 Action. Add 3 Cursed Pigs to each opponent’s GY.',
    flavor: 'Pigs, specifically. The author was very clear.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'book_of_curses', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'book_of_greed',
    name: 'Book of Greed',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: [],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [
      {
        op: 'gainCard',
        from: { shop: 'all', pick: 'random', count: 3, excludeJlore: true },
        to: 'hand',
        count: 3,
        free: true,
      },
    ],
    triggers: [],
    text: '+1 Action. Add 3 random Shop cards to your hand.',
    flavor: 'Chapter one: take it.',
    complexity: 'T2',
    subsystems: ['S-TOKEN', 'S-SHOP'],
    notPurchasable: true,
    art: { key: 'book_of_greed', status: 'placeholder', anim: 'coin' },
  },
  {
    id: 'book_of_felinors',
    name: 'Book of Felinors',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: [],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [
      // `count` is applied to the pooled candidate list rather than per player,
      // so one `eachPlayer` node discards 2 cards in total. Split in two, you
      // always lose 2 yourself and the opponents lose 2 between them; exactly 2
      // each needs a per-player count in the selector.
      { op: 'discard', target: { who: 'self', zone: 'hand', count: 2, pick: 'random' } },
      { op: 'discard', target: { who: 'eachOpponent', zone: 'hand', count: 2, pick: 'random' } },
      { op: 'createCard', defId: 'felinor', to: 'hand', who: 'eachPlayer', count: 2 },
    ],
    triggers: [],
    text: '+1 Action. Each player discards 2 cards at random and gains 2 Felinors in hand.',
    flavor: 'They got into the shelf again.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'book_of_felinors', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'book_of_blood',
    name: 'Book of Blood',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: ['Legacy'],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [
      // A.14 also prints ‘when trashed, add an original copy to their hand’ on
      // the marked cards. A keyword is the only rider an instance can carry —
      // triggers are read off the definition — so that half is unimplemented,
      // and `text` says only what the card actually does rather than promising
      // it.
      {
        op: 'setKeyword',
        target: {
          who: 'eachOpponent',
          zone: ['library', 'hand', 'gy'],
          filter: { type: 'Action' },
          count: 3,
          pick: 'random',
        },
        keyword: 'Flimsy',
        on: true,
      },
    ],
    triggers: [],
    text: '+1 Action. Give 3 Action cards in opponents’ decks Flimsy.',
    flavor: 'Signed in a hurry.',
    complexity: 'T3',
    subsystems: ['S-TOKEN', 'S-PERSIST'],
    notPurchasable: true,
    art: { key: 'book_of_blood', status: 'placeholder' },
  },
  {
    id: 'book_of_moon',
    name: 'Book of Moon',
    cost: { money: 1 },
    types: ['Token', 'Book'],
    subtypes: ['Book'],
    tags: [],
    rarity: 'token',
    keywords: ['Temporary'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: 'lunar_fragment', to: 'hand', count: 1 }],
    triggers: [],
    text: '+1 Action. Add a Lunar Fragment to your hand.',
    flavor: 'Mostly pictures.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'book_of_moon', status: 'placeholder', anim: 'summon' },
  },

  // -------------------------------------------------------------------------
  // Book generators
  // -------------------------------------------------------------------------
  {
    id: 'library_card',
    name: 'Library Card',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: bookPool, to: 'hand', count: 1 }],
    triggers: [],
    text: 'Flimsy. +1 Action. Add a Book to your hand.',
    flavor: 'Do not lose it.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'library_card', status: 'placeholder' },
  },
  {
    id: 'premium_library_card',
    name: 'Premium Library Card',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: bookPool, to: 'hand', count: 1 }],
    triggers: [],
    text: '+1 Action. Add a Book to your hand.',
    flavor: 'No late fees.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'premium_library_card', status: 'placeholder' },
  },
  {
    id: 'premium_premium_library_card',
    name: 'Premium Premium Library Card',
    cost: { money: 9 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: bookPool, to: 'hand', count: 2 }],
    triggers: [],
    text: '+1 Action. Add 2 Books to your hand.',
    flavor: 'They know your name at the desk.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'premium_premium_library_card', status: 'placeholder' },
  },
  {
    id: 'shockwaves_dream',
    name: 'Shockwave’s Dream',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      // The Books are dealt straight into the hand — `count` is evaluated
      // before anything moves, so `handSize` is still the hand about to burn —
      // and the trash then spares them. Parking them in `aside` loses them:
      // createCard gives an unowned zone no owner and nothing can select them
      // back out.
      { op: 'createCard', defId: bookPool, to: 'hand', count: { expr: 'floor(handSize / 2)' } },
      { op: 'trash', target: { zone: 'hand', filter: { not: { type: 'Book' } } } },
    ],
    triggers: [],
    text: '+1 Action. Add X Books to your hand, X = half your hand size rounded down, then trash every non-Book card in your hand.',
    flavor: 'He woke up holding half a library.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'shockwaves_dream', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'archivist',
    name: 'Archivist',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'choose',
        options: [
          {
            label: 'Add a Temporary Book to your hand',
            effects: [{ op: 'createCard', defId: bookPool, to: 'hand', count: 1, keywords: ['Temporary'] }],
          },
          {
            label: 'Remove Temporary from all Books in your hand',
            effects: [
              {
                op: 'setKeyword',
                target: { zone: 'hand', filter: { type: 'Book' } },
                keyword: 'Temporary',
                on: false,
              },
            ],
          },
        ],
      },
    ],
    triggers: [],
    text: '+1 Action. Choose one: add a Temporary Book to your hand; or remove Temporary from every Book in your hand.',
    flavor: 'Some things are meant to be kept.',
    complexity: 'T3',
    subsystems: ['S-TOKEN', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'archivist', status: 'placeholder' },
  },
  {
    id: 'back_to_the_raq',
    name: 'Back to the Raq',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'trash', target: { zone: 'library', count: 2, pick: 'random' } },
      { op: 'createCard', defId: bookPool, to: 'gy', count: 2 },
    ],
    triggers: [],
    text: 'Trash 2 random cards in your Library to drop 2 Books into your GY.',
    flavor: 'Reshelved, violently.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'back_to_the_raq', status: 'placeholder', anim: 'shuffle' },
  },
];

export default cards;

/** Ids of the twelve Books, in catalog order. Feeds the `book` sub-catalog. */
export const BOOK_IDS: string[] = cards.filter((c) => c.types.includes('Book')).map((c) => c.id);
