/**
 * A.20 — Grubbing Goblins.
 *
 * The `grubbing_goblin` token is `PlayOnDraw` + `Flimsy` with `stats.money = 2`,
 * so every Goblin in the deck is two Money that costs no hand slot and no
 * Action. The archetype is about getting as many of them into the GY as it can.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'grubbing_goblin',
    name: 'Grubbing Goblin',
    cost: { money: 0 },
    types: ['Action', 'Token'],
    subtypes: ['Goblin'],
    tags: [],
    rarity: 'token',
    keywords: ['PlayOnDraw', 'Flimsy'],
    stats: { money: 2 },
    effects: [],
    triggers: [],
    text: 'Play on Draw. Flimsy. +2 Money.',
    flavor: 'It grubs.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'grubbing_goblin', status: 'placeholder' },
  },
  {
    id: 'goblin_gang_boss',
    name: 'Goblin Gang Boss',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Goblin'],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { money: 2 },
    effects: [{ op: 'createCard', defId: 'grubbing_goblin', to: 'gy', count: 1 }],
    triggers: [],
    text: '+2 Money. Add a Grubbing Goblin to your GY.',
    flavor: 'Somebody has to organise them.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'goblin_gang_boss', status: 'placeholder' },
  },
  {
    id: 'nether_portal',
    name: 'Nether Portal',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Goblin'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [],
    triggers: [
      {
        on: 'onDiscard',
        effects: [{ op: 'createCard', defId: 'grubbing_goblin', to: 'gy', count: 2 }],
      },
    ],
    text: 'When discarded, add 2 Grubbing Goblins to your GY.',
    flavor: 'It only opens when nobody is holding it.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'nether_portal', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'jakkari_sacrifice',
    name: 'Jakkari Sacrifice',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Goblin'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [],
    triggers: [
      {
        on: 'onDiscard',
        effects: [{ op: 'createCard', defId: 'nether_portal', to: 'gy', count: 1 }],
      },
    ],
    text: 'When discarded, add a Nether Portal to your GY.',
    flavor: 'Give something up, get somewhere new.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'jakkari_sacrifice', status: 'placeholder' },
  },
  {
    id: 'war_bonds',
    name: 'War Bonds',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Goblin'],
    tags: [],
    rarity: 'rare',
    keywords: ['PlayOnBuy', 'Flimsy'],
    stats: { buys: 1 },
    effects: [{ op: 'createCard', defId: 'grubbing_goblin', to: 'gy', count: 3 }],
    triggers: [],
    text: 'Play on Buy. Flimsy. +1 Buy. Add 3 Grubbing Goblins to your GY.',
    flavor: 'Sold door to door, mostly to goblins.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'war_bonds', status: 'placeholder' },
  },
  {
    id: 'cn_backed_war_bonds',
    name: 'CN Backed War Bonds',
    cost: { money: 8 },
    types: ['Action'],
    subtypes: ['CN', 'Goblin'],
    tags: [],
    rarity: 'epic',
    keywords: ['PlayOnBuy', 'Flimsy'],
    stats: { buys: 1 },
    effects: [
      { op: 'createCard', defId: 'grubbing_goblin', to: 'gy', count: 5 },
      { op: 'createCard', defId: 'war', to: 'gy', count: 1 },
    ],
    triggers: [],
    text: 'Play on Buy. Flimsy. +1 Buy. Add 5 Grubbing Goblins and a War! to your GY.',
    flavor: 'Backed by something, definitely.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'cn_backed_war_bonds', status: 'placeholder' },
  },
  {
    id: 'the_mob',
    name: 'The Mob',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Goblin'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'nextCardModifier',
        mod: {
          appliesTo: 'buy',
          uses: 99,
          appendEffects: [{ op: 'createCard', defId: 'grubbing_goblin', to: 'gy', count: 1 }],
        },
      },
    ],
    triggers: [],
    text: 'Every card you buy this turn also adds a Grubbing Goblin to your GY.',
    flavor: 'They follow the money.',
    complexity: 'T2',
    subsystems: ['S-TOKEN', 'S-SHOP'],
    shop: 'draft',
    art: { key: 'the_mob', status: 'placeholder' },
  },
  {
    id: 'uncle_musabi',
    name: 'Uncle Musabi',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Goblin'],
    tags: [],
    rarity: 'legendary',
    keywords: ['Flimsy'],
    stats: { cards: 1 },
    effects: [
      {
        op: 'transform',
        target: { zone: 'library', filter: { cost: { lte: 2 } } },
        into: 'grubbing_goblin',
      },
    ],
    triggers: [],
    text: 'Flimsy. +1 Card. Transform every card costing (2) or less in your Library into a Grubbing Goblin.',
    flavor: 'He knows what they were. He does not care.',
    complexity: 'T3',
    subsystems: ['S-TOKEN', 'S-EFFECTS'],
    shop: 'draft',
    art: { key: 'uncle_musabi', status: 'placeholder' },
  },
  {
    id: 'skull_of_juldan',
    name: "Skull of Jul'dan",
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Goblin'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 3 },
    effects: [
      // Nothing stamps the three cards the printed stat line just drew, so the
      // loop can only approximate "drawn": take the 3 most recently added (0)-cost
      // cards in hand, which is the doc's own ceiling — an unbounded `over` paid
      // +3 Money for every Egg already being held. `{self:true}` trashes the card
      // the iteration is bound to; the old random re-pick could trash another one.
      //
      // `text` states the approximation rather than the doc's "each drawn card":
      // when the three drawn cards are not all (0)-cost the loop reaches past them
      // to (0)-cost cards that were already in hand, so "for each drawn card" would
      // be a lie. Naming the newest-first order keeps the printed line honest until
      // an engine-side stamp on freshly drawn instances makes "drawn" expressible.
      {
        op: 'forEach',
        over: { zone: 'hand', filter: { cost: { eq: 0 } }, count: 3, pick: 'bottom' },
        effects: [
          { op: 'gain', stat: 'money', amount: 3 },
          { op: 'trash', target: { self: true } },
        ],
      },
    ],
    triggers: [],
    text: '+3 Cards. Then trash up to 3 cards costing (0) from your hand, newest first, for +3 Money each.',
    flavor: 'Still shouting.',
    complexity: 'T2',
    subsystems: ['S-EFFECTS'],
    shop: 'draft',
    art: { key: 'skull_of_juldan', status: 'placeholder', anim: 'trash' },
  },
];

export default cards;
