/**
 * A.18 — Plague archetype.
 *
 * Plague tokens live on a specific instance in *any* zone, shop piles included
 * (B65), so a `plague` target here is sometimes a `Selector` over a player's
 * zones and sometimes a `PileSelector` over the shop.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'crop_dusting',
    name: 'Crop Dusting',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['Plague'],
    tags: ['Legacy'],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { has: { target: { zone: 'shop', filter: { plagued: false } }, atLeast: 1 } },
        then: [{ op: 'gain', stat: 'money', amount: 2 }],
      },
      { op: 'plague', target: { shop: 'all' }, amount: 1 },
    ],
    triggers: [],
    text: 'Put 1 Plague Token on the top card of every Shop pile. +2 Money if any of them had none.',
    flavor: 'Low pass over the whole market.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE', 'S-SHOP'],
    shop: 'draft',
    art: { key: 'crop_dusting', status: 'placeholder' },
  },
  {
    id: 'plague_crawler',
    name: 'Plague Crawler',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: ['Plague'],
    tags: ['Legacy'],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [{ op: 'plague', target: { zone: 'gy', count: 1, pick: 'random' }, amount: 1 }],
    triggers: [
      {
        on: 'onPlagueAdded',
        effects: [{ op: 'gain', stat: 'cards', amount: 2 }],
      },
    ],
    text: '+1 Action. Put 1 Plague Token on a random card in your GY. Whenever a token is placed on this, the placer draws 2 Cards. ({plague} on this.)',
    flavor: 'It goes where the sickness is thickest.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'plague_crawler', status: 'placeholder' },
  },
  {
    id: 'plague_charger',
    name: 'Plague Charger',
    cost: { money: 3 },
    types: ['Points'],
    subtypes: ['Plague'],
    tags: ['Legacy'],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'selfCounter' } }],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'choose',
            options: [
              {
                label: 'Trash Plague Charger to put 3 Plague Tokens on a card in your GY',
                effects: [
                  { op: 'plague', target: { zone: 'gy', count: 1, pick: 'choose' }, amount: 3 },
                  { op: 'trash', target: { self: true } },
                ],
              },
              { label: 'Keep it', effects: [{ op: 'noop' }] },
            ],
          },
        ],
      },
    ],
    text: 'On purchase you may trash this to put 3 Plague Tokens on a card in your GY. Otherwise it is worth +{plague} VP.',
    flavor: 'Charged and waiting.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'plague_charger', status: 'placeholder' },
  },
  {
    id: 'patient_zero',
    name: 'Patient Zero',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['Plague'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'plague', target: { shop: 'draft', count: 1, pick: 'choose' }, amount: 1 },
      {
        op: 'conditional',
        if: { has: { target: { zone: 'gy', filter: { plagued: true } }, atLeast: 1 } },
        then: [{ op: 'gain', stat: 'cards', amount: 2 }],
      },
    ],
    triggers: [],
    text: '+1 Action. Put a Plague Token on the top card of a Draft pile. If any card you gained this turn carried a token, +2 Cards.',
    flavor: 'He felt fine, mostly.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE', 'S-SHOP'],
    shop: 'draft',
    art: { key: 'patient_zero', status: 'placeholder' },
  },
  {
    id: 'outbreak',
    name: 'Outbreak',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: ['Plague'],
    tags: ['Legacy'],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'plague', target: { shop: 'all', count: 2, pick: 'random' }, amount: 1 },
      {
        op: 'gainCard',
        from: { shop: 'all', filter: { plagued: true }, pick: 'mostExpensive', count: 1 },
        to: 'gy',
        count: 1,
        free: true,
      },
    ],
    triggers: [],
    text: '+1 Action. Put a Plague Token on the top card of two random piles, then gain any Shop card whose tokens exceed its cost.',
    flavor: 'It got out.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE', 'S-SHOP'],
    shop: 'draft',
    art: { key: 'outbreak', status: 'placeholder' },
  },
  {
    id: 'antibody_extraction',
    name: 'Antibody Extraction',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['Plague'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'plague', target: { zone: 'hand', count: 1, pick: 'random' }, amount: 1 },
      // "Up to 2" needs the op with an optional count: a `repeat` + forced
      // `pick:'choose'` made the trash compulsory, and with one plagued card in
      // hand it never even prompted. `selectCards` binds each pick as the source,
      // so `{self:true}` is the card the player actually chose.
      {
        op: 'selectCards',
        from: { zone: 'hand', filter: { plagued: true } },
        min: 0,
        max: 2,
        then: [
          { op: 'trash', target: { self: true } },
          { op: 'gain', stat: 'cards', amount: 1 },
          { op: 'gain', stat: 'money', amount: 1 },
        ],
      },
    ],
    triggers: [],
    text: '+1 Action. Put a Plague Token on a random card in your hand, then trash up to 2 plagued cards from your hand for +1 Card and +1 Money each.',
    flavor: 'The cure is in the patient.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE'],
    shop: 'draft',
    art: { key: 'antibody_extraction', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'living_bomb',
    name: 'Living Bomb',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['Plague'],
    tags: ['Legacy'],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'trash', target: { who: 'eachPlayer', zone: 'gy', filter: { plagued: true } } },
      // A PileSelector matches a pile on its top card and `trashPile` then destroys
      // the whole stack, so one plagued top wiped a 10-card Common pile. Trash the
      // plagued instances instead; the nested `not` replaces `excludeJlore`.
      { op: 'trash', target: { zone: 'shop', filter: { plagued: true, not: { defId: 'jlore' } } } },
      { op: 'plague', target: { who: 'eachOpponent', zone: 'gy', count: 1, pick: 'random' }, amount: 1 },
    ],
    triggers: [],
    text: '+1 Action. Trash every plagued card in the Shop and in every GY, then put 1 Plague Token on a random card in each opponent’s GY.',
    flavor: 'Contain it by removing everything near it.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE', 'S-SHOP'],
    shop: 'draft',
    art: { key: 'living_bomb', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'plandemic',
    name: 'Plandemic',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Plague'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'plague', target: { who: 'eachPlayer', zone: 'gy', filter: { plagued: true } }, amount: 1 },
      { op: 'plague', target: { shop: 'all', filter: { plagued: true } }, amount: 1 },
      { op: 'plague', target: { who: 'eachPlayer', zone: 'gy', count: 1, pick: 'random' }, amount: 1 },
      {
        op: 'copyCard',
        target: { who: 'eachPlayer', zone: 'gy', filter: { plagued: true }, count: 1, pick: 'mostExpensive' },
        to: 'hand',
      },
    ],
    triggers: [],
    text: '+1 Action. Double every Plague Token in the Shop and in every GY and respread them, minimum 1. Add copies of cards whose tokens equal their cost to your hand, minimum 1.',
    flavor: 'Someone drew the graph in advance.',
    complexity: 'T4',
    subsystems: ['S-PLAGUE', 'S-SHOP'],
    shop: 'draft',
    art: { key: 'plandemic', status: 'placeholder' },
  },
  {
    id: 'jalshi',
    name: 'Jalshi',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Plague'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'choose',
        options: [
          {
            label: 'Plague every card in your hand',
            effects: [{ op: 'plague', target: { zone: 'hand' }, amount: 1 }],
          },
          {
            label: 'Remove every Plague Token from your hand for +X Money',
            effects: [
              { op: 'gain', stat: 'money', amount: { expr: 'countIn(hand, plagued)' } },
              { op: 'removePlague', target: { zone: 'hand' } },
            ],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Choose one: plague every card in your hand; or remove every Plague Token from your hand for +X Money, X = tokens removed.',
    flavor: 'Sell the sickness or sell the cure.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE'],
    shop: 'draft',
    art: { key: 'jalshi', status: 'placeholder' },
  },
  {
    id: 'juhan_wet_market',
    name: 'Juhan Wet Market',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['CN', 'Plague'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [{ op: 'gain', stat: 'cards', amount: { expr: 'selfCounter' } }],
    triggers: [
      {
        on: 'onDiscard',
        effects: [{ op: 'plague', target: { self: true }, amount: 2 }],
      },
    ],
    text: '+1 Action, +{plague} Cards. When discarded, put 2 more Plague Tokens on this.',
    flavor: 'Everything here is fresh, technically.',
    complexity: 'T3',
    subsystems: ['S-PLAGUE', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'juhan_wet_market', status: 'placeholder' },
  },
];

export default cards;
