/**
 * A.21 — Truss.
 *
 * The +Actions archetype, and the main consumer of the Big Action sink
 * (SB-1): Big Truss costs 2 Actions to play, Nap costs 3.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'truss',
    name: 'Truss',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Truss'],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 2, cards: 1 },
    effects: [],
    triggers: [],
    text: '+2 Actions, +1 Card.',
    flavor: 'Holds the whole thing up.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'truss', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'big_truss',
    name: 'Big Truss',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Truss'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 3, cards: 4 },
    effects: [],
    triggers: [],
    text: 'Big Action 2. +3 Actions, +4 Cards.',
    flavor: 'Bigger truss.',
    complexity: 'T3',
    subsystems: ['S-BIGACTION'],
    shop: 'draft',
    bigAction: 2,
    art: { key: 'big_truss', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'nap',
    name: 'Nap',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['Truss'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 1 },
    effects: [
      { op: 'delayed', when: 'startOfNextTurn', effects: [{ op: 'gain', stat: 'actions', amount: 1 }] },
      { op: 'delayed', when: { inTurns: 2 }, effects: [{ op: 'gain', stat: 'actions', amount: 1 }] },
    ],
    triggers: [],
    text: 'Big Action 3. +1 Card. +1 Action on each of your next two turns.',
    flavor: 'Three actions now for two later. Worth it.',
    complexity: 'T3',
    subsystems: ['S-BIGACTION'],
    shop: 'draft',
    bigAction: 3,
    art: { key: 'nap', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'truss_monk',
    name: 'Truss Monk',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Truss'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, cards: 1 },
    effects: [{ op: 'createCard', defId: 'truss', to: 'gy', count: 1 }],
    triggers: [],
    text: '+1 Action, +1 Card. Add a Truss to your GY.',
    flavor: 'He builds one a day and says nothing about it.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'truss_monk', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'truss_trust',
    name: 'Truss Trust',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Truss'],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'createCard', defId: 'tix', to: 'gy', count: 2 },
      { op: 'createCard', defId: 'truss', to: 'gy', count: 2 },
    ],
    triggers: [],
    text: 'Flimsy. Add 2 Tix and 2 Truss to your GY.',
    flavor: 'Diversified.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'truss_trust', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'truss_flick',
    name: 'Truss Flick',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Truss'],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'trash', target: { zone: 'hand', filter: { subtype: 'Truss' }, count: 1, pick: 'choose' } },
      {
        op: 'conditional',
        if: { ifPrevious: true },
        then: [
          { op: 'gain', stat: 'cards', amount: 3 },
          { op: 'gain', stat: 'actions', amount: 6 },
        ],
      },
    ],
    triggers: [],
    text: 'Flimsy. Trash a Truss for +3 Cards and +6 Actions.',
    flavor: 'One flick and the whole frame comes down.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'truss_flick', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
  {
    id: '401j',
    name: '401J',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Truss'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      { op: 'createCard', defId: 'truss_trust', to: 'gy', count: 1 },
      { op: 'createCard', defId: 'grubbing_goblin', to: 'gy', count: 1 },
      { op: 'createCard', defId: 'soul_shard', to: 'gy', count: 1 },
    ],
    triggers: [],
    text: 'Add a Truss Trust, a Grubbing Goblin and a Soul Shard to your GY.',
    flavor: 'Employer match includes one (1) goblin.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: '401j', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
];

export default cards;
