/**
 * A.14 — Draft Shop: Book generators.
 *
 * Slice S7 (cards-archetypes). The 12 Book tokens themselves are owned by the
 * tribes slice; this file only generates them, through the `book` sub-catalog:
 *   book_of_lethal_kill, book_of_conspiracy, book_of_books, book_of_flame,
 *   book_of_knowledge, book_of_random, book_of_frost, book_of_curses,
 *   book_of_greed, book_of_felinors, book_of_blood, book_of_moon.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'library_card',
    name: 'Library Card',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['Scripture'],
    tags: [],
    rarity: 'common',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: { pool: { catalog: 'book' } }, to: 'hand' }],
    triggers: [],
    text: 'Flimsy. +1 Action. Add a Book to your hand.',
    flavor: 'One card. One book. One chance.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'library_card', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'premium_library_card',
    name: 'Premium Library Card',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Scripture'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: { pool: { catalog: 'book' } }, to: 'hand' }],
    triggers: [],
    text: '+1 Action. Add a Book to your hand.',
    flavor: 'The same books, but you keep the card.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'premium_library_card', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'premium_premium_library_card',
    name: 'Premium Premium Library Card',
    cost: { money: 9 },
    types: ['Action'],
    subtypes: ['Scripture'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: { pool: { catalog: 'book' } }, to: 'hand', count: 2 }],
    triggers: [],
    text: '+1 Action. Add 2 Books to your hand.',
    flavor: 'Twice the premium, twice the books.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'premium_premium_library_card', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'shockwaves_dream',
    name: "Shockwave's Dream",
    cost: { money: 7 },
    types: ['Action'],
    subtypes: ['Scripture'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'createCard', defId: { pool: { catalog: 'book' } }, to: 'hand', count: { expr: 'floor(handSize / 2)' } },
      { op: 'trash', target: { zone: 'hand', filter: { not: { type: 'Book' } } } },
    ],
    triggers: [],
    text: '+1 Action. Trash your hand and add X Books to it, where X is half the cards trashed, rounded down.',
    flavor: 'He dreamed of a library and woke up holding it.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'shockwaves_dream', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'archivist',
    name: 'Archivist',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: ['Scripture'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'choose',
        options: [
          {
            label: 'Add a Temporary Book to your hand',
            effects: [{ op: 'createCard', defId: { pool: { catalog: 'book' } }, to: 'hand', keywords: ['Temporary'] }],
          },
          {
            label: 'Remove Temporary from every Book in your hand',
            effects: [{ op: 'setKeyword', target: { zone: 'hand', filter: { type: 'Book' } }, keyword: 'Temporary', on: false }],
          },
        ],
      },
    ],
    triggers: [],
    text: '+1 Action. Choose one: add a Temporary Book to your hand, or remove Temporary from every Book in your hand.',
    flavor: 'Nothing here is ever due back.',
    complexity: 'T3',
    subsystems: ['S-TOKEN', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'archivist', status: 'placeholder' },
  },
  {
    id: 'back_to_the_raq',
    name: 'Back to the Raq',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Scripture'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'trash', target: { zone: 'library', count: 2, pick: 'random' } },
      { op: 'createCard', defId: { pool: { catalog: 'book' } }, to: 'gy', count: 2 },
    ],
    triggers: [],
    text: 'Trash 2 random cards from your Library and drop 2 Books into your GY.',
    flavor: 'Reshelved, eventually, by someone.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'back_to_the_raq', status: 'placeholder', anim: 'shuffle' },
  },
];

export default cards;
