/**
 * A.10 — Draft Shop: Victory Point and scoring cards.
 *
 * Slice S7 (cards-archetypes). Tokens owned here: Skyscraper, Cursed Pig, Carat.
 *
 * Authoring rule reminders applied throughout this file:
 *  - Plain stat lines live in `stats`, never in `effects` (Buff/Nerf reads `stats`).
 *  - Variable VP ("+X VP, X = ...") is an effect, because a variable cannot be a
 *    printed stat line.
 *  - `EndOfGame` tagged cards are excluded from running VP and score from a
 *    `gameEnd` trigger instead.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'kwzki_cultist',
    name: 'Kwzki Cultist',
    cost: { money: 2 },
    types: ['Points'],
    subtypes: ['Kwzki'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'count(kwzki_cultist)' } }],
    triggers: [],
    text: '+X VP, where X is the number of Kwzki Cultists in your deck.',
    flavor: 'They only make sense in groups.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'kwzki_cultist', status: 'placeholder' },
  },
  {
    id: 'courtyard_of_squeam',
    name: 'Courtyard of Squeam',
    cost: { money: 2 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'floor(4 - avgCostOfDeck)' } }],
    triggers: [],
    text: '+X VP, where X is floor(4 - the average cost of your deck).',
    flavor: 'Cheap company, cheerful company.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'courtyard_of_squeam', status: 'placeholder' },
  },
  {
    id: 'library_of_gods',
    name: 'Library of Gods',
    cost: { money: 5 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'ceil(avgCostOfDeck)' } }],
    triggers: [],
    text: '+X VP, where X is ceil(the average cost of your deck).',
    flavor: 'Only the expensive get shelved.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'library_of_gods', status: 'placeholder' },
  },
  {
    id: 'whale_poaching',
    name: 'Whale Poaching',
    cost: { money: 4 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'floor(deckSize / 12)' } }],
    triggers: [],
    text: '+X VP, where X is floor(your deck size / 12).',
    flavor: 'Bigger boat, bigger haul.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'whale_poaching', status: 'placeholder' },
  },
  {
    id: 'tnacks_ingenuity',
    name: "Tnack's Ingenuity",
    cost: { money: 4 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'floor(5 - deckSize / 12)' } }],
    triggers: [],
    text: '+X VP, where X is floor(5 - your deck size / 12).',
    flavor: 'Elegance is subtraction.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'tnacks_ingenuity', status: 'placeholder' },
  },
  {
    id: 'fountain_of_possibilities',
    name: 'Fountain of Possibilities',
    cost: { money: 4 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'floor(uniqueCardsInDeck / 4)' } }],
    triggers: [],
    text: '+X VP, where X is floor(the number of distinct cards in your deck / 4).',
    flavor: 'Variety, then water.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'fountain_of_possibilities', status: 'placeholder' },
  },
  {
    id: 'marble_columns',
    name: 'Marble Columns',
    cost: { money: 4 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'floor(sdOfDeckCost)' } }],
    triggers: [],
    text: '+X VP, where X is floor(the standard deviation of your deck costs).',
    flavor: 'Uneven heights, even grandeur.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'marble_columns', status: 'placeholder' },
  },
  {
    id: 'stand_together',
    name: 'Stand Together',
    cost: { money: 9 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'uniqueCardsInDeck' } }],
    triggers: [],
    text: '+X VP, where X is the number of distinct cards in your deck.',
    flavor: 'Nobody is redundant.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'stand_together', status: 'placeholder' },
  },
  {
    id: 'treasure_vault',
    name: 'Treasure Vault',
    cost: { money: 8 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [{ op: 'gain', stat: 'vp', amount: { expr: 'ceil(3 + count(diamond))' } }],
    triggers: [],
    text: '+X VP, where X is 3 plus the number of Diamonds in your deck.',
    flavor: 'The door alone cost four.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'treasure_vault', status: 'placeholder' },
  },
  {
    id: 'monumental_works',
    name: 'Monumental Works',
    cost: { money: 5 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    // `mostExpensive` ranks by printed cost, which an upgrade never touches, and
    // `selfCounter` sums every counter on the picked card: for a Relic that is
    // its 'playCount' (core/play.ts stamps one per play) on top of its
    // 'upgrades', so the old body paid out at roughly double. Both halves have
    // to come from the 'upgrades' counter alone, and no expression variable
    // reports the largest one.
    //
    // A ladder does it in card data. Each rung asks "does any Relic in my deck
    // hold at least k upgrades?" and pays +1 VP if so, so the rungs sum to
    // exactly the highest 'upgrades' count in the deck — never to the total
    // across Relics, which is the "no double counting" clause. The last rung is
    // the ceiling, so the ceiling is printed on the card.
    effects: [
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 1 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 2 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 3 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 4 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 5 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 6 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 7 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 8 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 9 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
      { op: 'conditional', if: { has: { target: { zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Relic', counter: { key: 'upgrades', gte: 10 } } } } }, then: [{ op: 'gain', stat: 'vp', amount: 1 }] },
    ],
    triggers: [],
    text: '+X VP, where X is the number of upgrades on the most upgraded Relic in your deck, to a maximum of 10. No double counting.',
    flavor: 'One monument, many chisels.',
    complexity: 'T3',
    subsystems: ['S-BUFF', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'monumental_works', status: 'placeholder' },
  },
  {
    id: 'ascendant_spread',
    name: 'Ascendant Spread',
    cost: { money: 2 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [],
    triggers: [
      {
        on: 'onGain',
        effects: [
          {
            op: 'random',
            branches: [
              { weight: 1, effects: [{ op: 'scoreOnCard', target: { self: true }, amount: 1, secret: true }], displayAs: 'Ascendant Spread is worth 1 or 2 VP.' },
              { weight: 1, effects: [{ op: 'scoreOnCard', target: { self: true }, amount: 2, secret: true }], displayAs: 'Ascendant Spread is worth 1 or 2 VP.' },
            ],
          },
        ],
      },
    ],
    text: 'When you gain this, it secretly becomes worth 1 or 2 VP. Only you know which.',
    flavor: 'Read the cards. Do not show the cards.',
    complexity: 'T3',
    subsystems: ['S-HIDDEN', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'ascendant_spread', status: 'placeholder', anim: 'shuffle' },
  },
  {
    id: 'mercenary_280',
    name: 'Mercenary 280',
    cost: { money: 3 },
    types: ['Action', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { expr: 'max(0, 1 - abs(sumOfDeckCosts - 280))' },
        then: [{ op: 'gain', stat: 'vp', amount: 280 }],
      },
    ],
    triggers: [],
    text: '+280 VP if the sum of the costs of every card in your deck is exactly 280.',
    flavor: 'He does not negotiate. He counts.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'mercenary_280', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'oh_mr_lebon',
    name: 'Oh Mr. Lebon',
    cost: { money: 3 },
    types: ['Action', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        // `countIn` can only reach your own zones, so the comparison needs a
        // real variable for the tallest opponent Library. No Condition can
        // stand in for it either: `has.atLeast` is a literal number, never an
        // Amount, so a selector over opponent Libraries can never be measured
        // against `libraryHeight`.
        //
        // 'tallestOpponentLibrary' is not in EXPR_VARS yet, so readVar throws,
        // evalCondition catches, and the gate reads false — the card scores
        // nothing until the variable lands. That is the fail-closed direction
        // on purpose: the old expression read as max(0, libraryHeight) and paid
        // an unconditional +2 VP on every single play.
        if: { expr: 'libraryHeight > tallestOpponentLibrary' },
        then: [{ op: 'scoreOnCard', target: { self: true }, amount: 2 }],
      },
    ],
    triggers: [],
    text: 'If your Library is taller than every opponent’s, score +2 VP on this card. ({vp} VP so far.)',
    flavor: 'He counts other people’s stacks for a living.',
    complexity: 'T3',
    subsystems: ['S-PERSIST'],
    shop: 'draft',
    art: { key: 'oh_mr_lebon', status: 'placeholder' },
  },
  {
    id: 'tilted_towers',
    name: 'Tilted Towers',
    cost: { money: 3 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { vp: 1 },
    effects: [],
    triggers: [
      {
        on: 'onTrash',
        effects: [
          { op: 'addCounter', target: { self: true }, key: 'trashSurvivals', amount: 1 },
          {
            op: 'conditional',
            if: { expr: 'max(0, selfCounter - 1)' },
            then: [{ op: 'createCard', defId: 'tilted_towers', to: 'gy', statDelta: { vp: 3 } }],
            else: [{ op: 'moveTo', target: { self: true }, zone: 'gy' }],
          },
        ],
      },
    ],
    text: '+1 VP. Survives the first 2 trashings. On the second, it rebuilds worth 3 more VP. ({trashSurvivals} collapses so far.)',
    flavor: 'It leans. It has always leaned.',
    complexity: 'T3',
    subsystems: ['S-PERSIST'],
    shop: 'draft',
    art: { key: 'tilted_towers', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'skyscraper',
    name: 'Skyscraper',
    cost: { money: 3 },
    types: ['Token', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'token',
    keywords: [],
    stats: {},
    effects: [],
    triggers: [],
    text: 'Worth {vp} VP. Its value was set when The Conglomerate built it.',
    flavor: 'Every floor was a smaller building once.',
    complexity: 'T2',
    subsystems: ['S-TOKEN', 'S-PERSIST'],
    notPurchasable: true,
    art: { key: 'skyscraper', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'the_conglomerate',
    name: 'The Conglomerate',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1, cards: 1 },
    effects: [
      { op: 'createCard', defId: 'skyscraper', to: 'gy' },
      {
        // `bottom` is the Skyscraper this play just appended; `top` would score
        // onto an older one. The amount is a VP *sum*, which no card count can
        // express, so it reads a dedicated variable: countIn counts cards, and
        // paying +1 per Points card would turn every -1 VP card (Cursed Pig,
        // Garlic, Chopped Chuzz) into +1, which is a worse answer than none.
        //
        // 'vpInHand' is not in EXPR_VARS yet, so evalAmount swallows the throw
        // and the Skyscraper is built worth 0 while the hand is still trashed.
        op: 'scoreOnCard',
        target: { zone: 'gy', filter: { defId: 'skyscraper' }, count: 1, pick: 'bottom' },
        amount: { expr: 'vpInHand' },
      },
      { op: 'trash', target: { zone: 'hand', filter: { type: 'Points' } } },
    ],
    triggers: [],
    text: '+1 Action, +1 Card. Trash every VP card in your hand and add a Skyscraper worth their total VP to your GY.',
    flavor: 'Merged, floor by floor.',
    complexity: 'T3',
    subsystems: ['S-TOKEN', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'the_conglomerate', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'master_of_jlore',
    name: 'Master of Jlore',
    cost: { money: 12 },
    types: ['Action', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1, cards: 1, vp: 3 },
    effects: [{ op: 'createCard', defId: 'jlore', to: 'gy' }],
    triggers: [],
    text: '+1 Action, +1 Card, +3 VP. Add a Jlore to your GY.',
    flavor: 'Mastery is just owning more of it.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'master_of_jlore', status: 'placeholder' },
  },
  {
    id: 'constellation',
    name: 'Constellation',
    cost: { money: 10 },
    types: ['Points'],
    subtypes: [],
    tags: ['EndOfGame'],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [],
    // `meta/scoring.ts` has a scorer that walks the run properly, but nothing
    // calls it — `endgame.ts` scores through `core/scoring.computeScores`. So
    // the payout has to ride the gameEnd trigger like every other End of Game
    // card. `longestCostRun` is an EXPR_VAR because the run is a property of
    // the deck's cost set, not a card count no filter can name.
    triggers: [
      {
        on: 'gameEnd',
        effects: [
          { op: 'gain', stat: 'vp', amount: { expr: 'longestCostRun' } },
          {
            op: 'trash',
            target: {
              who: 'self',
              zone: ['library', 'hand', 'gy', 'play'],
              count: { expr: 'longestCostRun' },
              pick: 'cheapest',
            },
          },
        ],
      },
    ],
    text: 'End of Game. For each Constellation: trash the longest unbroken run of cards costing (1), (2), ... (X) and gain +X VP. Not counted in your running VP.',
    flavor: 'Draw the line between them and it means something.',
    complexity: 'T4',
    subsystems: ['S-ENDGAME'],
    shop: 'draft',
    art: { key: 'constellation', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'star_aligner',
    name: 'Star Aligner',
    cost: { money: 7 },
    types: ['Points'],
    subtypes: [],
    tags: ['EndOfGame'],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [],
    triggers: [
      {
        on: 'gameEnd',
        effects: [
          {
            op: 'conditional',
            if: { expr: 'max(0, 1 - abs(count(cost7) - 7))' },
            then: [{ op: 'gain', stat: 'vp', amount: 7 }],
          },
        ],
      },
    ],
    text: 'End of Game. +7 VP if exactly 7 cards in your deck cost (7). Not counted in your running VP.',
    flavor: 'Seven, seven, seven. No more, no fewer.',
    complexity: 'T3',
    subsystems: ['S-ENDGAME'],
    shop: 'draft',
    art: { key: 'star_aligner', status: 'placeholder' },
  },
  {
    id: 'fist_of_jraxxus',
    name: 'Fist of Jraxxus',
    cost: { money: 4 },
    types: ['Action', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { money: 2, vp: 1 },
    effects: [],
    triggers: [{ on: 'onDiscard', effects: [{ op: 'gain', stat: 'money', amount: 2 }] }],
    text: '+2 Money, +1 VP. When you discard this, +2 Money.',
    flavor: 'It pays whether it lands or not.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'fist_of_jraxxus', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'carat',
    name: 'Carat',
    cost: { money: 1 },
    types: ['Action', 'Food', 'Token', 'Points'],
    subtypes: ['Carrot'],
    tags: [],
    rarity: 'token',
    keywords: ['Flimsy'],
    stats: { money: 1, vp: 1 },
    effects: [],
    triggers: [],
    text: 'Flimsy. +1 Money, +1 VP.',
    flavor: 'A carrot, weighed as a gem.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'carat', status: 'placeholder', anim: 'coin' },
  },
  {
    id: 'bullseye',
    name: 'Bullseye',
    cost: { money: 3 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { vp: 1 },
    effects: [],
    triggers: [
      {
        on: 'onDiscard',
        effects: [
          {
            op: 'forEach',
            over: { zone: 'hand', filter: { cost: { lte: 1 } } },
            effects: [
              {
                // A Selector pools every opponent hand into one list, so a bare
                // `count: 1` Nerfs one card table-wide. Asking for one per
                // opponent is the closest this can get without a per-player
                // count. The guard keeps an empty table from falling back onto
                // the source card, which `nerf` does when nothing is selected.
                op: 'conditional',
                if: { has: { target: { who: 'eachOpponent', zone: 'hand' }, atLeast: 1 } },
                then: [
                  {
                    op: 'nerf',
                    scope: 'instance',
                    target: { who: 'eachOpponent', zone: 'hand', count: { expr: 'playerCount - 1' }, pick: 'random' },
                  },
                ],
              },
            ],
          },
          { op: 'trash', target: { zone: 'hand', filter: { cost: { lte: 1 } } } },
        ],
      },
    ],
    text: '+1 VP. When you discard this: trash every card in your hand costing (1) or less, and Nerf one card in each opponent’s hand per card trashed.',
    flavor: 'Dead centre, every time.',
    complexity: 'T3',
    subsystems: ['S-BUFF'],
    shop: 'draft',
    art: { key: 'bullseye', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'mass_production',
    name: 'Mass Production',
    cost: { money: 1 },
    types: ['Action', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 2, cards: 2, vp: -1 },
    effects: [{ op: 'copyCard', target: { self: true }, to: 'gy' }],
    triggers: [],
    text: '+2 Actions, +2 Cards, -1 VP. Add a copy of this to your GY.',
    flavor: 'Scale first. Quality is a later problem.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'mass_production', status: 'placeholder' },
  },
  {
    id: 'garlic',
    name: 'Garlic',
    cost: { money: 0 },
    types: ['Action', 'Points', 'Food'],
    subtypes: ['Garlic'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { vp: -1 },
    effects: [],
    triggers: [{ on: 'onTrash', effects: [{ op: 'gain', stat: 'money', amount: 7 }] }],
    text: '-1 VP. When this is trashed, +7 Money.',
    flavor: 'Worth more crushed.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'garlic', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'lotto_ticket',
    name: 'Lotto Ticket',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'createCard', defId: 'tix', to: 'library', position: 'random' },
      { op: 'shuffle', zone: 'library' },
      // Recruited aside first, so `selfCost` reads the card that was actually
      // drawn. Recruiting straight to hand and re-scanning it paid out on the
      // most expensive Points card already there, and paid even when the
      // Library held none.
      { op: 'recruit', zone: 'library', filter: { type: 'Points' }, count: 1, to: 'aside' },
      {
        op: 'forEach',
        over: { zone: 'aside', filter: { type: 'Points' } },
        effects: [
          { op: 'gain', stat: 'money', amount: { expr: 'selfCost' } },
          { op: 'moveTo', target: { self: true }, zone: 'hand' },
        ],
      },
    ],
    triggers: [],
    text: 'Shuffle a Tix into your Library, then draw a Points card from it and gain Money equal to that card’s cost.',
    flavor: 'Somebody has to win.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'lotto_ticket', status: 'placeholder', anim: 'shuffle' },
  },
  {
    id: 'tixatus',
    name: 'Tixatus',
    cost: { money: 6 },
    types: ['Action', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['PlayOnBuy'],
    stats: { vp: 4 },
    effects: [
      { op: 'moveTo', target: { zone: 'library', count: 5, pick: 'top' }, zone: 'aside' },
      {
        op: 'forEach',
        over: { zone: 'aside', filter: { defId: 'tix' } },
        effects: [
          { op: 'gain', stat: 'money', amount: 1 },
          {
            // Inside a forEach `{self:true}` is the iterated Tix, which the next
            // node trashes — the VP has to be named onto Tixatus itself.
            op: 'scoreOnCard',
            target: { zone: ['play', 'gy'], filter: { defId: 'tixatus' }, count: 1, pick: 'lastPlayed' },
            amount: 1,
          },
        ],
      },
      { op: 'trash', target: { zone: 'aside' } },
    ],
    triggers: [],
    text: 'Play on Buy. +4 VP. Trash the top 5 cards of your Library. For each Tix trashed, +1 Money and score +1 VP on this card. ({vp} VP scored.)',
    flavor: 'It eats tickets and grows.',
    complexity: 'T3',
    subsystems: ['S-PERSIST'],
    shop: 'draft',
    art: { key: 'tixatus', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'squire_of_j',
    name: 'Squire of J',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { has: { target: { zone: 'hand', filter: { defId: 'jlore' } }, atLeast: 1 } },
        then: [
          { op: 'discard', target: { zone: 'hand', filter: { defId: 'jlore' }, count: 1, pick: 'choose' } },
          { op: 'gain', stat: 'money', amount: 4 },
        ],
      },
    ],
    triggers: [],
    text: 'Discard a Jlore for +4 Money.',
    flavor: 'He carries it. He does not own it.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'squire_of_j', status: 'placeholder', anim: 'coin' },
  },
  {
    id: 'lord_of_j',
    name: 'Lord of J',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { has: { target: { zone: 'hand', filter: { defId: 'jlore' } }, atLeast: 1 } },
        then: [
          { op: 'discard', target: { zone: 'hand', filter: { defId: 'jlore' }, count: 1, pick: 'choose' } },
          { op: 'createCard', defId: 'jlore', to: 'gy' },
        ],
      },
    ],
    triggers: [],
    text: 'Discard a Jlore to add a Jlore to your GY.',
    flavor: 'Lordship is laundering, slowly.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'lord_of_j', status: 'placeholder' },
  },
  {
    id: 'purple_rain',
    name: 'Purple Rain',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'forEach',
        over: { zone: 'hand', filter: { rarity: 'epic' } },
        effects: [
          {
            op: 'random',
            branches: [
              { weight: 1, effects: [{ op: 'createCard', defId: 'tix', to: 'gy' }] },
              { weight: 1, effects: [{ op: 'createCard', defId: 'robux', to: 'gy' }] },
            ],
          },
        ],
      },
    ],
    triggers: [],
    text: 'For each Epic card in your hand, add a Tix or a Robux at random to your GY.',
    flavor: 'It only ever falls on the rich.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'purple_rain', status: 'placeholder', anim: 'coin' },
  },
  {
    id: 'iced_up',
    name: 'Iced Up',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        // "Any number" has to include none. A forEach asking for handSize Rares
        // always wants every Rare in hand, so the prompt was skipped and the
        // discard was mandatory. The declining branch is a `choose` rather than
        // a `min: 0` selection, because resolving a selection with nothing
        // picked runs the continuation once against the source card instead of
        // zero times.
        op: 'choose',
        options: [
          {
            label: 'Discard Rares for +2 Money each',
            effects: [
              {
                op: 'selectCards',
                from: { zone: 'hand', filter: { rarity: 'rare' } },
                min: 1,
                max: { expr: 'handSize' },
                then: [
                  { op: 'discard', target: { self: true } },
                  { op: 'gain', stat: 'money', amount: 2 },
                ],
              },
            ],
          },
          { label: 'Discard nothing', effects: [] },
        ],
      },
    ],
    triggers: [],
    text: 'Discard any number of Rare cards from your hand. +2 Money for each.',
    flavor: 'Every chain, every finger.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'iced_up', status: 'placeholder', anim: 'coin' },
  },
  {
    id: 'yuyas_embrace',
    name: "Yuya's Embrace",
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'discover',
        pool: { scope: 'knownUniverse', filter: { type: 'Points' } },
        count: 3,
        pick: 1,
        prompt: 'Discover a Points card.',
        // '$discovered' is the card the player actually picked. Re-sampling the
        // pool here handed out a fourth, unrelated card.
        then: [{ op: 'createCard', defId: '$discovered', to: 'gy' }],
      },
    ],
    triggers: [],
    text: 'Flimsy. Discover a Points card from your Known Universe and add it to your GY.',
    flavor: 'She holds on until it scores.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    shop: 'draft',
    art: { key: 'yuyas_embrace', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'chopped_chuzz',
    name: 'Chopped Chuzz',
    cost: { money: -1 },
    types: ['Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { vp: -1 },
    effects: [],
    triggers: [{ on: 'onTrash', effects: [{ op: 'gain', stat: 'actions', amount: 3 }] }],
    text: '-1 VP. When this attempts to Fuse, it is trashed instead. When trashed, +3 Actions.',
    flavor: 'It does not fuse. It scatters.',
    complexity: 'T3',
    subsystems: ['S-FUSE'],
    shop: 'draft',
    art: { key: 'chopped_chuzz', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'cursed_pig',
    name: 'Cursed Pig',
    cost: { money: 0 },
    types: ['Token', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'token',
    keywords: [],
    stats: { vp: -1 },
    effects: [],
    triggers: [],
    text: '-1 VP.',
    flavor: 'It followed you home. It is staying.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'cursed_pig', status: 'placeholder' },
  },
  {
    id: 'virtual_bank_robbery',
    name: 'Virtual Bank Robbery',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'createCard', defId: 'robux', to: 'gy' },
      { op: 'createCard', defId: 'tix', to: 'gy' },
    ],
    triggers: [],
    text: 'Flimsy. Add a Robux and a Tix to your GY.',
    flavor: 'No vault, no guards, no witnesses.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'virtual_bank_robbery', status: 'placeholder', anim: 'coin' },
  },
];

export default cards;
