/**
 * A.12 — Draft Shop: the Warhero Token archetype.
 *
 * Slice S7 (cards-archetypes). The Warhero Token itself (`warhero_token`) is
 * owned by the tribes slice and is only referenced here.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'false_hero',
    name: 'False Hero',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['Warhero'],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { money: -1 },
    effects: [{ op: 'createCard', defId: 'warhero_token', to: 'gy', keywords: ['Flimsy'] }],
    triggers: [],
    text: '-1 Money. Add a Flimsy Warhero Token to your GY.',
    flavor: 'The statue went up before the battle did.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'false_hero', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'summon' },
  },
  {
    id: 'tylannt',
    name: 'Tylannt',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: ['Warhero'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, cards: 1 },
    effects: [{ op: 'createCard', defId: 'warhero_token', to: 'library', position: 'top' }],
    triggers: [],
    text: '+1 Action, +1 Card. Add a Warhero Token to the top of your Library.',
    flavor: 'He promotes from within. Always himself.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'tylannt', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'summon' },
  },
  {
    id: 'aura_farming',
    name: 'Aura Farming',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Warhero'],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [{ op: 'createCard', defId: 'warhero_token', to: 'gy', count: 2, keywords: ['Flimsy'] }],
    triggers: [],
    text: 'Add 2 Flimsy Warhero Tokens to your GY.',
    flavor: 'Posture is a renewable resource.',
    complexity: 'T1',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'aura_farming', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'summon' },
  },
  {
    id: 'aura_gambit',
    name: 'Aura Gambit',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Warhero'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'createCard',
        defId: 'warhero_token',
        to: 'gy',
        who: 'eachOpponent',
        keywords: ['Flimsy'],
        counters: { auraGambit: 1 },
      },
    ],
    triggers: [],
    text: '+1 Action. Give each opponent a Flimsy Warhero Token. When one of those Tokens is trashed, it goes to your GY instead.',
    flavor: 'A gift with a return address.',
    complexity: 'T3',
    subsystems: ['S-TOKEN', 'S-PVP'],
    shop: 'draft',
    art: { key: 'aura_gambit', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'summon' },
  },
  {
    id: 'generational_aura_debt',
    name: 'Generational Aura Debt',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Warhero'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      { op: 'trash', target: { zone: 'library', count: 4, pick: 'top' } },
      { op: 'createCard', defId: 'warhero_token', to: 'library', count: 4, position: 'top', keywords: ['Flimsy'] },
      { op: 'delayed', when: 'startOfNextTurn', effects: [{ op: 'gain', stat: 'money', amount: -4 }] },
    ],
    triggers: [],
    text: 'Replace the top 4 cards of your Library with Flimsy Warhero Tokens. -4 Money at the start of your next turn.',
    flavor: 'Your grandchildren will also be very impressive.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'generational_aura_debt', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'summon' },
  },
];

export default cards;
