/**
 * A.1 Resource Shop + A.2 Points Shop — the seven Basic cards.
 * Always present in every match. Never drafted, never in random pools as
 * draft-shop piles (they have their own fixed shops).
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  // --- A.1 Resource Shop ---------------------------------------------------
  {
    id: 'copper',
    name: 'Copper',
    cost: { money: 0 },
    types: ['Resource'],
    subtypes: ['Copper'],
    tags: [],
    rarity: 'basic',
    keywords: [],
    stats: { money: 1 },
    effects: [],
    triggers: [],
    text: '+1 Money.',
    flavor: 'It adds up. Slowly.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'resource',
    art: { key: 'copper', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'silver',
    name: 'Silver',
    cost: { money: 3 },
    types: ['Resource'],
    subtypes: ['Silver'],
    tags: [],
    rarity: 'basic',
    keywords: [],
    stats: { money: 2 },
    effects: [],
    triggers: [],
    text: '+2 Money.',
    flavor: 'The honest middle.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'resource',
    art: { key: 'silver', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'gold',
    name: 'Gold',
    cost: { money: 6 },
    types: ['Resource'],
    subtypes: ['Gold'],
    tags: [],
    rarity: 'basic',
    keywords: [],
    stats: { money: 3 },
    effects: [],
    triggers: [],
    text: '+3 Money.',
    flavor: 'Heavy in the hand.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'resource',
    art: { key: 'gold', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'diamond',
    name: 'Diamond',
    cost: { money: 10 },
    types: ['Resource'],
    subtypes: ['Diamond'],
    tags: [],
    rarity: 'basic',
    keywords: [],
    stats: { money: 5 },
    effects: [],
    triggers: [],
    text: '+5 Money.',
    flavor: 'Compressed patience.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'resource',
    art: { key: 'diamond', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },

  // --- A.2 Points Shop -----------------------------------------------------
  {
    id: 'tix',
    name: 'Tix',
    cost: { money: 2 },
    types: ['Points'],
    subtypes: ['Tix'],
    tags: [],
    rarity: 'basic',
    keywords: [],
    stats: { vp: 1 },
    effects: [],
    triggers: [],
    text: '+1 VP.',
    flavor: 'Redeemable at the front desk.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'points',
    art: { key: 'tix', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'robux',
    name: 'Robux',
    cost: { money: 5 },
    types: ['Points'],
    subtypes: ['Robux'],
    tags: [],
    rarity: 'basic',
    keywords: [],
    stats: { vp: 2 },
    effects: [],
    triggers: [],
    text: '+2 VP.',
    flavor: 'Not financial advice.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'points',
    art: { key: 'robux', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'jlore',
    name: 'Jlore',
    cost: { money: 8 },
    types: ['Points'],
    subtypes: ['Jlore'],
    tags: [],
    rarity: 'basic',
    keywords: [],
    stats: { vp: 3 },
    effects: [],
    triggers: [
      {
        on: 'onPileEmpty',
        zones: ['shop'],
        effects: [{ op: 'endGame', reason: 'jlorePileEmpty' }],
      },
    ],
    text: '+3 VP. Emptying this pile ends the game.',
    flavor: 'The whole point.',
    complexity: 'T1',
    subsystems: ['S-CORE', 'S-ENDGAME'],
    shop: 'points',
    art: { key: 'jlore', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
];

export default cards;
