/**
 * A.7 Draft Shop — draw and hand sculpting.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'rapid_draw',
    name: 'Rapid Draw',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { cards: 4 },
    effects: [{ op: 'discard', target: { who: 'self', zone: 'hand', count: 4, pick: 'choose' } }],
    triggers: [],
    text: '+4 Cards, then discard 4 cards.',
    flavor: 'Churn is a strategy.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'rapid_draw', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'balanced_rapid_draw',
    name: 'Balanced Rapid Draw',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: ['Legacy'],
    rarity: 'common',
    keywords: [],
    stats: { cards: 4, actions: 1 },
    effects: [{ op: 'discard', target: { who: 'self', zone: 'hand', count: 4, pick: 'choose' } }],
    triggers: [],
    text: '+4 Cards, then discard 4 cards. +1 Action.',
    flavor: 'The errata version.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'balanced_rapid_draw', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'overclocked_rapid_draw',
    name: 'Overclocked Rapid Draw',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 8 },
    effects: [{ op: 'discard', target: { who: 'self', zone: 'hand', count: 8, pick: 'choose' } }],
    triggers: [],
    text: '+8 Cards, then discard 8 cards.',
    flavor: 'Runs hot. Runs anyway.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'overclocked_rapid_draw', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'prime_rapid_draw',
    name: 'Prime Rapid Draw',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 5, actions: 1 },
    effects: [{ op: 'discard', target: { who: 'self', zone: 'hand', count: 4, pick: 'choose' } }],
    triggers: [],
    text: '+5 Cards, then discard 4 cards. +1 Action.',
    flavor: 'One card ahead.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'prime_rapid_draw', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'card_destruction',
    name: 'Card Destruction',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'selectCards',
        from: { who: 'self', zone: 'hand' },
        min: 0,
        max: { expr: 'handSize' },
        then: [
          { op: 'discard', target: { self: true } },
          { op: 'draw', amount: 1 },
        ],
      },
    ],
    triggers: [],
    text: 'Discard up to X cards, then draw X cards. +1 Action.',
    flavor: 'Out with the old, in with the same.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'card_destruction', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'profe_yates',
    name: 'Profe Yates',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { cards: 3 },
    effects: [],
    triggers: [],
    text: '+3 Cards.',
    flavor: 'Assigns reading.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'profe_yates', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'sack_of_cards',
    name: 'Sack of Cards',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1, cards: 4 },
    effects: [],
    triggers: [],
    text: '+1 Action, +4 Cards.',
    flavor: 'Just a sack. Just cards.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'sack_of_cards', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'keyhole',
    name: 'Keyhole',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'reveal', target: { who: 'self', zone: 'library', count: 3, pick: 'top' } },
      {
        op: 'moveTo',
        target: { who: 'self', zone: 'library', count: 1, pick: 'choose' },
        zone: 'hand',
      },
      {
        op: 'moveTo',
        target: { who: 'self', zone: 'library', count: 1, pick: 'choose' },
        zone: 'gy',
      },
    ],
    triggers: [],
    text: 'Look at the top 3 cards of your Library: put one in your hand, discard one, leave one on top. +1 Action.',
    flavor: 'You only need one eye.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'keyhole', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'harbinger',
    name: 'Harbinger',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'moveTo',
        target: { who: 'self', zone: 'gy', count: 1, pick: 'choose' },
        zone: 'library',
        position: 'top',
      },
    ],
    triggers: [],
    text: 'Put a card from your GY on top of your Library. +1 Action.',
    flavor: 'It comes back around.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'harbinger', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'star_compass',
    name: 'Star Compass',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 2 },
    effects: [
      {
        op: 'conditional',
        if: {
          has: {
            target: { who: 'self', zone: 'hand', count: 2, pick: 'lastPlayed' },
            atLeast: 2,
          },
        },
        then: [{ op: 'draw', amount: 2 }],
      },
    ],
    triggers: [],
    text: '+2 Cards. If the two cards drawn share a name, draw 2 more and repeat the check.',
    flavor: 'North, north, north again.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'star_compass', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'snowball',
    name: 'Snowball',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 1 },
    effects: [
      {
        op: 'repeat',
        times: {
          expr: 'min(3, countIn(play, oneCost))',
        },
        effects: [{ op: 'draw', amount: 1 }],
      },
    ],
    triggers: [],
    text: '+1 Card, and another for each consecutive (1)-cost card played before this, up to 3 more.',
    flavor: 'It gets bigger. That is the whole thing.',
    complexity: 'T3',
    subsystems: ['S-COMBO'],
    shop: 'draft',
    art: { key: 'snowball', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'small_time_racketeer',
    name: 'Small Time Racketeer',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 1 },
    effects: [
      {
        op: 'repeat',
        times: 5,
        effects: [
          {
            op: 'conditional',
            if: {
              not: {
                has: {
                  target: { who: 'self', zone: 'hand', filter: { cost: { gte: 2 } }, pick: 'lastPlayed' },
                  atLeast: 1,
                },
              },
            },
            then: [{ op: 'draw', amount: 1 }],
          },
        ],
      },
    ],
    triggers: [],
    text: '+1 Card. Repeat until you draw a card costing (2) or more.',
    flavor: 'Nickels, mostly.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'small_time_racketeer', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'big_time_racketeer',
    name: 'Big Time Racketeer',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 1 },
    effects: [
      {
        op: 'repeat',
        times: 5,
        effects: [
          {
            op: 'conditional',
            if: {
              not: {
                has: {
                  target: { who: 'self', zone: 'hand', filter: { cost: { lte: 2 } }, pick: 'lastPlayed' },
                  atLeast: 1,
                },
              },
            },
            then: [{ op: 'draw', amount: 1 }],
          },
        ],
      },
    ],
    triggers: [],
    text: '+1 Card. Repeat until you draw a card costing (2) or less.',
    flavor: 'He only wants the good stuff.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'big_time_racketeer', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'essential_oils',
    name: 'Essential Oils',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'repeat',
        times: 4,
        effects: [
          {
            op: 'conditional',
            if: { expr: '4 - avgCostOfDeck' },
            then: [{ op: 'draw', amount: 1 }],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Draw cards until the combined cost of the cards drawn reaches (4).',
    flavor: 'Cures whatever the deck has.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'essential_oils', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'one_more_track',
    name: 'One More Track',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { not: { has: { target: { who: 'self', zone: 'hand' }, atLeast: 1 } } },
        then: [{ op: 'draw', amount: 5 }],
        else: [{ op: 'draw', amount: 1 }],
      },
    ],
    triggers: [],
    text: '+1 Card. If this was the last card in your hand, +5 Cards instead.',
    flavor: 'Just one more. Then bed.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'one_more_track', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'around_the_world',
    name: 'Around the World',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'conditional', if: { combo: 5 }, then: [{ op: 'draw', amount: 5 }] },
    ],
    triggers: [],
    text: 'Combo 5: +5 Cards.',
    flavor: 'Eighty days, five cards.',
    complexity: 'T3',
    subsystems: ['S-COMBO'],
    shop: 'draft',
    art: { key: 'around_the_world', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'power_of_4',
    name: 'Power of 4',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 4 },
    effects: [{ op: 'discard', target: { who: 'self', zone: 'hand', count: 4, pick: 'choose' } }],
    triggers: [],
    text: 'Discard 4 cards. +4 Actions.',
    flavor: 'Four for four. Fair.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'power_of_4', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'false_dichotomy',
    name: 'False Dichotomy',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 2 },
    effects: [{ op: 'discardDownTo', amount: 2 }],
    triggers: [],
    text: 'Discard down to 2 cards in hand. +2 Actions.',
    flavor: 'There were always more than two options.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'false_dichotomy', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'buffer_overflow',
    name: 'Buffer Overflow',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 4 },
    effects: [
      {
        op: 'forEach',
        over: { who: 'self', zone: 'hand', filter: { type: 'Resource' }, count: 2, pick: 'random' },
        effects: [{ op: 'gain', stat: 'money', amount: 1 }],
      },
      { op: 'discard', target: { who: 'self', zone: 'hand', count: 2, pick: 'random' } },
    ],
    triggers: [],
    text: '+4 Cards, then discard 2 at random. +1 Money for each Resource discarded this way.',
    flavor: 'Segmentation fault (cards dumped).',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'buffer_overflow', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'quantum_cut',
    name: 'Quantum Cut',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'reveal', target: { who: 'self', zone: 'library', count: 2, pick: 'top' } },
      {
        op: 'conditional',
        if: {
          has: {
            target: { who: 'self', zone: 'library', count: 2, pick: 'top' },
            atLeast: 2,
          },
        },
        then: [{ op: 'draw', amount: 3 }],
        else: [{ op: 'gain', stat: 'money', amount: 2 }],
      },
    ],
    triggers: [],
    text: 'Reveal the top 2 cards of your Library. If they cost the same, +3 Cards; otherwise +2 Money. +1 Action.',
    flavor: 'Both, until you look.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'quantum_cut', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'fast_life',
    name: 'Fast Life',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { money: 2 },
    effects: [{ op: 'mill', amount: 6 }],
    triggers: [],
    text: 'Mill 6. +2 Money.',
    flavor: 'Burn the deck, spend the ashes.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'fast_life', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'pocket_pouch',
    name: 'Pocket Pouch',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, cards: 1 },
    effects: [
      { op: 'discard', target: { who: 'self', zone: 'hand', count: 1, pick: 'choose' } },
      {
        op: 'delayed',
        when: 'startOfNextTurn',
        effects: [
          {
            op: 'moveTo',
            target: { who: 'self', zone: 'gy', count: 1, pick: 'lastPlayed' },
            zone: 'hand',
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discard a card. It returns to your hand at the start of your next turn. +1 Action, +1 Card.',
    flavor: 'Pocketed, not lost.',
    complexity: 'T2',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'pocket_pouch', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'stowaway',
    name: 'Stowaway',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 3, actions: 1 },
    effects: [
      {
        op: 'setKeyword',
        target: { who: 'self', zone: 'hand', count: 1, pick: 'random' },
        keyword: 'Temporary',
        on: true,
      },
    ],
    triggers: [],
    text: 'A random card in your hand becomes Temporary. +3 Cards, +1 Action.',
    flavor: 'Somebody got on board who should not have.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'stowaway', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'sleepy_joe_bider',
    name: 'Sleepy Joe Bider',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 2 },
    effects: [{ op: 'endTurn' }],
    triggers: [],
    text: '+2 Cards. End your turn immediately without discarding your hand.',
    flavor: 'That is enough for today.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'sleepy_joe_bider', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'tanyays_unstable_element',
    name: "Tanyay's Unstable Element",
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'legendary',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'draw', amount: { expr: 'libraryHeight' } },
      { op: 'nextCardModifier', mod: { appliesTo: 'play', multiply: 0, multiplyStats: ['cards'], uses: 99 } },
    ],
    triggers: [],
    text: 'Flimsy. Draw your entire Library. You cannot draw any more cards this turn.',
    flavor: 'It goes off all at once or not at all.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'tanyays_unstable_element', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'explode' },
  },
  {
    id: 'milkshake',
    name: 'Milkshake',
    cost: { money: 4 },
    types: ['Action', 'Food', 'Token'],
    subtypes: ['Milkshake'],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: { cards: 4, actions: 1 },
    effects: [
      {
        op: 'delayed',
        when: 'endOfTurn',
        effects: [{ op: 'gain', stat: 'cards', amount: -2 }],
      },
    ],
    triggers: [],
    text: 'Flimsy. +4 Cards, +1 Action. Draw 2 fewer cards at the end of this turn.',
    flavor: 'Brings all the boys to the discard pile.',
    complexity: 'T2',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'milkshake', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'merge_sort',
    name: 'Merge Sort',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      { op: 'moveTo', target: { who: 'self', zone: 'gy' }, zone: 'library' },
      { op: 'shuffle', zone: 'library' },
      { op: 'sortLibraryByCost' },
    ],
    triggers: [],
    text: 'Shuffle your GY into your Library, then sort your Library by ascending cost.',
    flavor: 'O(n log n) and worth it.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'merge_sort', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'shuffle' },
  },
  {
    id: 'save_for_later',
    name: 'Save for Later',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { buys: 1, money: 1 },
    effects: [
      { op: 'createCard', defId: 'permanent_hand_box', to: 'library', position: 'random' },
      { op: 'shuffle', zone: 'library' },
      { op: 'trash', target: { who: 'self', zone: 'hand' } },
    ],
    triggers: [],
    text: '+1 Buy, +1 Money. Copy your hand into a Permanent: Hand Box, shuffle it into your Library, then trash your hand.',
    flavor: 'You will want that later. Probably.',
    complexity: 'T4',
    subsystems: ['S-TOKEN', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'save_for_later', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'repackage',
    name: 'Repackage',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'createCard', defId: 'temporary_hand_box', to: 'library', position: 'random' },
      { op: 'shuffle', zone: 'library' },
    ],
    triggers: [],
    text: '+1 Action. Copy your hand into a Temporary: Hand Box and shuffle it into your Library.',
    flavor: 'Same contents, new box.',
    complexity: 'T4',
    subsystems: ['S-TOKEN', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'repackage', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'echo_forge',
    name: 'Echo Forge',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'copyCard',
        target: { who: 'self', zone: 'play', filter: { type: 'Action' }, count: 1, pick: 'choose' },
        to: 'library',
        keywords: ['Temporary'],
      },
      {
        op: 'moveTo',
        target: { who: 'self', zone: 'library', count: 1, pick: 'lastPlayed' },
        zone: 'library',
        position: 'top',
      },
    ],
    triggers: [],
    text: 'Put a Temporary copy of an Action you played this turn on top of your Library.',
    flavor: 'It rings once more, then never again.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'echo_forge', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'sketch_artist',
    name: 'Sketch Artist',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'recruit',
        zone: 'library',
        filter: { type: 'Action' },
        count: 1,
        to: 'hand',
      },
      {
        op: 'copyCard',
        target: { who: 'self', zone: 'hand', filter: { type: 'Action' }, count: 1, pick: 'lastPlayed' },
        to: 'hand',
        keywords: ['Temporary'],
      },
    ],
    triggers: [],
    text: 'Draw an Action from your Library that grants no +Actions, and add a Temporary copy of it to your hand.',
    flavor: 'A likeness, good enough for one use.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'sketch_artist', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'shadiris_visions',
    name: 'Shadiris Visions',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Shadiris'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'deck', who: 'self' },
        count: 3,
        pick: 1,
        prompt: 'A vision of your deck',
        then: [
          { op: 'copyCard', target: { self: true }, to: 'hand', keywords: ['Temporary'] },
        ],
      },
    ],
    triggers: [],
    text: 'Discover a card in your deck and add a Temporary copy of it to your hand. +1 Action.',
    flavor: 'It fades by morning.',
    complexity: 'T3',
    subsystems: ['S-DISCOVER'],
    shop: 'draft',
    art: { key: 'shadiris_visions', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'shadiris_manifestation',
    name: 'Shadiris Manifestation',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Shadiris'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'deck', who: 'self' },
        count: 3,
        pick: 1,
        prompt: 'Manifest from your deck',
        then: [{ op: 'copyCard', target: { self: true }, to: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Discover a card in your deck and add a copy of it to your hand. +1 Action.',
    flavor: 'The vision, but it stays.',
    complexity: 'T3',
    subsystems: ['S-DISCOVER'],
    shop: 'draft',
    art: { key: 'shadiris_manifestation', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'duplication',
    name: 'Duplication',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'copyCard',
        target: { who: 'self', zone: 'hand', count: 2, pick: 'random' },
        to: 'hand',
      },
    ],
    triggers: [],
    text: 'Add copies of two random cards in your hand to your hand.',
    flavor: 'Ctrl-C, Ctrl-V, Ctrl-V.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'duplication', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'model_citizen',
    name: 'Model Citizen',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'discover',
        pool: { scope: 'deck', who: 'self' },
        count: 3,
        pick: 1,
        prompt: 'Choose the model',
        then: [
          {
            op: 'transform',
            target: { who: 'self', zone: ['library', 'hand', 'gy'], count: 2, pick: 'random' },
            into: { pool: { scope: 'deck', who: 'self' } },
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discover 3 cards from your deck. The two you do not pick transform into the one you did.',
    flavor: 'Conformity, delivered.',
    complexity: 'T3',
    subsystems: ['S-DISCOVER'],
    shop: 'draft',
    art: { key: 'model_citizen', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'training_regiment',
    name: 'Training Regiment',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'nextCardModifier',
        mod: { appliesTo: 'play', grantKeyword: 'PlayOnDraw', uses: 1 },
      },
    ],
    triggers: [],
    text: 'The next Action you play this turn gains Play on Draw. +1 Action.',
    flavor: 'Drilled until reflexive.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'training_regiment', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'the_divined_cosmos',
    name: 'The Divined Cosmos',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'selectCards',
        from: { who: 'self', zone: 'hand' },
        min: 0,
        max: { expr: 'handSize' },
        then: [
          {
            op: 'delayed',
            when: 'startOfNextTurn',
            effects: [{ op: 'playCard', target: { self: true } }],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Place any number of cards from your hand in an order. They activate in that order at the start of your next turn.',
    flavor: 'Tomorrow, in sequence.',
    complexity: 'T3',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'the_divined_cosmos', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'counting_cards',
    name: 'Counting Cards',
    cost: { money: 9 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      { op: 'reveal', target: { who: 'self', zone: 'library', count: 5, pick: 'top' } },
      {
        op: 'conditional',
        if: { expr: '21 - sumOfDeckCosts' },
        then: [
          {
            op: 'playCard',
            target: { who: 'self', zone: 'library', count: 5, pick: 'top' },
          },
        ],
        else: [
          {
            op: 'moveTo',
            target: { who: 'self', zone: 'library', count: 5, pick: 'top' },
            zone: 'gy',
          },
        ],
      },
    ],
    triggers: [],
    text: 'Reveal cards from the top of your Library, adding their costs; (1)-cost cards count as 11 or 1. Stop at 17 or more. At 21 or under, play them all; if you bust, discard them all.',
    flavor: 'The house is your own Library.',
    complexity: 'T4',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'counting_cards', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'map_to_the_golden_monkey',
    name: 'Map to the Golden Monkey',
    cost: { money: 8 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'copyCard', target: { who: 'self', zone: 'hand' }, to: 'hand' },
    ],
    triggers: [],
    text: 'Flimsy. Duplicate your hand.',
    flavor: 'X marks everything.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'map_to_the_golden_monkey', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'one_with_nothing',
    name: 'One With Nothing',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'selectCards',
        from: { who: 'self', zone: 'hand' },
        min: 0,
        max: { expr: 'handSize' },
        then: [{ op: 'trash', target: { self: true } }],
      },
    ],
    triggers: [],
    text: 'Trash any number of cards in your hand. +1 Action.',
    flavor: 'Enlightenment, or an empty hand.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'one_with_nothing', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
  {
    id: 'controlled_burn',
    name: 'Controlled Burn',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { cards: 2, actions: 1 },
    effects: [{ op: 'trash', target: { who: 'self', zone: 'gy' } }],
    triggers: [],
    text: 'Trash your GY. +2 Cards, +1 Action.',
    flavor: 'On purpose. Mostly.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'controlled_burn', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
];

export default cards;
