/**
 * A.5 Draft Shop — core economy and money.
 *
 * Includes the seven Series Funding cards: negative money cost (the buyer is
 * paid, B55) and a self-lock on buy so the pile cannot be looped. `lead`
 * follows the same pattern per SB-27: floor (-2), pile locks for the rest of
 * the turn after one purchase.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'feather',
    name: 'Feather',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: ['Flimsy'],
    stats: { actions: 1, buys: 1, cards: 1, money: 1 },
    effects: [],
    triggers: [],
    text: 'Flimsy. +1 Action, +1 Buy, +1 Card, +1 Money.',
    flavor: 'Weightless, and gone.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'feather', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'loose_change',
    name: 'Loose Change',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { money: 1 },
    effects: [
      {
        op: 'conditional',
        if: { all: [{ combo: 2 }, { not: { combo: 3 } }] },
        then: [{ op: 'gain', stat: 'money', amount: 1 }],
      },
    ],
    triggers: [],
    text: '+1 Money. If exactly 1 card was played before this, +1 Money.',
    flavor: 'Couch archaeology.',
    complexity: 'T2',
    subsystems: ['S-COMBO'],
    shop: 'draft',
    art: { key: 'loose_change', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'jay_fungus',
    name: 'Jay Fungus',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { money: 2 },
    effects: [
      { op: 'copyCard', target: { self: true }, to: 'gy' },
      { op: 'shuffle', zone: 'gy' },
    ],
    triggers: [],
    text: 'Shuffle an extra copy of this into your GY. +2 Money.',
    flavor: 'It spreads because it works.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'jay_fungus', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'shuffle' },
  },
  {
    id: 'careful_investment',
    name: 'Careful Investment',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'delayed',
        when: 'startOfNextTurn',
        effects: [{ op: 'gain', stat: 'money', amount: 2 }],
      },
    ],
    triggers: [],
    text: '+2 Money at the start of your next turn.',
    flavor: 'Patience compounds.',
    complexity: 'T2',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'careful_investment', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'reckless_investment',
    name: 'Reckless Investment',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { money: 3 },
    effects: [
      {
        op: 'delayed',
        when: 'startOfNextTurn',
        effects: [{ op: 'gain', stat: 'money', amount: -2 }],
      },
    ],
    triggers: [],
    text: '+3 Money. -2 Money at the start of your next turn.',
    flavor: 'Tomorrow is a different guy’s problem.',
    complexity: 'T2',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'reckless_investment', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'preparation',
    name: 'Preparation',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'delayed',
        when: 'startOfNextTurn',
        effects: [{ op: 'draw', amount: 3 }],
      },
    ],
    triggers: [],
    text: '+3 Cards at the start of your next turn.',
    flavor: 'Laid out the night before.',
    complexity: 'T2',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'preparation', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'kwzki_cycle_2_6',
    name: '2.6 Kwzki Cycle',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1, buys: 1, cards: 1 },
    effects: [],
    triggers: [],
    text: '+1 Action, +1 Buy, +1 Card.',
    flavor: 'Two point six of what, exactly.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'kwzki_cycle_2_6', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'energize',
    name: 'Energize',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 2 },
    effects: [],
    triggers: [],
    text: '+2 Actions.',
    flavor: 'Do more, faster, for no reason.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'energize', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'market',
    name: 'Market',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { buys: 1, cards: 1, money: 1 },
    effects: [],
    triggers: [],
    text: '+1 Buy, +1 Card, +1 Money.',
    flavor: 'Open stalls, closed books.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'market', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1, buys: 1, cards: 1, money: 1 },
    effects: [],
    triggers: [],
    text: '+1 Action, +1 Buy, +1 Card, +1 Money.',
    flavor: 'The Market, but with a permit.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'marketplace', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'loan_shark',
    name: 'Loan Shark',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { money: 5 },
    effects: [
      {
        op: 'delayed',
        when: 'startOfNextTurn',
        effects: [{ op: 'gain', stat: 'money', amount: -10 }],
      },
    ],
    triggers: [],
    text: '+5 Money. -10 Money at the start of your next turn.',
    flavor: 'The rate is friendly. He is not.',
    complexity: 'T2',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'loan_shark', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'la_economia',
    name: 'La Economia',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 2, money: 2 },
    effects: [],
    triggers: [],
    text: '+2 Actions, +2 Money.',
    flavor: 'Es lo que hay.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'la_economia', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'smart_savings',
    name: 'Smart Savings',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, money: 1 },
    effects: [
      {
        op: 'delayed',
        when: 'endOfTurn',
        // `counter` is the one key `selfCounter` reads on its own; under any
        // other name it sums every counter on the instance, the engine's own
        // playCount included. Zeroed again after the payout so a later play
        // carries the new leftover only.
        effects: [
          { op: 'addCounter', target: { self: true }, key: 'counter', amount: { expr: 'moneyUnspent' } },
          {
            op: 'delayed',
            when: 'startOfTurn',
            effects: [
              { op: 'gain', stat: 'money', amount: { expr: 'selfCounter' } },
              { op: 'addCounter', target: { self: true }, key: 'counter', amount: { expr: '0 - selfCounter' } },
            ],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Money you do not spend this turn carries over to your next turn. +1 Action, +1 Money.',
    flavor: 'A rainy day fund, in a game about rain.',
    complexity: 'T2',
    subsystems: ['S-DELAYED', 'S-PERSIST'],
    shop: 'draft',
    art: { key: 'smart_savings', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'big_spenda',
    name: 'Big Spenda',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { buys: 2, cards: 2, money: 2 },
    effects: [],
    triggers: [],
    text: '+2 Buys, +2 Cards, +2 Money.',
    flavor: 'Round numbers only.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'big_spenda', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'giga_buy',
    name: 'Giga Buy',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 4, money: 2 },
    effects: [],
    triggers: [],
    text: '+4 Buys, +2 Money.',
    flavor: 'One click, many regrets.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'giga_buy', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'nine_five_five',
    name: '9-5-5',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 3 },
    effects: [],
    triggers: [],
    text: '+3 Actions.',
    flavor: 'Nine to five, five days.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'nine_five_five', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'nine_nine_six',
    name: '9-9-6',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 4 },
    effects: [],
    triggers: [],
    text: '+4 Actions.',
    flavor: 'Nine to nine, six days.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'nine_nine_six', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'ultimate_infestation',
    name: 'Ultimate Infestation',
    cost: { money: 10 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 5, buys: 5, cards: 5, money: 5 },
    effects: [],
    triggers: [],
    text: '+5 Actions, +5 Buys, +5 Cards, +5 Money.',
    flavor: 'Everything, everywhere, at (10).',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'ultimate_infestation', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'aas_bargain',
    name: "AA's Bargain",
    cost: { money: 3 },
    types: ['Action', 'Points'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, cards: 1, money: 3, vp: -2 },
    effects: [],
    triggers: [],
    text: '+1 Action, +1 Card, +3 Money, -2 VP.',
    flavor: 'He drives a hard one.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'aas_bargain', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'youre_all_fired',
    name: "You're all fired",
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 2, money: 10 },
    effects: [
      { op: 'trash', target: { who: 'self', zone: 'hand' } },
      { op: 'trash', target: { self: true } },
    ],
    triggers: [],
    text: 'Trash your hand and this card. +2 Buys, +10 Money.',
    flavor: 'Severance is a line item.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'youre_all_fired', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
  {
    id: 'day_trader',
    name: 'Day Trader',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { money: 2 },
    effects: [
      {
        op: 'forEach',
        over: { who: 'self', zone: 'gy', filter: { defId: 'silver' } },
        effects: [{ op: 'gain', stat: 'money', amount: 2 }],
      },
    ],
    triggers: [],
    text: '+2 Money, repeated for each Silver in your GY.',
    flavor: 'Up 2%. Down 2%. Up 2%.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'day_trader', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'senior_associate',
    name: 'Senior Associate',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 1 },
    effects: [
      {
        op: 'conditional',
        if: { has: { target: { who: 'self', zone: 'hand', filter: { defId: 'tix' } }, atLeast: 1 } },
        then: [
          { op: 'discard', target: { who: 'self', zone: 'hand', filter: { defId: 'tix' }, count: 1 } },
          { op: 'gain', stat: 'money', amount: 2 },
        ],
        else: [{ op: 'createCard', defId: 'tix', to: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Discard a Tix for +2 Money. If you have none, add a Tix to your hand instead. +1 Buy.',
    flavor: 'Two years in, still doing the deck.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'senior_associate', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'goldman_vp',
    name: 'Goldman VP',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 2 },
    effects: [
      {
        op: 'conditional',
        if: { has: { target: { who: 'self', zone: 'hand', filter: { defId: 'robux' } }, atLeast: 1 } },
        then: [
          { op: 'discard', target: { who: 'self', zone: 'hand', filter: { defId: 'robux' }, count: 1 } },
          { op: 'gain', stat: 'money', amount: 5 },
        ],
        else: [{ op: 'createCard', defId: 'robux', to: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Discard a Robux for +5 Money. If you have none, add a Robux to your hand instead. +2 Buys.',
    flavor: 'Doing God’s work.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'goldman_vp', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'honest_living',
    name: 'Honest Living',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: {
          not: {
            has: {
              target: { who: 'self', zone: 'play', filter: { not: { type: 'Resource' } } },
              atLeast: 2,
            },
          },
        },
        then: [{ op: 'gain', stat: 'money', amount: { expr: 'moneyUnspent' } }],
      },
    ],
    triggers: [],
    text: 'If every card you played before this was a Resource, double your Money.',
    flavor: 'No tricks. Just coins.',
    complexity: 'T3',
    subsystems: ['S-MULTIPLIER'],
    shop: 'draft',
    art: { key: 'honest_living', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'pure_of_heart',
    name: 'Pure of Heart',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 2, cards: 2 },
    effects: [],
    // The (0) price is a live reading of the hand, not a modifier: a
    // start-of-turn snapshot samples the hand at the one moment it is
    // guaranteed to hold five cards. It is priced in `shop/dynamic.ts`, which
    // `costOf` consults at purchase time, so nothing is authored here.
    triggers: [],
    text: 'Costs (0) if your hand is empty. +2 Actions, +2 Cards.',
    flavor: 'Nothing to declare.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'pure_of_heart', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'overpaid_intern',
    name: 'Overpaid Intern',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1, cards: 1 },
    effects: [
      {
        op: 'conditional',
        if: { expr: 'buysRemaining >= 3' },
        then: [
          { op: 'gain', stat: 'buys', amount: 1 },
          { op: 'gain', stat: 'money', amount: 1 },
        ],
      },
    ],
    triggers: [],
    text: '+1 Action, +1 Card. If you have 3 or more Buys, +1 Buy and +1 Money.',
    flavor: 'Equity, apparently.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'overpaid_intern', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'venture_backed',
    name: 'Venture Backed',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { cards: 2, money: 2 },
    effects: [
      {
        op: 'conditional',
        if: { expr: 'cardsGainedThisTurn >= 3' },
        then: [
          { op: 'gain', stat: 'actions', amount: 1 },
          { op: 'gain', stat: 'buys', amount: 1 },
        ],
      },
    ],
    triggers: [],
    text: '+2 Cards, +2 Money. If you gained 3 or more cards this turn, including tokens, +1 Action and +1 Buy.',
    flavor: 'Growth at all costs, and the costs are all growth.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'venture_backed', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'isda_agreement',
    name: 'ISDA Agreement',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: { buys: 5 },
    effects: [],
    triggers: [],
    text: 'Flimsy. +5 Buys.',
    flavor: 'Master agreement, single use.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'isda_agreement', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'express_shipping',
    name: 'Express Shipping',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, money: 1 },
    effects: [{ op: 'nextCardModifier', mod: { buyTo: 'hand', appliesTo: 'buy' } }],
    triggers: [],
    text: '+1 Action, +1 Money. The next card you buy this turn goes to your hand.',
    flavor: 'Arrives before you regret it.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'express_shipping', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'energy_drink',
    name: 'Energy Drink',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 3, cards: 2 },
    effects: [
      {
        op: 'delayed',
        when: 'startOfNextTurn',
        effects: [{ op: 'gain', stat: 'actions', amount: -1 }],
      },
    ],
    triggers: [],
    text: '+3 Actions, +2 Cards. -1 Action at the start of your next turn.',
    flavor: 'The crash is part of the deal.',
    complexity: 'T2',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'energy_drink', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'a_fools_prayer',
    name: "A Fool's Prayer",
    cost: { money: 0 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'random',
        branches: [
          { weight: 10, effects: [{ op: 'gain', stat: 'money', amount: 20 }] },
          { weight: 90, effects: [{ op: 'noop' }] },
        ],
      },
    ],
    triggers: [],
    text: '10% chance of +20 Money.',
    flavor: 'Somebody has to be the tenth.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'a_fools_prayer', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'highroller_type_a',
    name: 'Highroller Type A',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Highroller'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'random',
        branches: [
          { weight: 1, effects: [{ op: 'gain', stat: 'actions', amount: 4 }] },
          { weight: 1, effects: [{ op: 'gain', stat: 'buys', amount: 4 }] },
          { weight: 1, effects: [{ op: 'draw', amount: 4 }] },
          { weight: 1, effects: [{ op: 'gain', stat: 'money', amount: 4 }] },
        ],
      },
    ],
    triggers: [],
    text: 'Randomly gain +4 Actions, +4 Buys, +4 Cards or +4 Money.',
    flavor: 'Type A personality, Type A payout.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'highroller_type_a', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'highroller_type_b',
    name: 'Highroller Type B',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Highroller'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'random',
        branches: [
          { weight: 1, effects: [{ op: 'gain', stat: 'money', amount: 3 }] },
          { weight: 1, effects: [{ op: 'draw', amount: 2 }] },
        ],
      },
    ],
    triggers: [],
    text: 'Flip a coin: +3 Money, or +2 Cards.',
    flavor: 'Heads you eat, tails you read.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'highroller_type_b', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'highroller_type_c',
    name: 'Highroller Type C',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Highroller'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'random',
        branches: [
          { weight: 1, effects: [{ op: 'noop' }] },
          { weight: 1, effects: [{ op: 'gain', stat: 'money', amount: 1 }] },
          { weight: 1, effects: [{ op: 'gain', stat: 'money', amount: 2 }] },
          { weight: 1, effects: [{ op: 'gain', stat: 'money', amount: 3 }] },
          { weight: 1, effects: [{ op: 'gain', stat: 'money', amount: 4 }] },
          { weight: 1, effects: [{ op: 'gain', stat: 'money', amount: 5 }] },
        ],
      },
    ],
    triggers: [],
    text: 'Roll a die. +(roll - 1) Money.',
    flavor: 'Snake eyes pay nothing.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'highroller_type_c', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'highroller_type_x',
    name: 'Highroller Type X',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Highroller'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'random',
        branches: [
          { weight: 1, effects: [{ op: 'gain', stat: 'money', amount: 8 }] },
          {
            weight: 1,
            effects: [
              {
                op: 'trash',
                target: { who: 'self', zone: ['library', 'hand', 'gy'], count: 4, pick: 'random' },
              },
              { op: 'trash', target: { self: true } },
            ],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Flip a coin: +8 Money, or trash 4 random cards from your deck and then trash this.',
    flavor: 'X marks the crater.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'highroller_type_x', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'explode' },
  },
  {
    id: 'the_biggest_the_largest',
    name: 'The Biggest, The Largest',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { cards: 1 },
    effects: [
      // `largestOpponentDeck` is the biggest opponent deck, so the subtraction
      // is simultaneously the gate ("if you have the largest deck") and the
      // payout ("X = size lead"). It used to read `madOfOpponentDeck`, a cost
      // dispersion, which paid ~9 Money off a (1) card on turn one.
      { op: 'gain', stat: 'money', amount: { expr: 'max(0, deckSize - largestOpponentDeck)' } },
      { op: 'trash', target: { who: 'self', zone: 'gy' } },
    ],
    triggers: [],
    text: 'If you have the largest deck, +X Money where X is your size lead. Then trash your GY. +1 Card.',
    flavor: 'Nobody has ever had a bigger one.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'the_biggest_the_largest', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
  {
    id: 'diversity_hater',
    name: 'Diversity Hater',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'gain', stat: 'money', amount: { expr: 'max(0, uniqueCardsInDeck - 8)' } },
    ],
    triggers: [],
    text: '+X Money, X = the number of distinct cards in your deck minus 8.',
    flavor: 'He hates it, but he counts it.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'diversity_hater', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'hr_trainee',
    name: 'HR Trainee',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'gain', stat: 'money', amount: { expr: 'floor(uniqueCardsInDeck / 3)' } },
      {
        op: 'conditional',
        if: { expr: 'floor(uniqueCardsInDeck / 3) >= 3' },
        then: [{ op: 'draw', amount: 1 }],
      },
    ],
    triggers: [],
    text: '+X Money, X = floor(distinct cards in your deck / 3). If X is 3 or more, Cycle.',
    flavor: 'Onboarding is ongoing.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'hr_trainee', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'rebate',
    name: 'Rebate',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 1 },
    effects: [],
    triggers: [
      {
        // `zones:['play']` is what makes this a rider: `firePlayTriggers` sweeps
        // the buyer's play area on every purchase, so a Rebate already played
        // watches the buys that follow it.
        on: 'onBuy',
        zones: ['play'],
        maxPerTurn: 1,
        effects: [
          {
            // The trigger's own source is the Rebate, so `selfCost` there is
            // Rebate's (3) — a flat 2 refund for a (10) buy and a (0) buy
            // alike. `forEach` rebinds the source to the card it selected, and
            // the card just bought is the newest entry in the buyer's GY
            // (`buyCard` moves it there before it fires onBuy), so the body
            // reads the bought card's cost instead.
            //
            // `max(0, ...)` is load-bearing: costs are signed and the Series
            // Funding pile runs (-1)…(-7), where a bare `ceil(selfCost * 0.6)`
            // is negative and `opGain` does not clamp Money — a refund would
            // CHARGE the buyer. A refund of a negative price is 0.
            op: 'forEach',
            over: { who: 'self', zone: 'gy', count: 1, pick: 'bottom' },
            effects: [{ op: 'gain', stat: 'money', amount: { expr: 'max(0, ceil(selfCost * 0.6))' } }],
          },
        ],
      },
    ],
    text: '+1 Buy. Your first purchase this turn refunds 60% of its cost, rounded up.',
    flavor: 'Mail-in. Six to eight turns.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'rebate', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'biblical_greed',
    name: 'Biblical Greed',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      // Bank the loss on the card before draining the wallet: the payout
      // resolves five turns later with a fresh var set, so the Money lost has
      // to be read back off the source instance. `counter` is the reserved key
      // `selfCounter` reads on its own, and counters survive the Flimsy trash.
      { op: 'addCounter', target: { self: true }, key: 'counter', amount: { expr: 'moneyUnspent' } },
      {
        op: 'delayed',
        when: { inTurns: 5 },
        effects: [
          { op: 'gain', stat: 'money', amount: { expr: 'selfCounter * 4 + 5' } },
          { op: 'gain', stat: 'buys', amount: 3 },
        ],
      },
      { op: 'gain', stat: 'money', amount: { expr: '0 - moneyUnspent' } },
    ],
    triggers: [],
    text: 'Flimsy. Lose all your Money. In 5 turns, +X Money and +3 Buys, where X is four times the Money lost plus 5.',
    flavor: 'Seven lean turns, then the fat one.',
    complexity: 'T3',
    subsystems: ['S-DELAYED'],
    shop: 'draft',
    art: { key: 'biblical_greed', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'professor_of_curvature',
    name: 'Professor of Curvature',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    // Paid back rather than never charged. `scope:'nextBuy'` drops `setTo`
    // entirely (opModifyCost pushes a bare `{costDelta, costFloor}`), so the
    // old node discounted nothing AND clamped a negative-cost buy up to (0),
    // eating the credit from a Series Funding. A `delta` of −X instead would
    // discount whatever you bought next, not the (X)-cost card the row names,
    // because a NextCardMod carries no cost filter. The refund below is the
    // one shape that stays gated to the printed price: net money is identical
    // to free, at the cost of having to afford the card for one instant.
    //
    // The refund is the PRINTED cost. `instanceCost` consults `costOf` only for
    // an instance still sitting in a pile, and `buyCard` has already moved the
    // bought card to the GY, so nothing on the card side can see the price a
    // cost modifier actually charged. That is why the text below says "refunds"
    // and not "is free": with a discount live on the pile the two are different
    // numbers, and the card would otherwise promise something it cannot pay.
    //
    // `curvatureUsed` is a per-PURCHASE mark. A player counter is shared by
    // every copy, and `firePlayTriggers` resolves each Professor in play in
    // sequence, so on one qualifying buy two Professors both saw a charge, both
    // paid, and a single purchase ate both. `buysUsedThisTurn` is incremented
    // inside `buyCard` before any trigger fires and the refund bumps
    // `curvatureUsed` to match, so `buysUsedThisTurn > curvatureUsed` holds
    // exactly once per purchase however many copies are watching. The 0-amount
    // seed in front creates the key: the expression grammar throws on an
    // identifier that is in neither EXPR_VARS nor the player's counters, and
    // `evalCondition` swallows that throw as `false`.
    effects: [
      { op: 'addCounter', scope: 'player', key: 'turn:curvatureFree', amount: 1 },
      { op: 'addCounter', scope: 'player', key: 'turn:curvatureUsed', amount: 0 },
    ],
    triggers: [
      {
        // A rider: `firePlayTriggers` sweeps the buyer's play area on each
        // purchase. The counter is written by the body above, so an unplayed
        // Professor leaves the name undefined and the condition reads false.
        on: 'onBuy',
        zones: ['play'],
        condition: {
          all: [{ expr: 'curvatureFree >= 1' }, { expr: 'buysUsedThisTurn > curvatureUsed' }],
        },
        effects: [
          {
            // The card just bought is the newest entry in the GY; `forEach`
            // rebinds the source to it so `selfCost` is ITS price and not the
            // Professor's (1). Filtering the selector instead would match an
            // older (X)-cost card still sitting in the GY.
            op: 'forEach',
            over: { who: 'self', zone: 'gy', count: 1, pick: 'bottom' },
            effects: [
              {
                op: 'conditional',
                if: { expr: 'selfCost == currentTurn' },
                then: [
                  { op: 'gain', stat: 'money', amount: { expr: 'selfCost' } },
                  { op: 'addCounter', scope: 'player', key: 'turn:curvatureFree', amount: -1 },
                  { op: 'addCounter', scope: 'player', key: 'turn:curvatureUsed', amount: 1 },
                ],
              },
            ],
          },
        ],
      },
    ],
    text: 'On turn X, the next card you buy with a printed cost of exactly (X) refunds that cost.',
    flavor: 'The curve bends toward the bursar.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'professor_of_curvature', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'lead',
    name: 'Lead',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    // The reroll is a price, not a modifier: no dispatcher fires triggers on a
    // card sitting in a shop pile, so the `{on:'startOfTurn', zones:['shop']}`
    // node that used to sit here was dead on arrival. `shop/dynamic.ts` derives
    // the (−2)…(10) price from (seed, turn) at cost time instead, which rerolls
    // every turn and still replays exactly.
    //
    // The payout is the price PAID, and a Lead in hand cannot read it:
    // `selfCost` off a non-shop instance is the printed (4), the midpoint of
    // the range, so a bare `{expr:'selfCost'}` here paid a flat 4 whatever the
    // reroll charged. Nothing in the frozen var list carries the price a
    // purchase charged either, so the price is banked onto the card at the
    // moment of purchase instead — the Biblical Greed pattern: `counter` is the
    // reserved key `selfCounter` reads on its own, and counters survive every
    // zone move, so the payout below is the number THIS copy was bought for.
    effects: [{ op: 'gain', stat: 'money', amount: { expr: 'selfCounter' } }],
    triggers: [
      {
        // SB-27, and live: buy.ts fires onBuy on the bought instance itself.
        on: 'onBuy',
        effects: [
          {
            op: 'lockPile',
            target: { shop: 'draft', filter: { defId: 'lead' } },
            duration: 'turn',
          },
          {
            // `buyCard` has already moved this copy to the GY, where its cost
            // reads as the printed (4), so the turn's reroll has to come off a
            // Lead still in the pile: `forEach` rebinds the source to it and
            // `selfCost` there is `costOf` — the price this buy was charged.
            // The bought copy is the newest GY entry (`buyCard` appends it) and
            // the pile self-locks above, so no second Lead can land behind it
            // this turn. The `has` guard is load-bearing: `addCounter` falls
            // back to its OWN source when the target selector is empty, which
            // would bank the price onto the shop copy instead.
            op: 'forEach',
            over: { zone: 'shop', filter: { defId: 'lead' }, count: 1 },
            effects: [
              {
                op: 'conditional',
                if: {
                  has: {
                    target: { who: 'self', zone: 'gy', filter: { defId: 'lead' }, count: 1, pick: 'bottom' },
                  },
                },
                then: [
                  {
                    op: 'addCounter',
                    target: { who: 'self', zone: 'gy', filter: { defId: 'lead' }, count: 1, pick: 'bottom' },
                    key: 'counter',
                    amount: { expr: 'selfCost' },
                  },
                ],
              },
            ],
          },
          {
            // Bought the last copy in the pile: there is nothing left to price
            // off, so fall back to the printed (4) rather than banking nothing
            // and paying 0 later. This node sits outside the forEach, so `self`
            // is still the card just bought.
            op: 'conditional',
            if: { not: { has: { target: { zone: 'shop', filter: { defId: 'lead' }, count: 1 } } } },
            then: [
              { op: 'addCounter', target: { self: true }, key: 'counter', amount: { expr: 'selfCost' } },
            ],
          },
        ],
      },
    ],
    text: 'This costs between (-2) and (10), rerolled at the start of each turn. +Money equal to the price you paid. Buying this locks its pile for the rest of the turn.',
    flavor: 'Heavy, cheap, and briefly worth something.',
    complexity: 'T4',
    subsystems: ['S-COSTMOD', 'S-LOCK'],
    shop: 'draft',
    art: { key: 'lead', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'accel_giant',
    name: 'Accel Giant',
    cost: { money: 11 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 2, buys: 2, cards: 2 },
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'modifyCost',
            scope: 'pile',
            target: { shop: 'draft', filter: { defId: 'accel_giant' } },
            delta: -2,
            floor: 0,
            duration: 'permanent',
          },
        ],
      },
    ],
    text: 'On buy, every other card in this pile costs (2) less. +2 Actions, +2 Buys, +2 Cards.',
    flavor: 'The first one is always the most expensive.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'accel_giant', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'giants_aid',
    name: "Giant's Aid",
    cost: { money: 11 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 2, buys: 2, cards: 2 },
    effects: [],
    // A running discount, so it is a price rather than a modifier: `onPlay`
    // reaches only the card being played, never a card in a pile, and one
    // firing would have subtracted (1) once instead of once per card. Priced in
    // `shop/dynamic.ts` as `max(0, 11 - cards played this turn)`.
    triggers: [],
    text: 'Costs (1) less per card played this turn. +2 Actions, +2 Buys, +2 Cards.',
    flavor: 'He helps those who have already helped themselves.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'giants_aid', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'jlarna',
    name: 'Jlarna',
    cost: { money: 8 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'legendary',
    keywords: ['Flimsy'],
    stats: { money: 20, buys: 5, actions: 1 },
    effects: [
      {
        op: 'delayed',
        when: 'endOfTurn',
        effects: [{ op: 'manifestAura', tier: 'celestial', auraId: 'outstanding_debt' }],
      },
    ],
    triggers: [],
    text: 'Flimsy. +20 Money, +5 Buys, +1 Action. At end of turn, manifest the Celestial Aura Outstanding Debt: -X Money for 4 turns.',
    flavor: 'Pay in four easy instalments of regret.',
    complexity: 'T4',
    subsystems: ['S-AURA', 'S-DELAYED'],
    shop: 'draft',
    art: { key: 'jlarna', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },

  // --- Series Funding: negative cost, self-locking pile ---------------------
  {
    id: 'series_a_funding',
    name: 'Series A Funding',
    cost: { money: -1 },
    types: ['Points'],
    subtypes: ['Funding'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'lockPile',
            target: { shop: 'draft', filter: { defId: 'series_a_funding' } },
            duration: 'untilYourNextTurn',
          },
        ],
      },
    ],
    text: 'Costs (-1): buying this pays you (1). On buy, Lock this pile until your next turn.',
    flavor: 'Friends and family round.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD', 'S-LOCK'],
    shop: 'draft',
    art: { key: 'series_a_funding', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'series_b_funding',
    name: 'Series B Funding',
    cost: { money: -2 },
    types: ['Points'],
    subtypes: ['Funding'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { vp: -1 },
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'lockPile',
            target: { shop: 'draft', filter: { defId: 'series_b_funding' } },
            duration: 'untilYourNextTurn',
          },
        ],
      },
    ],
    text: 'Costs (-2). On buy, Lock this pile until your next turn. -1 VP.',
    flavor: 'The deck was good. The numbers were not.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD', 'S-LOCK'],
    shop: 'draft',
    art: { key: 'series_b_funding', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'series_c_funding',
    name: 'Series C Funding',
    cost: { money: -3 },
    types: ['Points'],
    subtypes: ['Funding'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { vp: -3 },
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'lockPile',
            target: { shop: 'draft', filter: { defId: 'series_c_funding' } },
            duration: 'untilYourNextTurn',
          },
        ],
      },
    ],
    text: 'Costs (-3). On buy, Lock this pile until your next turn. -3 VP.',
    flavor: 'Growth stage. Growth of what is unclear.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD', 'S-LOCK'],
    shop: 'draft',
    art: { key: 'series_c_funding', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'series_d_funding',
    name: 'Series D Funding',
    cost: { money: -4 },
    types: ['Points'],
    subtypes: ['Funding'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { vp: -5 },
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'lockPile',
            target: { shop: 'draft', filter: { defId: 'series_d_funding' } },
            duration: 'untilYourNextTurn',
          },
        ],
      },
    ],
    text: 'Costs (-4). On buy, Lock this pile until your next turn. -5 VP.',
    flavor: 'Down round, up spirits.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD', 'S-LOCK'],
    shop: 'draft',
    art: { key: 'series_d_funding', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'series_e_funding',
    name: 'Series E Funding',
    cost: { money: -5 },
    types: ['Points'],
    subtypes: ['Funding'],
    tags: [],
    rarity: 'epic',
    keywords: ['Indestructible'],
    stats: { vp: -8 },
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'lockPile',
            target: { shop: 'draft', filter: { defId: 'series_e_funding' } },
            duration: 'untilYourNextTurn',
          },
        ],
      },
    ],
    text: 'Indestructible. Costs (-5). On buy, Lock this pile until your next turn. -8 VP.',
    flavor: 'It cannot be trashed. It cannot be escaped.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD', 'S-LOCK'],
    shop: 'draft',
    art: { key: 'series_e_funding', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'series_f_funding',
    name: 'Series F Funding',
    cost: { money: -6 },
    types: ['Points'],
    subtypes: ['Funding'],
    tags: [],
    rarity: 'epic',
    keywords: ['Indestructible'],
    stats: { vp: -12 },
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'lockPile',
            target: { shop: 'draft', filter: { defId: 'series_f_funding' } },
            duration: 'untilYourNextTurn',
          },
        ],
      },
    ],
    text: 'Indestructible. Costs (-6). On buy, Lock this pile until your next turn. -12 VP.',
    flavor: 'F is for the letter after E.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD', 'S-LOCK'],
    shop: 'draft',
    art: { key: 'series_f_funding', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'series_x_funding',
    name: 'Series X Funding',
    cost: { money: -7 },
    types: ['Points'],
    subtypes: ['Funding'],
    tags: [],
    rarity: 'epic',
    keywords: ['Indestructible'],
    stats: { vp: -18 },
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          {
            op: 'lockPile',
            target: { shop: 'draft', filter: { defId: 'series_x_funding' } },
            duration: 'untilYourNextTurn',
          },
        ],
      },
    ],
    text: 'Indestructible. Costs (-7). On buy, Lock this pile until your next turn. -18 VP.',
    flavor: 'They stopped counting and started praying.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD', 'S-LOCK'],
    shop: 'draft',
    art: { key: 'series_x_funding', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
];

export default cards;
