/**
 * A.4 Draft Shop — Prophet generation. The 12 cards that bank Prophet.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'novice_acolyte',
    name: 'Novice Acolyte',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: ['Legacy'],
    rarity: 'common',
    keywords: ['Flimsy'],
    stats: { prophet: 1 },
    effects: [],
    triggers: [],
    text: 'Flimsy. +1 Prophet.',
    flavor: 'Still learning which way to kneel.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'novice_acolyte', status: 'placeholder' },
  },
  {
    id: 'prophet_injection',
    name: 'Prophet Injection',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: ['PlayOnBuy', 'Flimsy'],
    stats: { prophet: 1 },
    effects: [],
    triggers: [],
    text: 'Play on Buy, Flimsy. +1 Prophet.',
    flavor: 'Faith, intravenously.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'prophet_injection', status: 'placeholder' },
  },
  {
    id: 'perish_priest',
    name: 'Perish Priest',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { prophet: 1 },
    effects: [],
    triggers: [],
    text: '+1 Prophet.',
    flavor: 'Preaches the ending, not the beginning.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'perish_priest', status: 'placeholder' },
  },
  {
    id: 'lection',
    name: 'Lection',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: { prophet: 1 },
    effects: [{ op: 'addCounter', target: { self: true }, key: 'playCount', amount: 1 }],
    triggers: [
      {
        on: 'onPlay',
        condition: { expr: 'selfPlayCount - 4' },
        effects: [
          { op: 'gain', stat: 'actions', amount: 1 },
          {
            op: 'createCard',
            defId: { pool: { catalog: 'scripture', scope: 'entireUniverse' } },
            to: 'hand',
          },
        ],
      },
    ],
    text: 'Flimsy. +1 Prophet. On the 5th play, +1 Action and add a random Scripture to your hand. ({playsLeft} left!)',
    flavor: 'Read it again. And again.',
    complexity: 'T4',
    subsystems: ['S-PERSIST', 'S-PROPHET', 'S-TEXTGEN'],
    shop: 'draft',
    art: { key: 'lection', status: 'placeholder' },
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    cost: { money: 4 },
    types: ['Action', 'Food'],
    subtypes: ['Fruit'],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: { prophet: 2 },
    effects: [],
    triggers: [],
    text: 'Flimsy. +2 Prophet.',
    flavor: 'Six seeds and a season underground.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'pomegranate', status: 'placeholder' },
  },
  {
    id: 'mythmaker',
    name: 'Mythmaker',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { prophet: 2 },
    effects: [],
    triggers: [],
    text: '+2 Prophet.',
    flavor: 'Nobody checks the sources.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'mythmaker', status: 'placeholder' },
  },
  {
    id: 'new_canon',
    name: 'New Canon',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'forEach',
        over: {
          who: 'self',
          zone: 'hand',
          filter: { subtype: ['Prophet', 'Book', 'Relic'] },
        },
        effects: [
          { op: 'gain', stat: 'prophet', amount: 1 },
          { op: 'draw', amount: 1 },
        ],
      },
      {
        op: 'trash',
        target: {
          who: 'self',
          zone: 'hand',
          filter: { subtype: ['Prophet', 'Book', 'Relic'] },
        },
      },
    ],
    triggers: [],
    text: 'Trash all Prophet, Book and Relic cards in your hand. +1 Prophet and +1 Card for each.',
    flavor: 'Revision is an act of worship.',
    complexity: 'T2',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'new_canon', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'meditation',
    name: 'Meditation',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { all: [{ combo: 1 }, { not: { combo: 2 } }] },
        then: [{ op: 'draw', amount: 2 }],
        else: [{ op: 'gain', stat: 'prophet', amount: 2 }],
      },
    ],
    triggers: [],
    text: '+2 Prophet. Combo 1: +2 Cards instead.',
    flavor: 'Breathe in. Bank it.',
    complexity: 'T3',
    subsystems: ['S-COMBO', 'S-PROPHET'],
    shop: 'draft',
    art: { key: 'meditation', status: 'placeholder' },
  },
  {
    id: 'sleep_preacher',
    name: 'Sleep Preacher',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { prophet: 1 },
    effects: [],
    triggers: [
      {
        on: 'onDiscard',
        effects: [{ op: 'gain', stat: 'prophet', amount: 1 }],
      },
    ],
    text: 'On play or discard, +1 Prophet.',
    flavor: 'The sermon continues regardless.',
    complexity: 'T2',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'sleep_preacher', status: 'placeholder' },
  },
  {
    id: 'money_church',
    name: 'Money Church',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'gain', stat: 'prophet', amount: { expr: 'min(moneyUnspent, 5)' } },
      { op: 'gain', stat: 'money', amount: { expr: '0 - moneyUnspent' } },
    ],
    triggers: [],
    text: 'Spend all your Money. +X Prophet, X = Money lost, up to 5.',
    flavor: 'Tithe: one hundred percent.',
    complexity: 'T2',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'money_church', status: 'placeholder', anim: 'coin' },
  },
  {
    id: 'temple_marketplace',
    name: 'Temple Marketplace',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, buys: 1, cards: 1, money: 1, prophet: 1 },
    effects: [],
    triggers: [],
    text: '+1 Action, +1 Buy, +1 Card, +1 Money, +1 Prophet.',
    flavor: 'Who would crash out over this?',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'temple_marketplace', status: 'placeholder' },
  },
  {
    id: 'feel_so_clean_like_a_prophet_machine',
    name: 'Feel so Clean Like a Prophet Machine',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'forEach',
        over: { who: 'self', zone: 'hand', filter: { cost: { eq: 1 } }, count: 2 },
        effects: [{ op: 'gain', stat: 'actions', amount: 1 }],
      },
      { op: 'discard', target: { who: 'self', zone: 'hand', count: 2, pick: 'choose' } },
      {
        op: 'conditional',
        if: { not: { has: { target: { who: 'self', zone: 'hand' }, atLeast: 1 } } },
        then: [{ op: 'gain', stat: 'prophet', amount: 2 }],
      },
    ],
    triggers: [],
    text: 'Discard the cards adjacent to this in your hand. +1 Action for each (1)-cost card discarded. If your hand is then empty, +2 Prophet.',
    flavor: 'Rinse cycle for the soul.',
    complexity: 'T3',
    subsystems: ['S-PROPHET', 'S-CORE'],
    shop: 'draft',
    art: { key: 'feel_so_clean_like_a_prophet_machine', status: 'placeholder' },
  },
];

export default cards;
