/**
 * A.4 Draft Shop — Prophet generation. The 12 cards that bank Prophet.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'novice_acolyte',
    name: 'Novice Acolyte',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: ['Legacy'],
    rarity: 'common',
    keywords: ['Flimsy'],
    stats: { prophet: 1 },
    effects: [],
    triggers: [],
    text: 'Flimsy. +1 Prophet.',
    flavor: 'Still learning which way to kneel.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'novice_acolyte', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'prophet_injection',
    name: 'Prophet Injection',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: ['PlayOnBuy', 'Flimsy'],
    stats: { prophet: 1 },
    effects: [],
    triggers: [],
    text: 'Play on Buy, Flimsy. +1 Prophet.',
    flavor: 'Faith, intravenously.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'prophet_injection', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'perish_priest',
    name: 'Perish Priest',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { prophet: 1 },
    effects: [],
    triggers: [],
    text: '+1 Prophet.',
    flavor: 'Preaches the ending, not the beginning.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'perish_priest', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'lection',
    name: 'Lection',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: { prophet: 1 },
    // The addCounter that stood here wrote a second increment onto the same
    // 'playCount' key playCard already maintains, so the instance counter ran
    // at 2x. Nothing reads it — the trigger gates on the per-player,
    // per-definition selfPlayCount — so it is gone.
    effects: [],
    triggers: [
      {
        // An `expr` condition is true for any NON-ZERO value, so
        // 'selfPlayCount - 4' fired on plays 1, 2, 3, 5, 6, ... and was false
        // only on the 4th. The row wants the 5th play and no other.
        on: 'onPlay',
        condition: { expr: 'selfPlayCount == 5' },
        effects: [
          { op: 'gain', stat: 'actions', amount: 1 },
          {
            op: 'createCard',
            defId: { pool: { catalog: 'scripture', scope: 'entireUniverse' } },
            to: 'hand',
          },
        ],
      },
    ],
    // {playsLeft} was never written by anything and always rendered '0'.
    // {selfPlayCount} is not a counter key either, so renderCardText falls
    // through to the per-player play count the trigger actually gates on.
    text: 'Flimsy. +1 Prophet. On the 5th play, +1 Action and add a random Scripture to your hand. (Played {selfPlayCount} of 5.)',
    flavor: 'Read it again. And again.',
    complexity: 'T4',
    subsystems: ['S-PERSIST', 'S-PROPHET', 'S-TEXTGEN'],
    shop: 'draft',
    art: { key: 'lection', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    cost: { money: 4 },
    types: ['Action', 'Food'],
    subtypes: ['Fruit'],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: { prophet: 2 },
    effects: [],
    triggers: [],
    text: 'Flimsy. +2 Prophet.',
    flavor: 'Six seeds and a season underground.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'pomegranate', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'mythmaker',
    name: 'Mythmaker',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { prophet: 2 },
    effects: [],
    triggers: [],
    text: '+2 Prophet.',
    flavor: 'Nobody checks the sources.',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'mythmaker', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'new_canon',
    name: 'New Canon',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    // forEach snapshots its targets, but a sibling trash node re-resolves
    // against the live hand — so the K cards drawn by the payout were trashed
    // too, without ever being paid for. Trashing inside the loop, where forEach
    // has bound the iterated card as the source, fixes both halves to one set.
    effects: [
      {
        op: 'forEach',
        over: {
          who: 'self',
          zone: 'hand',
          filter: { subtype: ['Prophet', 'Book', 'Relic'] },
        },
        effects: [
          { op: 'trash', target: { self: true } },
          { op: 'gain', stat: 'prophet', amount: 1 },
          { op: 'draw', amount: 1 },
        ],
      },
    ],
    triggers: [],
    text: 'Trash all Prophet, Book and Relic cards in your hand. +1 Prophet and +1 Card for each.',
    flavor: 'Revision is an act of worship.',
    complexity: 'T2',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'new_canon', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
  {
    id: 'meditation',
    name: 'Meditation',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { all: [{ combo: 1 }, { not: { combo: 2 } }] },
        then: [{ op: 'draw', amount: 2 }],
        else: [{ op: 'gain', stat: 'prophet', amount: 2 }],
      },
    ],
    triggers: [],
    text: '+2 Prophet. Combo 1: +2 Cards instead.',
    flavor: 'Breathe in. Bank it.',
    complexity: 'T3',
    subsystems: ['S-COMBO', 'S-PROPHET'],
    shop: 'draft',
    art: { key: 'meditation', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'sleep_preacher',
    name: 'Sleep Preacher',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { prophet: 1 },
    effects: [],
    triggers: [
      {
        on: 'onDiscard',
        effects: [{ op: 'gain', stat: 'prophet', amount: 1 }],
      },
    ],
    text: 'On play or discard, +1 Prophet.',
    flavor: 'The sermon continues regardless.',
    complexity: 'T2',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'sleep_preacher', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'money_church',
    name: 'Money Church',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    // Money has no floor (SB-38) and negative Money is reachable (Loan Shark,
    // Outstanding Debt). Unclamped, min(moneyUnspent, 5) went negative and the
    // prophet clamp — which applies to the TOTAL, not the delta — burned banked
    // Prophet, while 0 - moneyUnspent credited the debt back. Both halves clamp
    // at zero so a player in debt simply gains nothing.
    effects: [
      { op: 'gain', stat: 'prophet', amount: { expr: 'max(0, min(moneyUnspent, 5))' } },
      { op: 'gain', stat: 'money', amount: { expr: '0 - max(0, moneyUnspent)' } },
    ],
    triggers: [],
    text: 'Spend all your Money. +X Prophet, X = Money lost, up to 5.',
    flavor: 'Tithe: one hundred percent.',
    complexity: 'T2',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'money_church', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'temple_marketplace',
    name: 'Temple Marketplace',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, buys: 1, cards: 1, money: 1, prophet: 1 },
    effects: [],
    triggers: [],
    text: '+1 Action, +1 Buy, +1 Card, +1 Money, +1 Prophet.',
    flavor: 'Who would crash out over this?',
    complexity: 'T1',
    subsystems: ['S-PROPHET'],
    shop: 'draft',
    art: { key: 'temple_marketplace', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'feel_so_clean_like_a_prophet_machine',
    name: 'Feel so Clean Like a Prophet Machine',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    // The bonus used to be a separate forEach over the (1)-cost cards sitting in
    // hand BEFORE the discard, so a player was paid for cards they then chose
    // not to discard. selectCards runs its `then` once per selection with the
    // picked card bound as the source, so selfCost is the discarded card's cost
    // and the two sets cannot drift apart. (A { has: { target: { self: true,
    // filter: ... } } } condition would not work here: selectInstancesWith
    // returns on sel.self before any filter is applied.)
    effects: [
      {
        op: 'selectCards',
        from: { who: 'self', zone: 'hand' },
        min: 2,
        max: 2,
        then: [
          {
            op: 'conditional',
            if: { expr: 'selfCost == 1' },
            then: [{ op: 'gain', stat: 'actions', amount: 1 }],
          },
          { op: 'discard', target: { self: true } },
        ],
      },
      {
        op: 'conditional',
        if: { not: { has: { target: { who: 'self', zone: 'hand' }, atLeast: 1 } } },
        then: [{ op: 'gain', stat: 'prophet', amount: 2 }],
      },
    ],
    triggers: [],
    text: 'Discard the cards adjacent to this in your hand. +1 Action for each (1)-cost card discarded. If your hand is then empty, +2 Prophet.',
    flavor: 'Rinse cycle for the soul.',
    complexity: 'T3',
    subsystems: ['S-PROPHET', 'S-CORE'],
    shop: 'draft',
    art: { key: 'feel_so_clean_like_a_prophet_machine', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
];

export default cards;
