/**
 * A.6 Draft Shop — Resource manipulation and refining.
 *
 * SB-6: the (5) Resource is `blood_diamond` / "Blood Diamond"; the (10) Action
 * is `blood_diamond_cutter` / "Blood Diamond Cutter". Two ids, two names.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'fools_gold',
    name: "Fool's Gold",
    cost: { money: 0 },
    types: ['Resource'],
    subtypes: ['Gold'],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: { money: 3 },
    effects: [],
    triggers: [],
    text: 'Flimsy. +3 Money.',
    flavor: 'It glitters exactly once.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'fools_gold', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'gleamstone',
    name: 'Gleamstone',
    cost: { money: 8 },
    types: ['Resource'],
    subtypes: ['Diamond'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { money: 4, buys: 1 },
    effects: [],
    triggers: [],
    text: '+4 Money, +1 Buy.',
    flavor: 'Cut for spending, not for wearing.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'gleamstone', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'blood_diamond',
    name: 'Blood Diamond',
    cost: { money: 5 },
    types: ['Resource'],
    subtypes: ['Diamond'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { money: 5, vp: -5 },
    effects: [],
    triggers: [],
    text: '+5 Money, -5 VP.',
    flavor: 'Somebody paid for this. Not you.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'blood_diamond', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'blood_diamond_cutter',
    name: 'Blood Diamond Cutter',
    cost: { money: 10 },
    types: ['Action'],
    subtypes: ['Diamond'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1, money: 5 },
    effects: [],
    triggers: [
      {
        on: 'startOfTurn',
        zones: ['shop'],
        effects: [
          {
            op: 'forEach',
            over: { who: 'self', zone: 'hand', filter: { type: 'Action', cost: { lte: 1 } } },
            effects: [
              {
                op: 'modifyCost',
                scope: 'pile',
                target: { shop: 'draft', filter: { defId: 'blood_diamond_cutter' } },
                delta: -2,
                floor: 0,
                duration: 'turn',
              },
            ],
          },
        ],
      },
      {
        on: 'onBuy',
        effects: [
          {
            op: 'trash',
            target: { who: 'self', zone: 'hand', filter: { type: 'Action', cost: { lte: 1 } } },
          },
        ],
      },
    ],
    text: 'Trash Actions costing (1) or less from your hand to reduce this card’s cost by (2) each. +1 Action, +5 Money.',
    flavor: 'A steady hand and a cheap conscience.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'blood_diamond_cutter', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
  {
    id: 'magnet',
    name: 'Magnet',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'gainCard',
        from: { shop: 'resource', filter: { defId: 'copper' } },
        to: 'hand',
        count: 3,
        free: true,
      },
    ],
    triggers: [],
    text: 'Add up to 3 Copper from the Resource Shop to your hand. +1 Action.',
    flavor: 'Attracts only the cheap stuff.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'magnet', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'simple_refining',
    name: 'Simple Refining',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: 'hand', filter: { defId: 'copper' }, count: 1, pick: 'choose' },
        into: 'upgrade',
      },
    ],
    triggers: [],
    text: 'Trash a Copper in your hand and add a Silver to your hand.',
    flavor: 'Heat, pressure, paperwork.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'simple_refining', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'advanced_refining',
    name: 'Advanced Refining',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: 'hand', filter: { type: 'Resource' }, count: 1, pick: 'choose' },
        into: 'upgrade',
      },
    ],
    triggers: [],
    text: 'Trash a Resource in your hand and add its upgrade to your hand.',
    flavor: 'Copper to Silver to Gold to Diamond. No further.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'advanced_refining', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'pennymelting',
    name: 'Pennymelting',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: 'hand', filter: { type: 'Resource' }, count: 1, pick: 'choose' },
        into: 'downgrade',
      },
      {
        op: 'copyCard',
        target: { who: 'self', zone: 'hand', filter: { type: 'Resource' }, count: 1, pick: 'cheapest' },
        to: 'hand',
      },
    ],
    triggers: [],
    text: 'Trash a Resource in your hand and add 2 copies of its downgrade to your hand. +1 Action.',
    flavor: 'Two worse things beat one better thing. Sometimes.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'pennymelting', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'currency_cremator',
    name: 'Currency Cremator',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'trash',
        target: { who: 'self', zone: 'hand', filter: { type: 'Resource' }, count: 1, pick: 'choose' },
      },
      { op: 'gain', stat: 'money', amount: 3 },
    ],
    triggers: [],
    text: 'Trash a Resource card from your hand for +3 Money.',
    flavor: 'Ashes, but liquid.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'currency_cremator', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
  {
    id: 'goldoron',
    name: 'Goldoron',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'createCard', defId: 'gold', to: 'gy' }],
    triggers: [],
    text: 'Flimsy. Add a Gold to your GY.',
    flavor: 'One gold, one goodbye.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'goldoron', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'diamondozen',
    name: 'Diamondozen',
    cost: { money: 8 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'createCard', defId: 'diamond', to: 'hand' }],
    triggers: [],
    text: 'Flimsy. Add a Diamond to your hand.',
    flavor: 'Not a dozen. Just the one.',
    complexity: 'T1',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'diamondozen', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'shine_bright',
    name: 'Shine Bright',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: 'hand', filter: { defId: 'gold' } },
        into: 'diamond',
      },
      {
        op: 'transform',
        target: { who: 'self', zone: 'gy', filter: { defId: 'gold' } },
        into: 'diamond',
      },
    ],
    triggers: [],
    text: 'Turn every Gold in your hand into a Diamond, then do the same for your GY. +1 Action.',
    flavor: 'Like a diamond in the sky.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'shine_bright', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'summon' },
  },
  {
    id: 'put_a_ring_on_it',
    name: 'Put a Ring on It',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: 'hand', filter: { defId: 'silver' } },
        into: 'tix',
      },
      {
        op: 'transform',
        target: { who: 'self', zone: 'hand', filter: { defId: 'gold' } },
        into: 'robux',
      },
      {
        op: 'transform',
        target: { who: 'self', zone: 'hand', filter: { defId: 'diamond' } },
        into: 'jlore',
      },
      { op: 'moveTo', target: { who: 'self', zone: 'hand', filter: { type: 'Points' } }, zone: 'gy' },
    ],
    triggers: [],
    text: 'Turn each Silver into a Tix, each Gold into a Robux and each Diamond into a Jlore, then move them from your hand to your GY.',
    flavor: 'If you liked it.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'put_a_ring_on_it', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'shining_kit',
    name: 'Shining Kit',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { money: 2 },
    effects: [{ op: 'buff', scope: 'nextPlayed', stat: 'money', amount: 1, times: 1 }],
    triggers: [],
    text: 'The next Resource you play permanently gains +1 Money. +2 Money.',
    flavor: 'A cloth, a polish, a permanent improvement.',
    complexity: 'T3',
    subsystems: ['S-BUFF'],
    shop: 'draft',
    art: { key: 'shining_kit', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'midas_touch',
    name: 'Midas Touch',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: ['PlayOnDraw'],
    stats: {},
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: 'hand', count: 1, pick: 'random' },
        into: 'gold',
      },
    ],
    triggers: [],
    text: 'Play on Draw. Turn a random card in your hand into a Gold.',
    flavor: 'He never asked which card.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'midas_touch', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'depot_draw',
    name: 'Depot Draw',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'reveal', target: { who: 'self', zone: 'library', count: 4, pick: 'top' } },
      {
        op: 'moveTo',
        target: { who: 'self', zone: 'library', count: 4, pick: 'top', filter: { type: 'Resource' } },
        zone: 'hand',
      },
      {
        op: 'moveTo',
        target: { who: 'self', zone: 'library', count: 4, pick: 'top' },
        zone: 'gy',
      },
    ],
    triggers: [],
    text: 'Reveal the top 4 cards of your Library. Put the Resources in your hand and discard the rest. +1 Action.',
    flavor: 'Loading bay, not showroom.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'depot_draw', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'sticky_fungers',
    name: 'Sticky Fungers',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { cards: 1 },
    effects: [
      {
        op: 'moveTo',
        target: { who: 'self', zone: 'library', filter: { type: 'Resource' } },
        zone: 'library',
        position: 'top',
      },
    ],
    triggers: [],
    text: 'Move every Resource in your Library to the top of it. +1 Card.',
    flavor: 'They cling to money specifically.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'sticky_fungers', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'villa_d_moneybags',
    name: 'Villa D. Moneybags',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'legendary',
    keywords: [],
    stats: {},
    effects: [
      { op: 'createCard', defId: 'gold', to: 'hand' },
      { op: 'createCard', defId: 'gold', to: 'gy', who: 'eachOpponent' },
    ],
    triggers: [],
    text: 'Add a Gold to your hand and a Gold to each opponent’s GY.',
    flavor: 'Generous, in a way that costs him nothing.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'villa_d_moneybags', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'coin' },
  },
  {
    id: 'intellectual_property_theft',
    name: 'Intellectual Property Theft',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'discover',
        pool: { scope: 'opponentGy', who: 'chosenOpponent', filter: { type: 'Resource' } },
        count: 3,
        pick: 1,
        prompt: 'Take what is theirs',
        then: [{ op: 'copyCard', target: { self: true }, to: 'hand', who: 'self' }],
      },
    ],
    triggers: [],
    text: 'Discover a Resource in an opponent’s GY and add a copy of it to your hand.',
    flavor: 'It was in a public discard pile, technically.',
    complexity: 'T3',
    subsystems: ['S-STEAL', 'S-DISCOVER'],
    shop: 'draft',
    art: { key: 'intellectual_property_theft', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'second_degree_forgery',
    name: 'Second-Degree Forgery',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'copyCard',
        target: {
          who: 'chosenOpponent',
          zone: 'play',
          filter: { type: 'Resource' },
          count: 1,
          pick: 'lastPlayed',
        },
        to: 'hand',
        who: 'self',
      },
      {
        op: 'conditional',
        if: { combo: 3 },
        then: [{ op: 'setKeyword', target: { self: true }, keyword: 'Flimsy', on: false }],
      },
    ],
    triggers: [],
    text: 'Flimsy. Copy the last Resource an opponent played into your hand. Combo 3: this loses Flimsy.',
    flavor: 'The first degree was the idea.',
    complexity: 'T3',
    subsystems: ['S-STEAL', 'S-COMBO'],
    shop: 'draft',
    art: { key: 'second_degree_forgery', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'petty_theft',
    name: 'Petty Theft',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: {
          has: {
            target: { who: 'chosenOpponent', zone: 'hand', filter: { type: 'Resource' } },
            atLeast: 1,
          },
        },
        then: [
          {
            op: 'moveTo',
            target: {
              who: 'chosenOpponent',
              zone: 'hand',
              filter: { type: 'Resource' },
              count: 1,
              pick: 'random',
            },
            zone: 'hand',
          },
        ],
        else: [{ op: 'createCard', defId: 'silver', to: 'gy' }],
      },
      {
        op: 'conditional',
        if: { combo: 3 },
        then: [{ op: 'setKeyword', target: { self: true }, keyword: 'Flimsy', on: false }],
      },
    ],
    triggers: [],
    text: 'Flimsy. Steal a Resource from an opponent’s hand. If they have none, add a Silver to your GY instead. Combo 3: this loses Flimsy.',
    flavor: 'Small crime, small sentence, small silver.',
    complexity: 'T3',
    subsystems: ['S-STEAL', 'S-COMBO'],
    shop: 'draft',
    art: { key: 'petty_theft', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'gold_ship',
    name: 'Gold Ship',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Gold'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { money: 3, actions: 1 },
    effects: [
      { op: 'lockPile', target: { shop: 'all', excludeJlore: true }, duration: 'turn' },
      { op: 'unlockPile', target: { shop: 'all', pick: 'choose' } },
    ],
    triggers: [],
    text: '+3 Money, +1 Action. Lock every pile but one of your choice until end of turn.',
    flavor: 'The harbour closes when the gold sails.',
    complexity: 'T3',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'gold_ship', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
];

export default cards;
