/**
 * A.9 Draft Shop — shop manipulation: locks, cost mods, pile surgery.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'window_shopping',
    name: 'Window Shopping',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: { buys: 1 },
    effects: [
      {
        op: 'gainCard',
        from: { shop: 'all', filter: { cost: { lte: 2 } }, pick: 'choose', count: 1 },
        to: 'gy',
        free: true,
      },
    ],
    triggers: [],
    text: 'Add a shop card costing (2) or less to your GY. +1 Buy.',
    flavor: 'Looking is free. This one is too.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'window_shopping', status: 'placeholder' },
  },
  {
    id: 'spotter',
    name: 'Spotter',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'gainCard',
        from: { shop: 'all', filter: { cost: { eq: 4 } }, pick: 'choose', count: 1 },
        to: 'hand',
        free: true,
      },
    ],
    triggers: [],
    text: 'Add a (4)-cost card from the Shop to your hand.',
    flavor: 'He knows a four when he sees one.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'spotter', status: 'placeholder' },
  },
  {
    id: 'elite_spotter',
    name: 'Elite Spotter',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'gainCard',
        from: { shop: 'all', filter: { cost: { eq: 8 } }, pick: 'choose', count: 1 },
        to: 'hand',
        free: true,
      },
    ],
    triggers: [],
    text: 'Add an (8)-cost card from the Shop to your hand.',
    flavor: 'Promoted for spotting bigger numbers.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'elite_spotter', status: 'placeholder' },
  },
  {
    id: 'blubber_baron',
    name: 'Blubber Baron',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'gainCard',
        from: { shop: 'all', filter: { cost: { lte: 2 } }, pick: 'choose' },
        to: 'gy',
        count: 2,
        free: true,
      },
    ],
    triggers: [],
    text: 'Add up to 2 shop cards costing (2) or less to your GY.',
    flavor: 'Bulk is a strategy.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'blubber_baron', status: 'placeholder' },
  },
  {
    id: 'shadow_moves',
    name: 'Shadow Moves',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'gainCard', from: { shop: 'all', pick: 'random', count: 1 }, to: 'hand', free: true },
    ],
    triggers: [],
    text: 'Steal a random card from the Shop into your hand. +1 Action.',
    flavor: 'Nobody saw the shelf empty.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'shadow_moves', status: 'placeholder' },
  },
  {
    id: 'firesale',
    name: 'Firesale',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'discover',
        pool: { scope: 'shop', filter: { cost: { lte: 2 } } },
        count: 3,
        pick: 1,
        prompt: 'Everything must go',
        then: [
          {
            op: 'gainCard',
            from: { shop: 'all', filter: { defId: '$discovered' } },
            to: 'hand',
            free: true,
          },
          {
            // The stolen card lands at the back of hand, so `bottom` is the one
            // just taken — and the defId filter means nothing is played when the
            // steal was not an Action.
            op: 'playCard',
            target: { who: 'self', zone: 'hand', filter: { defId: '$discovered', type: 'Action' }, count: 1, pick: 'bottom' },
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discover 3 shop cards costing (2) or less and steal one into your hand. If it is an Action, play it.',
    flavor: 'Everything must go, quickly.',
    complexity: 'T3',
    subsystems: ['S-CORE', 'S-DISCOVER'],
    shop: 'draft',
    art: { key: 'firesale', status: 'placeholder' },
  },
  {
    id: 'cult_leader',
    name: 'Cult Leader',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        // The pick is threaded through both clauses, so the steal is about the
        // card that was actually taken.
        op: 'discover',
        // Draft Shop piles only — not the basics, not the Prophet Shop, which
        // is gated on banked Prophet rather than on money.
        pool: {
          scope: 'shop',
          filter: { rarity: ['common', 'rare', 'epic', 'legendary', 'mythic'], not: { subtype: 'Prophet' } },
        },
        count: 3,
        pick: 1,
        prompt: 'Take the last one',
        then: [
          {
            op: 'gainCard',
            from: { shop: 'all', filter: { defId: '$discovered' } },
            to: 'gy',
            free: true,
          },
          {
            // "If that emptied the pile" — no copy of it is left in any Shop.
            op: 'conditional',
            if: { not: { has: { target: { zone: 'shop', filter: { defId: '$discovered' } }, atLeast: 1 } } },
            then: [
              {
                op: 'moveTo',
                target: { who: 'eachOpponent', zone: ['library', 'hand', 'gy'], filter: { defId: '$discovered' } },
                zone: 'gy',
                who: 'self',
              },
            ],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discover 3 Draft Shop cards and add one to your GY. If that emptied its pile, steal every copy of it from your opponents.',
    flavor: 'He takes the last one, then all the others.',
    complexity: 'T3',
    subsystems: ['S-STEAL', 'S-DISCOVER'],
    shop: 'draft',
    art: { key: 'cult_leader', status: 'placeholder' },
  },
  {
    id: 'cult_recruiter',
    name: 'Cult Recruiter',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 2, money: 2 },
    effects: [
      // `duration: 'turn'` expires on the turn it is applied, i.e. instantly;
      // `{turns: 1}` is the one that actually binds for the rest of this turn.
      { op: 'lockPile', target: { shop: 'all', excludeJlore: false }, duration: { turns: 1 } },
      { op: 'unlockPile', target: { shop: 'all', pick: 'choose', count: 1 } },
    ],
    triggers: [],
    text: 'You may buy from only one pile this turn. +2 Buys, +2 Money.',
    flavor: 'One vendor. One truth.',
    complexity: 'T3',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'cult_recruiter', status: 'placeholder' },
  },
  {
    id: 'glorious_propaganda',
    name: 'Glorious Propaganda',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'gainCard', from: { shop: 'draft', pick: 'random', count: 1 }, to: 'gy', free: true },
      { op: 'gainCard', from: { shop: 'resource', pick: 'random', count: 1 }, to: 'gy', free: true },
      { op: 'gainCard', from: { shop: 'points', pick: 'random', count: 1 }, to: 'gy', free: true },
    ],
    triggers: [],
    text: 'Add 1 random card from each of the Draft, Resource and Points shops to your GY.',
    flavor: 'The posters worked.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'glorious_propaganda', status: 'placeholder' },
  },
  {
    id: 'mediator',
    name: 'Mediator',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'shop' },
        count: 3,
        pick: 1,
        prompt: 'A gift for everyone',
        // `{self:true}` in a discover `then` is Mediator itself, not the pick —
        // the chosen card is only reachable through the '$discovered' sentinel.
        then: [{ op: 'createCard', defId: '$discovered', to: 'hand', who: 'eachPlayer' }],
      },
    ],
    triggers: [],
    text: 'Discover a shop card and add it to every player’s hand. +1 Action.',
    flavor: 'Fair is fair, unfortunately.',
    complexity: 'T3',
    subsystems: ['S-DISCOVER'],
    shop: 'draft',
    art: { key: 'mediator', status: 'placeholder' },
  },
  {
    id: 'welfare',
    name: 'Welfare',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'shop' },
        count: 3,
        pick: 1,
        prompt: 'Distribute to the table',
        then: [{ op: 'createCard', defId: '$discovered', to: 'gy', who: 'eachPlayer' }],
      },
    ],
    triggers: [],
    text: 'Choose a shop card and add it to every player’s GY in turn order, starting with you. +1 Action.',
    flavor: 'You first, then the rest.',
    complexity: 'T3',
    subsystems: ['S-DISCOVER'],
    shop: 'draft',
    art: { key: 'welfare', status: 'placeholder' },
  },
  {
    id: 'lockdown',
    name: 'Lockdown',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'common',
    keywords: [],
    stats: { cards: 1 },
    effects: [
      {
        op: 'lockPile',
        target: { shop: 'draft', pick: 'choose', count: 1 },
        duration: 'untilEndOfYourNextTurn',
      },
    ],
    triggers: [],
    text: 'Lock a Draft Shop pile until the end of your next turn. +1 Card.',
    flavor: 'Closed for the duration.',
    complexity: 'T2',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'lockdown', status: 'placeholder' },
  },
  {
    id: 'blackout',
    name: 'Blackout',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, cards: 1 },
    effects: [
      {
        op: 'lockPile',
        target: { shop: 'draft', pick: 'choose', count: 1 },
        duration: 'untilEndOfYourNextTurn',
      },
    ],
    triggers: [],
    text: 'Lock a Draft Shop pile until the end of your next turn. +1 Action, +1 Card.',
    flavor: 'The lights go out over one aisle.',
    complexity: 'T2',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'blackout', status: 'placeholder' },
  },
  {
    id: 'back_to_basics',
    name: 'Back to Basics',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [
      {
        op: 'lockPile',
        target: { shop: 'all', filter: { cost: { gte: 6 } } },
        duration: 'untilEndOfYourNextTurn',
      },
    ],
    triggers: [],
    text: 'Flimsy. Lock every pile costing (6) or more until the end of your next turn. +1 Action.',
    flavor: 'Nobody needs the expensive things.',
    complexity: 'T3',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'back_to_basics', status: 'placeholder' },
  },
  {
    id: 'go_fish',
    name: 'Go Fish',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        // One pile, threaded through both clauses: the discard and the Lock
        // have to be about the same pile, which only the sentinel can do.
        op: 'discover',
        pool: { scope: 'shop', filter: { not: { defId: 'copper' } } },
        count: 3,
        pick: 1,
        prompt: 'Do you have any...',
        then: [
          {
            op: 'discard',
            target: { who: 'eachOpponent', zone: 'hand', filter: { defId: '$discovered' } },
          },
          {
            op: 'lockPile',
            target: { shop: 'all', filter: { defId: '$discovered' }, excludeJlore: false },
            duration: 'untilEndOfYourNextTurn',
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discover 3 non-Copper shop cards and name one. Opponents discard every copy of it from their hands. Then Lock its pile until the end of your next turn.',
    flavor: 'Do you have any Silvers? Go fish.',
    complexity: 'T3',
    subsystems: ['S-LOCK', 'S-STEAL', 'S-DISCOVER'],
    shop: 'draft',
    art: { key: 'go_fish', status: 'placeholder' },
  },
  {
    id: 'freeze_tag',
    name: 'Freeze Tag',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'lockPile',
        target: { shop: 'draft', pick: 'choose', count: 1 },
        duration: 'untilEndOfYourNextTurn',
      },
      { op: 'unlockPile', target: { shop: 'draft', pick: 'random', count: 1 } },
      {
        op: 'conditional',
        if: { ifPrevious: true },
        then: [
          { op: 'gainCard', from: { shop: 'draft', pick: 'random', count: 1 }, to: 'gy', free: true },
        ],
      },
    ],
    triggers: [],
    text: 'Lock one Draft pile and unlock a random other one. If they cost the same, add the unlocked pile’s top card to your GY. +1 Action.',
    flavor: 'Frozen. Unfrozen. Confused.',
    complexity: 'T3',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'freeze_tag', status: 'placeholder' },
  },
  {
    id: 'arm_of_the_jempire',
    name: 'Arm of the Jempire',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'lockPile',
        target: { shop: 'draft', pick: 'random', count: 3 },
        duration: 'untilYourNextTurn',
      },
      // "for each you could have afforded" cannot live in a filter —
      // NumericFilter takes literal numbers only and cannot read the wallet —
      // so the draw is an expression over unspent Money instead, capped at the
      // three piles that were locked.
      { op: 'draw', amount: { expr: 'min(3, moneyUnspent)' } },
    ],
    triggers: [],
    text: 'Lock 3 random Draft piles until your next turn. Draw 1 Card per unspent Money, up to 3. +1 Action.',
    flavor: 'The arm reaches three shelves.',
    complexity: 'T3',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'arm_of_the_jempire', status: 'placeholder' },
  },
  {
    id: 'archwarden_of_jlore',
    name: 'Archwarden of Jlore',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: { actions: 1, cards: 1 },
    effects: [
      {
        op: 'lockPile',
        target: { shop: 'points', filter: { defId: 'jlore' } },
        duration: { untilDiscarded: 8 },
      },
    ],
    triggers: [],
    text: 'Flimsy. Lock the Jlore pile until (8) worth of cards have been discarded. +1 Action, +1 Card.',
    flavor: 'The vault opens when the tribute is paid.',
    complexity: 'T3',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'archwarden_of_jlore', status: 'placeholder' },
  },
  {
    id: 'cloud_nine',
    name: 'Cloud Nine',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, buys: 1, cards: 1 },
    effects: [
      // The "remove all cost changes" half needs a clearing op the DSL does not
      // have: a delta-0 modifier cannot undo the modifiers already on a pile,
      // and a permanent floor-0 entry would quietly clamp every negative price
      // in the game for the rest of the match. Only the unlock ships.
      { op: 'unlockPile', target: { shop: 'all' } },
    ],
    triggers: [],
    text: 'Remove all Locks from the Shop. +1 Action, +1 Buy, +1 Card.',
    flavor: 'Everything back to list price.',
    complexity: 'T2',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'cloud_nine', status: 'placeholder' },
  },
  {
    id: 'the_jlore_must_flow',
    name: 'The Jlore Must Flow',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 1 },
    effects: [
      { op: 'modifyCost', scope: 'allShops', delta: -1, floor: 1, duration: 'turn' },
    ],
    triggers: [],
    text: 'Every shop card costs (1) less this turn, to a minimum of (1). +1 Buy.',
    flavor: 'He who controls the discount.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'the_jlore_must_flow', status: 'placeholder' },
  },
  {
    id: 'cup_runneth_over',
    name: 'Cup Runneth Over',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        // One pile for both halves. Two `pick:'choose'` selectors would raise
        // two independent prompts that can name different piles.
        //
        // Known gap: a *fully empty* pile is unreachable and no card-data shape
        // fixes it. A `pool:{scope:'shop'}` Discover samples defIds off
        // instances sitting in a pile, so an empty pile offers none;
        // selectPilesWith drops zero-card piles inside its `filter` branch; and
        // opReplenishPile's own empty-pile fallback resolves the pile id as a
        // defId (`tryGetCard(pileId)`) when pile ids are `<shop>:<defId>`, so it
        // finds nothing either. Partially-depleted piles refill correctly.
        op: 'discover',
        // Draft Shop piles only — not the basics, not the Prophet Shop, which
        // is gated on banked Prophet rather than on money.
        pool: {
          scope: 'shop',
          filter: { rarity: ['common', 'rare', 'epic', 'legendary', 'mythic'], not: { subtype: 'Prophet' } },
        },
        count: 3,
        pick: 1,
        prompt: 'Fill it to the brim',
        then: [
          { op: 'replenishPile', target: { shop: 'all', filter: { defId: '$discovered' } } },
          {
            op: 'modifyCost',
            scope: 'pile',
            target: { shop: 'all', filter: { defId: '$discovered' } },
            delta: -1,
            floor: 1,
            duration: 'permanent',
          },
        ],
      },
    ],
    triggers: [],
    text: 'Flimsy. Discover 3 Draft Shop cards and fully replenish the pile of the one you pick. Its cards now cost (1) less, to a minimum of (1).',
    flavor: 'And then some.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD', 'S-DISCOVER'],
    shop: 'draft',
    art: { key: 'cup_runneth_over', status: 'placeholder' },
  },
  {
    id: 'throttle_markets',
    name: 'Throttle Markets',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 1, money: 1 },
    effects: [
      {
        op: 'choose',
        options: [
          {
            label: 'Draft piles cost (1) more',
            effects: [
              {
                op: 'modifyCost',
                scope: 'draftShop',
                delta: 1,
                floor: 0,
                duration: 'untilYourNextTurn',
              },
            ],
          },
          {
            label: 'Resource and Points piles cost (1) more',
            effects: [
              {
                op: 'modifyCost',
                scope: 'resourceShop',
                delta: 1,
                floor: 0,
                duration: 'untilYourNextTurn',
              },
              {
                op: 'modifyCost',
                scope: 'pointsShop',
                delta: 1,
                floor: 0,
                duration: 'untilYourNextTurn',
              },
            ],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Until your next turn, either Draft piles cost (1) more, or Resource and Points piles cost (1) more. +1 Buy, +1 Money.',
    flavor: 'Someone has a hand on the valve.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'throttle_markets', status: 'placeholder' },
  },
  {
    id: 'price_fixing',
    name: 'Price Fixing',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'modifyCost',
        scope: 'pile',
        target: { shop: 'draft', pick: 'choose', count: 1 },
        // There is no expression variable for the average Draft pile cost, so
        // the average deck cost stands in for it until one exists.
        setTo: { expr: 'floor(avgCostOfDeck)' },
        floor: 0,
        duration: 'untilEndOfYourNextTurn',
      },
    ],
    triggers: [],
    text: 'Set a Draft pile’s cost to the average Draft pile cost, rounded down, until the end of your next turn. +1 Action.',
    flavor: 'Perfectly legal in this jurisdiction.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'price_fixing', status: 'placeholder' },
  },
  {
    id: 'missed_vintage',
    name: 'Missed Vintage',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 1 },
    effects: [
      {
        op: 'modifyCost',
        scope: 'pile',
        target: { shop: 'draft', pick: 'tallest', count: 2 },
        delta: -2,
        floor: 0,
        duration: 'turn',
      },
    ],
    triggers: [],
    text: 'Reduce the top card cost of the two tallest Draft piles by (2). +1 Buy.',
    flavor: 'Nobody wanted the 2019.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'missed_vintage', status: 'placeholder' },
  },
  {
    id: 'vexxed',
    name: 'Vexxed',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [{ op: 'swapPileCosts', target: { shop: 'all', pick: 'random', count: 2 } }],
    triggers: [],
    text: 'Swap the costs of two random piles.',
    flavor: 'The tags got mixed up. Nobody is fixing it.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'vexxed', status: 'placeholder' },
  },
  {
    id: 'discount_coupon',
    name: 'Discount Coupon',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        // `selfPlayCount - 5` is non-zero — and therefore true — on plays 1-4,
        // so the two branches were the wrong way round. And `scope:'nextBuy'`
        // never reads `setTo`, so "free" has to be a delta deep enough to land
        // on the floor. The play counter itself is kept by the engine on every
        // play, so the card must not add its own on top.
        op: 'conditional',
        if: { expr: 'selfPlayCount >= 5' },
        then: [{ op: 'modifyCost', scope: 'nextBuy', delta: -999, floor: 0, duration: 'turn' }],
        else: [{ op: 'modifyCost', scope: 'nextBuy', delta: -1, floor: 0, duration: 'turn' }],
      },
    ],
    triggers: [],
    text: 'The next card you buy this turn costs (1) less — from its 5th play on, (0) instead. (Played {playCount} times.)',
    flavor: 'Terms and conditions accumulate.',
    complexity: 'T4',
    subsystems: ['S-PERSIST', 'S-COSTMOD', 'S-TEXTGEN'],
    shop: 'draft',
    art: { key: 'discount_coupon', status: 'placeholder' },
  },
  {
    id: 'miracle_prep',
    name: 'Miracle Prep',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      { op: 'modifyCost', scope: 'nextBuy', delta: -2, floor: 0, duration: 'turn' },
    ],
    triggers: [],
    text: 'The next card you buy costs (2) less.',
    flavor: 'Lay the groundwork for something unlikely.',
    complexity: 'T2',
    subsystems: ['S-COSTMOD'],
    shop: 'draft',
    art: { key: 'miracle_prep', status: 'placeholder' },
  },
  {
    id: 'nickel_and_dime',
    name: 'Nickel and Dime',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'modifyCost',
        scope: 'nextBuyOpponent',
        delta: 1,
        floor: 0,
        duration: 'untilYourNextTurn',
      },
    ],
    triggers: [
      {
        on: 'onOpponentBuy',
        maxPerTurn: 1,
        effects: [{ op: 'createCard', defId: 'silver', to: 'gy' }],
      },
    ],
    text: 'Flimsy. The next card an opponent buys costs (1) more. When they buy it, you gain a Silver.',
    flavor: 'A toll booth on their turn.',
    complexity: 'T3',
    subsystems: ['S-COSTMOD', 'S-STEAL'],
    shop: 'draft',
    art: { key: 'nickel_and_dime', status: 'placeholder' },
  },
  {
    id: 'pocket_wormhole',
    name: 'Pocket Wormhole',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        // The Discover names the pile, which is the only way to scope the
        // transform to one pile — a Selector has no pile axis. The Lock has to
        // run first, while the pile's top card still matches the pick.
        op: 'discover',
        // Draft Shop piles only — not the basics, not the Prophet Shop, which
        // is gated on banked Prophet rather than on money.
        pool: {
          scope: 'shop',
          filter: { rarity: ['common', 'rare', 'epic', 'legendary', 'mythic'], not: { subtype: 'Prophet' } },
        },
        count: 3,
        pick: 1,
        prompt: 'Which shelf slips universe?',
        then: [
          {
            op: 'lockPile',
            target: { shop: 'all', filter: { defId: '$discovered' } },
            duration: 'untilYourNextTurn',
          },
          {
            op: 'transform',
            target: { zone: 'shop', filter: { defId: '$discovered' } },
            into: { pool: { scope: 'knownUniverse' } },
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discover 3 Draft Shop cards. Lock the pile of the one you pick until your next turn, and every card in it becomes a random Known Universe card.',
    flavor: 'Same shelf. Different universe.',
    complexity: 'T3',
    subsystems: ['S-DISCOVER', 'S-LOCK', 'S-CODEX'],
    shop: 'draft',
    art: { key: 'pocket_wormhole', status: 'placeholder' },
  },
  {
    id: 'chron_cache',
    name: 'Chron Caché',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        // `costOverride` reprices the whole pile, permanently, not the card
        // being inserted — there is no per-instance price, so the Diamond goes
        // in at its printed cost.
        op: 'addToPileTop',
        target: { shop: 'draft', pick: 'random', count: 1 },
        defId: 'diamond',
        count: 1,
      },
    ],
    triggers: [],
    text: 'Add a Diamond to the top of a random Draft pile. +1 Action.',
    flavor: 'Buried one layer down.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'chron_cache', status: 'placeholder' },
  },
  {
    id: 'supernova',
    name: 'Supernova',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { buys: 1 },
    effects: [
      {
        // The node count is per pile, so 10 piles x 10 was 100 cards. And
        // `costOverride` prices the whole pile forever, not the cards added, so
        // it would have made ten entire piles cost (1) for the rest of the match.
        op: 'addToPileTop',
        target: { shop: 'all', pick: 'random', count: 10 },
        defId: { pool: { scope: 'entireUniverse' } },
        count: 1,
      },
    ],
    triggers: [],
    text: 'Add 1 random card from the Entire Universe to the top of each of 10 random shop piles. +1 Buy.',
    flavor: 'Everything in the sky lands in the shop.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'supernova', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'i_ship_it',
    name: 'I Ship It',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: { buys: 1 },
    effects: [{ op: 'mergePiles', target: { shop: 'draft', pick: 'choose', count: 2 } }],
    triggers: [],
    text: 'Flimsy. Shuffle two piles together and split them evenly between the two slots. +1 Buy.',
    flavor: 'They belong together.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'i_ship_it', status: 'placeholder', anim: 'shuffle' },
  },
  {
    id: 'the_big_backening',
    name: 'The Big Backening',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { buys: 1, money: 1 },
    effects: [],
    triggers: [
      {
        on: 'onBuy',
        zones: ['play'],
        maxPerTurn: 1,
        effects: [
          {
            op: 'addToPileTop',
            target: { shop: 'all', pick: 'choose' },
            defId: { pool: { scope: 'shop' } },
            count: 2,
          },
        ],
      },
    ],
    text: 'Add 2 copies of the first card you buy this turn to the top of that pile. +1 Buy, +1 Money.',
    flavor: 'It comes back bigger.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'the_big_backening', status: 'placeholder' },
  },
  {
    id: 'new_banner_day',
    name: 'New Banner Day!',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { money: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'shop' },
        count: 3,
        pick: 1,
        prompt: 'Set the banner',
        then: [
          {
            op: 'nextCardModifier',
            mod: { appliesTo: 'buy', buyTo: 'gy', uses: 1 },
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discover a card from a non-empty pile. If you later buy a different card costing at least as much this turn, also gain from that pile. +1 Money.',
    flavor: 'New banner, same shop.',
    complexity: 'T3',
    subsystems: ['S-DISCOVER'],
    shop: 'draft',
    art: { key: 'new_banner_day', status: 'placeholder' },
  },
  {
    id: 'shopkeep',
    name: 'Shopkeep',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, buys: 1, cards: 1, money: 1 },
    effects: [
      {
        op: 'discard',
        target: { who: 'self', zone: 'hand', count: { expr: 'emptyOrLockedPiles' }, pick: 'choose' },
      },
    ],
    triggers: [],
    text: 'Discard a card for each empty or Locked pile. +1 Action, +1 Buy, +1 Card, +1 Money.',
    flavor: 'He charges rent on absence.',
    complexity: 'T2',
    subsystems: ['S-LOCK'],
    shop: 'draft',
    art: { key: 'shopkeep', status: 'placeholder' },
  },
  {
    id: 'five_year_plan',
    name: 'Five Year Plan',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: ['CN'],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        // A Selector has no pile axis, so the pick is what names the pile:
        // without it `zone:'shop'` is every card in every shop.
        op: 'discover',
        // Draft Shop piles only — not the basics, not the Prophet Shop, which
        // is gated on banked Prophet rather than on money.
        pool: {
          scope: 'shop',
          filter: { rarity: ['common', 'rare', 'epic', 'legendary', 'mythic'], not: { subtype: 'Prophet' } },
        },
        count: 3,
        pick: 1,
        prompt: 'Nationalise a shelf',
        then: [
          {
            op: 'transform',
            target: { zone: 'shop', filter: { defId: '$discovered' } },
            into: { pool: { scope: 'entireUniverse', filter: { subtype: 'CN' } } },
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discover 3 Draft Shop cards. Every card in the pile of the one you pick becomes a CN card. +1 Action.',
    flavor: 'Production quotas, met on paper.',
    complexity: 'T3',
    subsystems: ['S-CORE', 'S-DISCOVER'],
    shop: 'draft',
    art: { key: 'five_year_plan', status: 'placeholder' },
  },
  {
    id: 'bad_omen',
    name: 'Bad Omen',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'addToPileTop',
        target: { shop: 'draft', pick: 'choose', count: 1 },
        defId: 'cursed_pig',
        count: 1,
      },
    ],
    triggers: [],
    // A pile is an ordered stack and the Pig goes on top, so the next buyer
    // gets the Pig rather than the card under it. "Also gives" would need a
    // pile-scoped purchase rider, which the DSL does not have.
    text: 'Flimsy. Choose a Draft pile: the next card bought from it is a Cursed Pig.',
    flavor: 'Something is wrong with that shelf.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'bad_omen', status: 'placeholder' },
  },
  {
    id: 'water_into_swine',
    name: 'Water Into Swine',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        // The empty-pile guard in selectPilesWith only runs when a filter is
        // present, and an empty filter matches everything — so this is the way
        // to say "every non-empty Draft pile" and leave emptied piles emptied.
        op: 'addToPileTop',
        target: { shop: 'draft', filter: {} },
        defId: 'cursed_pig',
        count: 1,
      },
    ],
    triggers: [],
    text: 'Add a Cursed Pig to the top of every non-empty Draft pile.',
    flavor: 'A lesser miracle.',
    complexity: 'T2',
    subsystems: ['S-TOKEN'],
    shop: 'draft',
    art: { key: 'water_into_swine', status: 'placeholder' },
  },
  {
    id: 'glubby_gloob_the_auctioneer',
    name: 'Glubby Gloob the Auctioneer',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'legendary',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'delayed',
        when: 'startOfNextTurn',
        effects: [
          {
            op: 'discover',
            pool: { scope: 'shop' },
            count: 3,
            pick: 1,
            prompt: 'The gavel falls',
            // `{self:true}` here is Glubby Gloob, which Flimsy already put in
            // the trash — the winner has to be paid with the sentinel.
            then: [{ op: 'createCard', defId: '$discovered', to: 'gy' }],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Flimsy. Blind auction for 3 random shop cards. You get 6 chips, each opponent 5. It resolves at the start of your next turn.',
    flavor: 'Going once. Going twice. Glubb.',
    complexity: 'T4',
    subsystems: ['S-AUCTION', 'S-DELAYED'],
    shop: 'draft',
    art: { key: 'glubby_gloob_the_auctioneer', status: 'placeholder' },
  },
  {
    id: 'jlore_accelerator',
    name: 'Jlore Accelerator',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'gainCard',
        from: { shop: 'points', filter: { defId: 'jlore' } },
        to: 'hand',
        who: 'eachPlayer',
        free: true,
      },
    ],
    triggers: [],
    text: 'Add a Jlore from the pile to every player’s hand.',
    flavor: 'Ends the game faster, for everyone.',
    complexity: 'T2',
    subsystems: ['S-ENDGAME'],
    shop: 'draft',
    art: { key: 'jlore_accelerator', status: 'placeholder' },
  },
  {
    id: 'biology_project',
    name: 'Biology Project',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'gainCard',
        from: { shop: 'resource', filter: { defId: 'diamond' } },
        to: 'hand',
        who: 'eachPlayer',
        free: true,
      },
    ],
    triggers: [],
    text: 'Add a Diamond from the pile to every player’s hand.',
    flavor: 'Group project. Everyone gets the grade.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'biology_project', status: 'placeholder' },
  },
];

export default cards;
