/**
 * A.8 Draft Shop — trashing, upcycling and deck sculpting.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'pawn_shop',
    name: 'Pawn Shop',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: {
          has: {
            target: {
              who: 'self',
              zone: 'hand',
              filter: { not: { defId: 'copper' }, keyword: 'Flimsy' },
            },
            atLeast: 1,
          },
        },
        then: [{ op: 'gain', stat: 'actions', amount: 1 }],
      },
      {
        op: 'trash',
        target: {
          who: 'self',
          zone: 'hand',
          filter: { not: { defId: 'copper' } },
          count: 1,
          pick: 'choose',
        },
      },
      { op: 'gain', stat: 'money', amount: 2 },
      { op: 'draw', amount: 1 },
    ],
    triggers: [],
    text: 'Trash a non-Copper card from your hand: +2 Money, +1 Card. If it was Flimsy, also +1 Action.',
    flavor: 'Everything has a price, briefly.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'pawn_shop', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'daylight_salesman',
    name: 'Daylight Salesman',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      { op: 'trash', target: { who: 'self', zone: 'hand', count: 1, pick: 'choose' } },
      { op: 'gain', stat: 'money', amount: 3 },
    ],
    triggers: [],
    text: 'Trash a card from your hand for +3 Money.',
    flavor: 'Robbery, but well-lit.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'daylight_salesman', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'moonlight_salesman',
    name: 'Moonlight Salesman',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'common',
    keywords: [],
    stats: {},
    effects: [
      { op: 'trash', target: { who: 'self', zone: 'hand', count: 1, pick: 'choose' } },
      { op: 'draw', amount: 3 },
    ],
    triggers: [],
    text: 'Trash a card from your hand for +3 Cards.',
    flavor: 'Second job, same product.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'moonlight_salesman', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'upcycle',
    name: 'Upcycle',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'trash', target: { who: 'self', zone: 'hand', count: 1, pick: 'choose' } },
      {
        op: 'transform',
        target: { who: 'self', zone: 'gy', count: 1, pick: 'lastPlayed' },
        into: { costDelta: 2 },
      },
      {
        op: 'gainCard',
        from: { shop: 'all', pick: 'choose', excludeJlore: false },
        to: 'gy',
        free: true,
      },
    ],
    triggers: [],
    text: 'Trash a card in your hand to gain a card costing up to (2) more than it.',
    flavor: 'Same material, better job.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'upcycle', status: 'placeholder' },
  },
  {
    id: 'upcycled_upcycle',
    name: 'Upcycled Upcycle',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'trash', target: { who: 'self', zone: 'hand', count: 1, pick: 'choose' } },
      {
        op: 'transform',
        target: { who: 'self', zone: 'gy', count: 1, pick: 'lastPlayed' },
        into: { costDelta: 3 },
      },
      {
        op: 'gainCard',
        from: { shop: 'all', pick: 'choose' },
        to: 'gy',
        free: true,
      },
    ],
    triggers: [],
    text: 'Trash a card in your hand to gain a card costing up to (3) more than it.',
    flavor: 'It upcycles itself, obviously.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'upcycled_upcycle', status: 'placeholder' },
  },
  {
    id: 'trash_for_treasure',
    name: 'Trash for Treasure',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      { op: 'trash', target: { who: 'self', zone: 'hand', count: 1, pick: 'choose' } },
      {
        op: 'discover',
        pool: { scope: 'shop', filter: { cost: { lte: 3 } } },
        count: 3,
        pick: 1,
        prompt: 'Pick your treasure',
        then: [{ op: 'moveTo', target: { self: true }, zone: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Trash a card in your hand, then Discover a Draft Shop card costing (3) or less and add it to your hand.',
    flavor: 'One man’s.',
    complexity: 'T3',
    subsystems: ['S-DISCOVER'],
    shop: 'draft',
    art: { key: 'trash_for_treasure', status: 'placeholder' },
  },
  {
    id: 'recession_indicator',
    name: 'Recession Indicator',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'epic',
    keywords: [],
    stats: { cards: 1 },
    effects: [
      { op: 'trash', target: { who: 'self', zone: 'hand', filter: { cost: { eq: 0 } } } },
      {
        op: 'choose',
        options: [
          {
            label: 'Also trash every non-Copper (0)-cost card in opponents’ hands',
            effects: [
              {
                op: 'trash',
                target: {
                  who: 'eachOpponent',
                  zone: 'hand',
                  filter: { cost: { eq: 0 }, not: { defId: 'copper' } },
                },
              },
            ],
          },
          { label: 'Leave opponents alone', effects: [{ op: 'noop' }] },
        ],
      },
    ],
    triggers: [],
    text: 'Trash all (0)-cost cards in your hand. You may also trash all non-Copper (0)-cost cards in opponents’ hands. +1 Card.',
    flavor: 'Two consecutive quarters of bad draws.',
    complexity: 'T3',
    subsystems: ['S-STEAL'],
    shop: 'draft',
    art: { key: 'recession_indicator', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'pauper_no_longer',
    name: 'Pauper No Longer',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'forEach',
        over: { who: 'self', zone: 'hand', filter: { rarity: 'common' } },
        effects: [
          { op: 'draw', amount: 1 },
          { op: 'gain', stat: 'money', amount: 1 },
        ],
      },
      { op: 'trash', target: { who: 'self', zone: 'hand', filter: { rarity: 'common' } } },
    ],
    triggers: [],
    text: 'Trash all Common cards in your hand. +1 Card and +1 Money for each.',
    flavor: 'Moving up, one Common at a time.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'pauper_no_longer', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'scorched_earth',
    name: 'Scorched Earth',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 3, buys: 2, cards: 4, money: 5 },
    effects: [{ op: 'trash', target: { who: 'self', zone: 'hand' } }],
    triggers: [],
    text: 'Trash all other cards in your hand. +3 Actions, +2 Buys, +4 Cards, +5 Money.',
    flavor: 'Leave nothing for the next turn.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'scorched_earth', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'restart_mission',
    name: 'Restart Mission',
    cost: { money: 7 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'trash', target: { who: 'self', zone: ['library', 'hand', 'gy'] } },
      {
        op: 'gainCard',
        from: { shop: 'all', filter: { cost: { lte: 7 } }, pick: 'choose' },
        to: 'gy',
        count: 7,
        free: true,
      },
    ],
    triggers: [],
    text: 'Flimsy. Trash your entire deck, then add 7 shop cards costing (7) or less to it.',
    flavor: 'Load last save. There is no last save.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'restart_mission', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'the_ultimate_sacrifice',
    name: 'The Ultimate Sacrifice',
    cost: { money: 8 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'selectCards',
        from: { who: 'self', zone: 'hand', filter: { not: { type: 'Resource' } } },
        min: 2,
        max: 2,
        then: [
          { op: 'trash', target: { self: true } },
          {
            op: 'forEach',
            over: { who: 'self', zone: ['library', 'hand', 'gy'] },
            effects: [{ op: 'createCard', defId: 'jlore', to: 'gy' }],
          },
          { op: 'trash', target: { who: 'self', zone: ['library', 'hand', 'gy'] } },
        ],
      },
    ],
    triggers: [],
    text: 'Trash two identical non-Resource cards in your hand, then trash every remaining copy in your deck. Add that many Jlore to your GY.',
    flavor: 'They went together.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'the_ultimate_sacrifice', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'glitch_in_the_system',
    name: 'Glitch in the System',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'trash',
        target: {
          who: 'eachPlayer',
          zone: ['library', 'hand', 'gy'],
          filter: { cost: { lte: 3 }, not: { defId: 'copper' } },
        },
      },
    ],
    triggers: [],
    text: 'Trash every card costing (0) to (3) in every deck, except Copper.',
    flavor: 'The economy stutters, then resumes.',
    complexity: 'T3',
    subsystems: ['S-STEAL'],
    shop: 'draft',
    art: { key: 'glitch_in_the_system', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'twisting_nether',
    name: 'Twisting Nether',
    cost: { money: 9 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'legendary',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'trashPile', target: { shop: 'all', pick: 'choose', excludeJlore: true } },
    ],
    triggers: [],
    text: 'Flimsy. Choose a shop pile other than Jlore and trash it entirely.',
    flavor: 'It was there. Now it is not.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'twisting_nether', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'safety_net',
    name: 'Safety Net',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [],
    triggers: [
      {
        on: 'onTrash',
        zones: ['play'],
        maxPerTurn: 1,
        condition: {
          not: {
            has: {
              target: { who: 'self', zone: 'trash', filter: { keyword: 'Temporary' } },
              atLeast: 1,
            },
          },
        },
        effects: [
          { op: 'moveTo', target: { who: 'self', zone: 'trash', count: 1, pick: 'lastPlayed' }, zone: 'gy' },
          { op: 'draw', amount: 1 },
        ],
      },
    ],
    text: 'The next non-Temporary card of yours that would be trashed this turn goes to your GY instead. If that happens, +1 Card. +1 Action.',
    flavor: 'Caught. Bruised, but caught.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'safety_net', status: 'placeholder' },
  },
  {
    id: 'the_fall_guy',
    name: 'The Fall Guy',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { cards: 1 },
    effects: [],
    triggers: [
      {
        on: 'onTrash',
        zones: ['library', 'hand', 'gy'],
        effects: [
          { op: 'moveTo', target: { who: 'self', zone: 'trash', count: 1, pick: 'lastPlayed' }, zone: 'gy' },
          { op: 'trash', target: { self: true } },
        ],
      },
    ],
    text: 'Whenever one of your cards would be trashed by a non-Flimsy effect, this leaps out of your deck and is trashed instead. +1 Card.',
    flavor: 'Somebody has to.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'the_fall_guy', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'card_sleeve',
    name: 'Card Sleeve',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: { actions: 1, cards: 1 },
    effects: [
      {
        op: 'setKeyword',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'] },
        keyword: 'Flimsy',
        on: false,
      },
      {
        op: 'setKeyword',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'] },
        keyword: 'Temporary',
        on: false,
      },
    ],
    triggers: [],
    text: 'Flimsy. +1 Action, +1 Card. Remove Flimsy and Temporary from every card in your deck.',
    flavor: 'Protects everything but itself.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'card_sleeve', status: 'placeholder' },
  },
  {
    id: 'cookie_gruzzler',
    name: 'Cookie Gruzzler',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'trash',
        target: { who: 'eachPlayer', zone: 'library', count: 1, pick: 'top' },
      },
      { op: 'addCounter', target: { self: true }, key: 'gruzzled', amount: { expr: 'playerCount' } },
    ],
    triggers: [
      {
        on: 'onTrash',
        effects: [
          {
            op: 'moveTo',
            target: { who: 'self', zone: 'trash', count: { expr: 'selfCounter' }, pick: 'lastPlayed' },
            zone: 'gy',
          },
        ],
      },
    ],
    text: 'Trash the top card of each player’s Library. When this card is trashed, add all of them to your GY. ({gruzzled} stored)',
    flavor: 'It keeps them somewhere.',
    complexity: 'T3',
    subsystems: ['S-PERSIST', 'S-STEAL'],
    shop: 'draft',
    art: { key: 'cookie_gruzzler', status: 'placeholder' },
  },
  {
    id: 'corrosion',
    name: 'Corrosion',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, cards: 1 },
    effects: [
      {
        op: 'setKeyword',
        target: {
          who: 'eachOpponent',
          zone: ['library', 'hand', 'gy'],
          count: 3,
          pick: 'random',
        },
        keyword: 'Flimsy',
        on: true,
      },
    ],
    triggers: [],
    text: '+1 Action, +1 Card. Give Flimsy to 3 cards in opponents’ decks.',
    flavor: 'It spreads where it is wettest.',
    complexity: 'T3',
    subsystems: ['S-STEAL'],
    shop: 'draft',
    art: { key: 'corrosion', status: 'placeholder' },
  },
  {
    id: 'zzlurper',
    name: 'Zzlurper',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'trash', target: { zone: 'shop', count: 1, pick: 'choose' } },
    ],
    triggers: [],
    text: 'Trash a card in the Shop. +1 Action.',
    flavor: 'Zzlurp.',
    complexity: 'T2',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'zzlurper', status: 'placeholder', anim: 'trash' },
  },
  {
    id: 'coal',
    name: 'Coal',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { money: -1 },
    effects: [{ op: 'addCounter', target: { self: true }, key: 'playCount', amount: 1 }],
    triggers: [
      {
        on: 'onPlay',
        condition: { expr: 'selfPlayCount - 2' },
        effects: [
          { op: 'trash', target: { self: true } },
          { op: 'createCard', defId: 'diamond', to: 'hand' },
        ],
      },
    ],
    text: '-1 Money. On the 3rd play, trash this and add a Diamond to your hand. ({playsLeft} left!)',
    flavor: 'Pressure, time, and two bad turns.',
    complexity: 'T4',
    subsystems: ['S-PERSIST', 'S-TEXTGEN'],
    shop: 'draft',
    art: { key: 'coal', status: 'placeholder' },
  },
];

export default cards;
