/**
 * A.25 — Draft Shop: Discover, generation and rarity pulls.
 *
 * SB-40: Zephrys, Second Time Around and Infinite Realities resolve through the
 * cheap substitutes in `@engine/meta` rather than any solver. The card data
 * below carries the Discover shape; `simSubstitutes` is the hook the
 * interpreter calls to fill those pools with the heuristic picks.
 *
 * SB-13: the four Fusion cards route through `@engine/systems` fusion.
 */
import type { CardDefinition, CardDefId, EffectNode, GameState, PlayerId, Rarity } from '@engine/types';
import { perfectCardFor, winningDeckFor } from '@engine/meta';
import { fuseDefinitions } from '@engine/systems';
import { rarityPullWeight } from '@engine/shop';

/**
 * SB-40 hooks. The interpreter looks a card up here before opening its Discover
 * prompt; a hit replaces the sampled pool with these ids.
 */
export const simSubstitutes: Record<CardDefId, (state: GameState, player: PlayerId) => CardDefId[]> = {
  zephrys: (state, player) => [perfectCardFor(state, player)],
  second_time_around: (state, player) => winningDeckFor(state, player).slice(0, 3),
  infinite_realities: (state, player) => winningDeckFor(state, player),
};

/** SB-13 fusion hook: fuse the given component definitions into one card. */
export function fuseForCard(components: CardDefId[]): CardDefinition {
  return fuseDefinitions(components);
}

/** Hearthstone pack odds expressed over the shop's own rarity pull weights. */
function packBranches(): { weight: number; effects: EffectNode[] }[] {
  const tiers: Rarity[] = ['common', 'rare', 'epic', 'legendary'];
  const branches: { weight: number; effects: EffectNode[] }[] = [];
  for (const tier of tiers) {
    const w = rarityPullWeight(tier);
    branches.push({
      weight: w * 0.95,
      effects: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse', filter: { rarity: tier }, weighted: false } }, to: 'hand' }],
    });
    // Golden pull: same card, plus a Gold.
    branches.push({
      weight: w * 0.05,
      effects: [
        { op: 'createCard', defId: { pool: { scope: 'entireUniverse', filter: { rarity: tier }, weighted: false } }, to: 'hand' },
        { op: 'createCard', defId: 'gold', to: 'hand' },
      ],
    });
  }
  return branches;
}

export const cards: CardDefinition[] = [
  {
    id: 'pandoras_box',
    name: "Pandora's Box",
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'entireUniverse' },
        count: 3,
        pick: 1,
        prompt: 'Discover any card in the Entire Universe',
        then: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse' } }, to: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Discover an Entire Universe card and add it to your hand. +1 Action.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    shop: 'draft',
    art: { key: 'pandoras_box', status: 'placeholder' },
  },
  {
    id: 'lag_in_the_system',
    name: 'Lag in the System',
    cost: { money: 2 },
    types: ['Action'],
    subtypes: [],
    tags: ['Legacy'],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      { op: 'gainCard', from: { shop: 'all', filter: { cost: { eq: 0 } } }, to: 'hand', free: true },
      { op: 'gainCard', from: { shop: 'all', filter: { cost: { eq: 1 } } }, to: 'hand', free: true },
    ],
    triggers: [],
    text: 'Add one of each (0)- and (1)-cost shop card to your hand. +1 Action.',
    complexity: 'T2',
    subsystems: ['S-SHOP'],
    shop: 'draft',
    art: { key: 'lag_in_the_system', status: 'placeholder' },
  },
  {
    id: 'epic_fate',
    name: 'Epic Fate',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: { pool: { scope: 'knownUniverse', filter: { rarity: 'epic' } } }, to: 'hand' }],
    triggers: [],
    text: 'Flimsy. Add a random Epic from your Known Universe to your hand. +1 Action.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    shop: 'draft',
    art: { key: 'epic_fate', status: 'placeholder' },
  },
  {
    id: 'legendary_destiny',
    name: 'Legendary Destiny',
    cost: { money: 8 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'entireUniverse', filter: { rarity: 'legendary' } },
        count: 3,
        pick: 1,
        prompt: 'Discover a Legendary',
        then: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse', filter: { rarity: 'legendary' } } }, to: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Flimsy. Discover a Legendary from the Entire Universe and add it to your hand. +1 Action.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    shop: 'draft',
    art: { key: 'legendary_destiny', status: 'placeholder' },
  },
  {
    id: 'zephrys',
    name: 'Zephrys',
    cost: { money: 10 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'legendary',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'knownUniverse' },
        count: 3,
        pick: 1,
        prompt: 'Discover the perfect card for your hand',
        then: [{ op: 'createCard', defId: { pool: { scope: 'knownUniverse' } }, to: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Discover the perfect card for your hand. +1 Action.',
    flavor: 'The wish is granted, more or less.',
    complexity: 'T4',
    subsystems: ['S-SIM', 'S-CODEX'],
    shop: 'draft',
    art: { key: 'zephrys', status: 'placeholder' },
  },
  {
    id: 'wardrums_mystery_box',
    name: "Wardrum's Mystery Box",
    cost: { money: 8 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'legendary',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'repeat',
        times: 5,
        effects: [
          { op: 'createCard', defId: { pool: { scope: 'entireUniverse', filter: { type: 'Action' } } }, to: 'hand', keywords: ['Flimsy'] },
          { op: 'playCard', target: { who: 'self', zone: 'hand', count: 1, pick: 'random' }, randomTargets: true },
        ],
      },
    ],
    triggers: [],
    text: 'Flimsy. Cast 5 random Entire Universe Actions with random targets.',
    complexity: 'T3',
    subsystems: ['S-CODEX', 'S-MULTIPLIER'],
    shop: 'draft',
    art: { key: 'wardrums_mystery_box', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'wardrums_bold_prediction',
    name: "Wardrum's Bold Prediction",
    cost: { money: 8 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'legendary',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: ['library', 'hand', 'gy'] },
        into: { pool: { scope: 'knownUniverse' } },
      },
    ],
    triggers: [],
    text: 'Flimsy. Transform your entire deck into random Known Universe cards.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    shop: 'draft',
    art: { key: 'wardrums_bold_prediction', status: 'placeholder', anim: 'shuffle' },
  },
  {
    id: 'predatory_monetization',
    name: 'Predatory Monetization',
    cost: { money: 10 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [
      { op: 'repeat', times: 5, effects: [{ op: 'random', branches: packBranches() }] },
    ],
    triggers: [],
    text: 'Flimsy. +1 Action. Open a card pack: 5 cards at pack odds. Golden pulls also give you a Gold.',
    flavor: 'Just one more pack.',
    complexity: 'T4',
    subsystems: ['S-SHOP', 'S-CODEX'],
    shop: 'draft',
    art: { key: 'predatory_monetization', status: 'placeholder', anim: 'explode' },
  },
  {
    id: 'alien_dropshipping',
    name: 'Alien Dropshipping',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: ['PlayOnBuy', 'Flimsy'],
    stats: {},
    effects: [
      {
        op: 'createCard',
        defId: { pool: { scope: 'entireUniverse', filter: { cost: { eq: 6 } } } },
        to: 'library',
        count: 3,
        position: 'random',
        keywords: ['Flimsy'],
      },
      { op: 'shuffle', zone: 'library', who: 'self' },
    ],
    triggers: [],
    text: 'Play on Buy, Flimsy. Shuffle 3 random (6)-cost Entire Universe cards into your Library with Flimsy.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    shop: 'draft',
    art: { key: 'alien_dropshipping', status: 'placeholder', anim: 'shuffle' },
  },
  {
    id: 'a_gaze_into_the_past',
    name: 'A Gaze into the Past',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse', filter: { tag: 'Legacy' } } }, to: 'hand' }],
    triggers: [],
    text: '+1 Action. Add a random Legacy card from the Entire Universe to your hand.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    shop: 'draft',
    art: { key: 'a_gaze_into_the_past', status: 'placeholder' },
  },
  {
    id: 'a_glimpse_of_the_past',
    name: 'A Glimpse of the Past',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse', filter: { tag: 'Legacy' } } }, to: 'hand' }],
    triggers: [],
    text: 'Flimsy. +1 Action. Add a random Legacy card from the Entire Universe to your hand.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    shop: 'draft',
    art: { key: 'a_glimpse_of_the_past', status: 'placeholder' },
  },
  {
    id: 'second_time_around',
    name: 'Second Time Around',
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'discover',
        pool: { scope: 'knownUniverse' },
        count: 3,
        pick: 1,
        prompt: 'Discover a card from a reality where you win',
        then: [{ op: 'createCard', defId: { pool: { scope: 'knownUniverse' } }, to: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Discover a card from a simulated reality where you win.',
    complexity: 'T4',
    subsystems: ['S-SIM', 'S-CODEX'],
    shop: 'draft',
    art: { key: 'second_time_around', status: 'placeholder' },
  },
  {
    id: 'infinite_realities',
    name: 'Infinite Realities',
    cost: { money: 20 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'mythic',
    keywords: ['PlayOnBuy', 'Flimsy'],
    stats: {},
    effects: [
      { op: 'trash', target: { who: 'self', zone: ['hand', 'library', 'gy'] } },
      {
        op: 'createCard',
        defId: { pool: { scope: 'knownUniverse' } },
        to: 'library',
        count: 10,
        position: 'random',
      },
      { op: 'shuffle', zone: 'library', who: 'self' },
      { op: 'draw', amount: 5 },
    ],
    triggers: [],
    text: 'Play on Buy, Flimsy. Replace your hand, Library and GY with a deck from a reality where you win.',
    flavor: 'One of them had to work.',
    complexity: 'T4',
    subsystems: ['S-SIM', 'S-CODEX'],
    shop: 'draft',
    art: { key: 'infinite_realities', status: 'placeholder', anim: 'shuffle' },
  },
  {
    id: 'what_is_love',
    name: 'What is Love?',
    cost: { money: 9 },
    types: ['Action'],
    subtypes: ['Fusion'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 2 },
    effects: [
      {
        op: 'repeat',
        times: 2,
        effects: [
          {
            op: 'discover',
            pool: { scope: 'knownUniverse' },
            count: 3,
            pick: 2,
            prompt: 'Discover 2 cards to Fuse',
            then: [{ op: 'createCard', defId: { pool: { scope: 'knownUniverse' } }, to: 'hand' }],
          },
        ],
      },
    ],
    triggers: [],
    text: 'Discover 2 Known Universe cards, Fuse them and add the result to your hand — twice. +2 Actions.',
    flavor: 'Baby don\'t hurt me.',
    complexity: 'T4',
    subsystems: ['S-FUSE', 'S-CODEX'],
    shop: 'draft',
    art: { key: 'what_is_love', status: 'placeholder' },
  },
  {
    id: 'matchmaker',
    name: 'Matchmaker',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: ['Fusion'],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'copyCard',
        target: { who: 'self', zone: 'library', count: 2, pick: 'random' },
        to: 'library',
      },
      { op: 'shuffle', zone: 'library', who: 'self' },
    ],
    triggers: [],
    text: 'Fuse 2 random non-fused cards in your Library. +1 Action.',
    complexity: 'T4',
    subsystems: ['S-FUSE'],
    shop: 'draft',
    art: { key: 'matchmaker', status: 'placeholder' },
  },
  {
    id: 'freaky_phil',
    name: 'Freaky Phil',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: ['Fusion'],
    tags: [],
    rarity: 'legendary',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'copyCard',
        target: { who: 'self', zone: 'library', count: 3, pick: 'random' },
        to: 'library',
      },
      { op: 'shuffle', zone: 'library', who: 'self' },
    ],
    triggers: [],
    text: 'Fuse 3 random non-fused cards in your Library. +1 Action.',
    complexity: 'T4',
    subsystems: ['S-FUSE'],
    shop: 'draft',
    art: { key: 'freaky_phil', status: 'placeholder' },
  },
  {
    id: 'frankenstein',
    name: 'Frankenstein',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: ['Fusion'],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: { buys: 1 },
    effects: [
      {
        op: 'nextCardModifier',
        mod: { appliesTo: 'buy', uses: 1, costDelta: 0, appendEffects: [{ op: 'gain', stat: 'money', amount: { expr: 'floor(selfCost / 2)' } }] },
      },
      {
        op: 'nextCardModifier',
        mod: { appliesTo: 'buy', uses: 1, buyTo: 'hand' },
      },
    ],
    triggers: [],
    text: 'Flimsy. +1 Buy. Your first purchase refunds 50% (round down); your next purchase fuses with the previous one.',
    complexity: 'T4',
    subsystems: ['S-FUSE', 'S-COSTMOD'],
    shop: 'draft',
    art: { key: 'frankenstein', status: 'placeholder' },
  },
];

export default cards;
