/**
 * A.28 — Draft Shop: time, meta and game-warping.
 *
 * SB-22: A Duel of Wits is a deck-statistics multiple choice, not a
 * logarithmic inequality. SB-39 removes account gates.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'chron_job',
    name: 'Chron Job',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1, money: 2 },
    effects: [{ op: 'moveTo', target: { self: true }, zone: 'library', position: { index: 5 } }],
    triggers: [],
    text: '+1 Action, +2 Money. After playing, put this 6th from the top of your Library.',
    flavor: 'Runs on schedule. Always.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'chron_job', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'chron_break',
    name: 'Chron Break',
    cost: { money: 10 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'mythic',
    keywords: ['PlayOnDraw', 'Flimsy'],
    stats: {},
    effects: [
      { op: 'extraTurn', who: 'self' },
      { op: 'endTurn', who: 'self' },
    ],
    triggers: [],
    text: 'Cast on Draw, Flimsy. End your turn. Then take another one.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'chron_break', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'explode' },
  },
  {
    id: 'twenty_fifth_hour',
    name: '25th Hour',
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { expr: 'floor(currentTurn / 25)' },
        then: [
          { op: 'addCounter', target: { self: true }, key: 'hoursTaken', amount: 1 },
          { op: 'extraTurn', who: 'self' },
        ],
      },
    ],
    triggers: [],
    text: 'After your 25th turn, immediately take an extra turn. One extra turn per copy. (Turn {currentTurn}.)',
    complexity: 'T4',
    subsystems: ['S-PERSIST'],
    shop: 'draft',
    art: { key: 'twenty_fifth_hour', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'outsourcing_rd',
    name: 'Outsourcing R&D',
    cost: { money: 8 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'legendary',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'conditional',
        if: { expr: 'max(0, 1 - abs(selfPlayCount - 3))' },
        then: [{ op: 'manifestAura', tier: 'hypercelestial', auraId: 'lotus_solutions', who: 'self' }],
      },
    ],
    triggers: [],
    text: 'Flimsy. On the 3rd play of this card this game, manifest the Hypercelestial Aura Lotus Solutions. ({playCount}/3)',
    complexity: 'T4',
    subsystems: ['S-PERSIST', 'S-AURA'],
    shop: 'draft',
    art: { key: 'outsourcing_rd', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'conjure_aura',
    name: 'Conjure Aura',
    cost: { money: 12 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'manifestAura', tier: 'celestial', discover: true, who: 'self' }],
    triggers: [],
    text: 'Flimsy. Manifest a Celestial Aura.',
    complexity: 'T3',
    subsystems: ['S-AURA'],
    shop: 'draft',
    art: { key: 'conjure_aura', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'summon' },
  },
  {
    id: 'heros_power',
    name: "Hero's Power",
    cost: { money: 5 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'manifestAura', tier: 'heroic', discover: true, who: 'self' }],
    triggers: [],
    text: 'Flimsy. Discover a Heroic Aura for your Field.',
    complexity: 'T3',
    subsystems: ['S-AURA'],
    shop: 'draft',
    art: { key: 'heros_power', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'summon' },
  },
  {
    id: 'heros_recall',
    name: "Hero's Recall",
    cost: { money: 3 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'rare',
    keywords: [],
    stats: { actions: 1 },
    effects: [
      {
        op: 'conditional',
        if: { expr: 'floor(moneyUnspent / 3)' },
        then: [
          { op: 'gain', stat: 'money', amount: -3 },
          { op: 'createCard', defId: 'heros_recall', to: 'gy' },
        ],
      },
      {
        op: 'conditional',
        if: { has: { target: { who: 'self', zone: 'hand', filter: { defId: 'heros_recall' } }, atLeast: 5 } },
        then: [
          { op: 'trash', target: { who: 'self', zone: 'hand', filter: { defId: 'heros_recall' }, count: 5 } },
          { op: 'manifestAura', tier: 'heroic', discover: true, who: 'self' },
        ],
      },
    ],
    triggers: [],
    text:
      'If you have (3)+ Money, spend 3 and add a Hero\'s Recall to your GY. With 5 in hand, trash them and Discover a Heroic Aura. +1 Action.',
    complexity: 'T3',
    subsystems: ['S-AURA'],
    shop: 'draft',
    art: { key: 'heros_recall', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'quest_accepted',
    name: 'Quest Accepted!',
    cost: { money: 1 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: ['PlayOnBuy'],
    stats: {},
    effects: [
      { op: 'manifestAura', tier: 'celestial', auraId: 'in_too_deep', who: 'self' },
      { op: 'trash', target: { self: true } },
    ],
    triggers: [
      {
        on: 'onBuy',
        effects: [
          { op: 'manifestAura', tier: 'celestial', auraId: 'in_too_deep', who: 'self' },
          { op: 'trash', target: { self: true } },
        ],
      },
    ],
    text: 'On buy, manifest the Celestial Aura In Too Deep, then trash this.',
    flavor: "Rumor goes Paul Hagen's ghost lurks the caves.",
    complexity: 'T4',
    subsystems: ['S-QUEST', 'S-AURA'],
    shop: 'draft',
    art: { key: 'quest_accepted', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'a_duel_of_wits',
    name: 'A Duel of Wits',
    cost: { money: 4 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [
      {
        op: 'choose',
        options: [
          {
            label: "My deck's average cost is above (3)",
            effects: [{ op: 'conditional', if: { expr: 'floor(avgCostOfDeck / 3.0001)' }, then: [{ op: 'draw', amount: 4 }] }],
          },
          {
            label: "My deck's average cost is (3) or less",
            effects: [{ op: 'conditional', if: { not: { expr: 'floor(avgCostOfDeck / 3.0001)' } }, then: [{ op: 'draw', amount: 4 }] }],
          },
          {
            label: 'My deck holds more than 16 unique cards',
            effects: [{ op: 'conditional', if: { expr: 'floor(uniqueCardsInDeck / 17)' }, then: [{ op: 'draw', amount: 4 }] }],
          },
          {
            label: 'My deck holds 16 or fewer unique cards',
            effects: [{ op: 'conditional', if: { not: { expr: 'floor(uniqueCardsInDeck / 17)' } }, then: [{ op: 'draw', amount: 4 }] }],
          },
        ],
        who: 'self',
      },
    ],
    triggers: [],
    text: 'Answer one true statement about your own deck. Correct: +4 Cards. Wrong or timed out: nothing.',
    complexity: 'T4',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'a_duel_of_wits', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'paper_sculpture',
    name: 'Paper Sculpture',
    cost: { money: 6 },
    types: ['Action'],
    subtypes: [],
    tags: [],
    rarity: 'epic',
    keywords: [],
    stats: { money: 2, buys: 2, actions: 2, cards: 2, vp: 2 },
    effects: [],
    triggers: [
      {
        on: 'onTrash',
        effects: [{ op: 'trash', target: { who: 'self', zone: ['library', 'hand', 'gy'], count: 10, pick: 'random' } }],
      },
    ],
    text: '+2 to all five stats. If this is trashed, stolen or removed from your deck in any way, trash 10 random cards from your deck.',
    flavor: 'Handle with care. Really.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    shop: 'draft',
    art: { key: 'paper_sculpture', status: 'final', artist: 'LCM Dreamshaper v7', anim: 'trash' },
  },
  {
    id: 'mercenary_280',
    name: 'Mercenary 280',
    cost: { money: 3 },
    types: ['Action', 'Points'],
    subtypes: [],
    tags: ['EndOfGame'],
    rarity: 'epic',
    keywords: [],
    stats: {},
    effects: [],
    triggers: [
      {
        on: 'gameEnd',
        effects: [
          {
            op: 'conditional',
            if: { expr: 'max(0, 1 - abs(sumOfDeckCosts - 280))' },
            then: [{ op: 'scoreOnCard', target: { self: true }, amount: 280 }],
          },
        ],
      },
    ],
    text: 'End of Game: +280 VP if the costs of every card in your deck sum to exactly 280. ({sumOfDeckCosts}/280)',
    flavor: 'He counts.',
    complexity: 'T2',
    subsystems: ['S-ENDGAME'],
    shop: 'draft',
    art: { key: 'mercenary_280', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
  {
    id: 'doomsday_clock',
    name: 'Doomsday Clock',
    cost: { money: 9 },
    types: ['Action'],
    subtypes: [],
    tags: ['PvP'],
    rarity: 'mythic',
    keywords: [],
    stats: {},
    effects: [
      { op: 'incDoomsday', amount: 1 },
      {
        op: 'delayed',
        when: { inTurns: 5 },
        effects: [{ op: 'endGame', reason: 'doomsdayClock' }],
        who: 'self',
      },
    ],
    triggers: [],
    text: 'Advance the Doomsday Counter by 1. Five turns from now the game ends, whatever the score. (Counter at {doomsdayCounter}.)',
    flavor: 'It only turns one way.',
    complexity: 'T3',
    subsystems: ['S-ENDGAME'],
    shop: 'draft',
    art: { key: 'doomsday_clock', status: 'final', artist: 'LCM Dreamshaper v7' },
  },
];

export default cards;
