/**
 * B.1 — the Miracle catalog. Miracle Fruit discovers 1 of 3 from this pool.
 *
 * Every entry is tagged `Miracle`, is `notPurchasable`, and is reachable only
 * through `{pool:{catalog:'miracle'}}`.
 */
import type { CardDefinition } from '@engine/types';

// Miracle Fruit itself is the (10) Legendary Food of A.16 and lives in
// `tribes/food.ts`. This file holds only the pool it discovers from.
export const cards: CardDefinition[] = [
  {
    id: 'miracle_transmutation',
    name: 'Miracle: Transmutation',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'], filter: { defId: ['copper', 'silver'] } },
        into: 'gold',
      },
    ],
    triggers: [],
    text: 'Transform every Copper and Silver in your deck into Gold.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_transmutation', status: 'placeholder' },
  },
  {
    id: 'miracle_sanctification',
    name: 'Miracle: Sanctification',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'buff',
        scope: 'instance',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Points' } },
        stat: 'vp',
        amount: 1,
      },
    ],
    triggers: [],
    text: 'Every Points card in your deck gains +1 VP.',
    complexity: 'T3',
    subsystems: ['S-BUFF'],
    notPurchasable: true,
    art: { key: 'miracle_sanctification', status: 'placeholder' },
  },
  {
    id: 'miracle_tithe_of_jlore',
    name: 'Miracle: Tithe of Jlore',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'gainCard', from: { shop: 'points', filter: { defId: 'jlore' } }, to: 'gy', count: 2, free: true }],
    triggers: [],
    text: 'Add 2 Jlore from the Points Shop to your GY.',
    complexity: 'T3',
    subsystems: ['S-SHOP'],
    notPurchasable: true,
    art: { key: 'miracle_tithe_of_jlore', status: 'placeholder' },
  },
  {
    id: 'miracle_animation',
    name: 'Miracle: Animation',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'buff',
        scope: 'instance',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Points' } },
        stat: 'actions',
        amount: 1,
      },
      {
        op: 'buff',
        scope: 'instance',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Points' } },
        stat: 'cards',
        amount: 1,
      },
    ],
    triggers: [],
    text: 'Every Points card in your deck gains +1 Action and +1 Card.',
    complexity: 'T3',
    subsystems: ['S-BUFF'],
    notPurchasable: true,
    art: { key: 'miracle_animation', status: 'placeholder' },
  },
  {
    id: 'miracle_the_covetous_hand',
    name: 'Miracle: The Covetous Hand',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      // `who` on a moveTo names the DESTINATION owner. Without it the cards are
      // re-filed under the opponent who already owned them and the steal is a
      // no-op; with it they change hands, Indestructible Points included, which
      // the copy-plus-trash shape could not do.
      {
        op: 'moveTo',
        target: { who: 'eachOpponent', zone: ['gy', 'hand'], filter: { type: 'Points' }, count: 2, pick: 'mostExpensive' },
        zone: 'gy',
        who: 'self',
      },
    ],
    triggers: [],
    text: 'Steal 2 Points cards from your opponents into your GY.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_the_covetous_hand', status: 'placeholder' },
  },
  {
    id: 'miracle_manna',
    name: 'Miracle: Manna',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'delayed', when: 'startOfNextTurn', effects: [{ op: 'gain', stat: 'money', amount: 13 }], who: 'self' },
    ],
    triggers: [],
    text: '+13 Money next turn.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_manna', status: 'placeholder', anim: 'coin' },
  },
  {
    id: 'miracle_the_library',
    name: 'Miracle: The Library',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: { pool: { catalog: 'book' } }, to: 'hand', count: 3 }],
    triggers: [],
    text: 'Add 3 Books to your hand. +1 Action.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'miracle_the_library', status: 'placeholder' },
  },
  {
    id: 'miracle_multiplication',
    name: 'Miracle: Multiplication',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'createCard', defId: 'miracle_fruit', to: 'gy', count: 2 }],
    triggers: [],
    text: 'Add 2 Miracle Fruit to your GY.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'miracle_multiplication', status: 'placeholder' },
  },
  {
    id: 'miracle_duplication',
    name: 'Miracle: Duplication',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'copyCard',
        target: { who: 'self', zone: ['library', 'hand', 'gy'], filter: { cost: { gte: 6 } } },
        to: 'gy',
      },
    ],
    triggers: [],
    text: 'Duplicate every card in your deck costing (6) or more.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_duplication', status: 'placeholder' },
  },
  {
    id: 'miracle_diamond_rain',
    name: 'Miracle: Diamond Rain',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'createCard', defId: 'diamond', to: 'hand', count: 2 }],
    triggers: [],
    text: 'Add 2 Diamonds to your hand.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_diamond_rain', status: 'placeholder' },
  },
  {
    id: 'miracle_revelation',
    name: 'Miracle: Revelation',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'entireUniverse', filter: { cost: { gte: 10 } } },
        count: 3,
        pick: 1,
        prompt: 'Discover a card costing (10) or more',
        then: [],
      },
    ],
    triggers: [],
    text: 'Add a card costing (10) or more from the Entire Universe to your hand. +1 Action.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    notPurchasable: true,
    art: { key: 'miracle_revelation', status: 'placeholder' },
  },
  {
    id: 'miracle_prophecy',
    name: 'Miracle: Prophecy',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: { prophet: 7 },
    effects: [],
    triggers: [],
    text: '+7 Prophet.',
    complexity: 'T3',
    subsystems: ['S-PROPHET'],
    notPurchasable: true,
    art: { key: 'miracle_prophecy', status: 'placeholder' },
  },
  {
    id: 'miracle_moonfall',
    name: 'Miracle: Moonfall',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      // The doc row's "(0)-cost" (B.1, Miracle 13) has no home in the data, so
      // the printed text drops it. `costOverride` prices the PILE, not the card
      // added to it: three Draft piles would read (0) to every player, through
      // `pileCost`, `costOf` and every `pick:'cheapest'` pile selector, until
      // someone happened to play the one card that clears a pile's price (Cloud
      // Nine — a `modifyCost` carrying neither `delta` nor `setTo`). And no
      // price is reachable in any case: `lunar_fragment` is a Token marked
      // notPurchasable, which `canBuyPile` (core/buy.ts) refuses before it ever
      // reads a price, so the Fragment sits on top of the pile as a blocker
      // rather than as a free buy. Seeded as printed with no price written; a
      // per-instance price is engine work. Chron Caché and Supernova
      // (economy/shop-manip.ts) dropped the same clause for the same reason.
      {
        op: 'addToPileTop',
        target: { shop: 'draft', count: 3, pick: 'random', excludeJlore: true },
        defId: 'lunar_fragment',
        count: 1,
      },
    ],
    triggers: [],
    text: 'Add a Lunar Fragment to the top of 3 random Draft piles.',
    complexity: 'T3',
    subsystems: ['S-SHOP', 'S-TOKEN'],
    notPurchasable: true,
    art: { key: 'miracle_moonfall', status: 'placeholder' },
  },
];

export default cards;
