/**
 * B.1 — the Miracle catalog. Miracle Fruit discovers 1 of 3 from this pool.
 *
 * Every entry is tagged `Miracle`, is `notPurchasable`, and is reachable only
 * through `{pool:{catalog:'miracle'}}`.
 */
import type { CardDefinition } from '@engine/types';

export const cards: CardDefinition[] = [
  {
    id: 'miracle_fruit',
    name: 'Miracle Fruit',
    cost: { money: 3 },
    types: ['Action', 'Food', 'Token'],
    subtypes: ['Fruit'],
    tags: [],
    rarity: 'token',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { catalog: 'miracle' },
        count: 3,
        pick: 1,
        prompt: 'Choose a Miracle',
        then: [{ op: 'createCard', defId: { pool: { catalog: 'miracle' } }, to: 'play' }],
      },
    ],
    triggers: [],
    text: 'Flimsy. +1 Action. Discover 1 of 3 Miracles and perform it.',
    flavor: 'Tastes like the outcome you wanted.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'miracle_fruit', status: 'placeholder', anim: 'summon' },
  },
  {
    id: 'miracle_transmutation',
    name: 'Miracle: Transmutation',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'transform',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'], filter: { defId: ['copper', 'silver'] } },
        into: 'gold',
      },
    ],
    triggers: [],
    text: 'Transform every Copper and Silver in your deck into Gold.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_transmutation', status: 'placeholder' },
  },
  {
    id: 'miracle_sanctification',
    name: 'Miracle: Sanctification',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'buff',
        scope: 'instance',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Points' } },
        stat: 'vp',
        amount: 1,
      },
    ],
    triggers: [],
    text: 'Every Points card in your deck gains +1 VP.',
    complexity: 'T3',
    subsystems: ['S-BUFF'],
    notPurchasable: true,
    art: { key: 'miracle_sanctification', status: 'placeholder' },
  },
  {
    id: 'miracle_tithe_of_jlore',
    name: 'Miracle: Tithe of Jlore',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'gainCard', from: { shop: 'points', filter: { defId: 'jlore' } }, to: 'gy', count: 2, free: true }],
    triggers: [],
    text: 'Add 2 Jlore from the Points Shop to your GY.',
    complexity: 'T3',
    subsystems: ['S-SHOP'],
    notPurchasable: true,
    art: { key: 'miracle_tithe_of_jlore', status: 'placeholder' },
  },
  {
    id: 'miracle_animation',
    name: 'Miracle: Animation',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'buff',
        scope: 'instance',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Points' } },
        stat: 'actions',
        amount: 1,
      },
      {
        op: 'buff',
        scope: 'instance',
        target: { who: 'self', zone: ['library', 'hand', 'gy', 'play'], filter: { type: 'Points' } },
        stat: 'cards',
        amount: 1,
      },
    ],
    triggers: [],
    text: 'Every Points card in your deck gains +1 Action and +1 Card.',
    complexity: 'T3',
    subsystems: ['S-BUFF'],
    notPurchasable: true,
    art: { key: 'miracle_animation', status: 'placeholder' },
  },
  {
    id: 'miracle_the_covetous_hand',
    name: 'Miracle: The Covetous Hand',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'moveTo',
        target: { who: 'eachOpponent', zone: ['gy', 'hand'], filter: { type: 'Points' }, count: 2, pick: 'mostExpensive' },
        zone: 'gy',
      },
    ],
    triggers: [],
    text: 'Steal 2 Points cards from your opponents into your GY.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_the_covetous_hand', status: 'placeholder' },
  },
  {
    id: 'miracle_manna',
    name: 'Miracle: Manna',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      { op: 'delayed', when: 'startOfNextTurn', effects: [{ op: 'gain', stat: 'money', amount: 13 }], who: 'self' },
    ],
    triggers: [],
    text: '+13 Money next turn.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_manna', status: 'placeholder', anim: 'coin' },
  },
  {
    id: 'miracle_the_library',
    name: 'Miracle: The Library',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [{ op: 'createCard', defId: { pool: { catalog: 'book' } }, to: 'hand', count: 3 }],
    triggers: [],
    text: 'Add 3 Books to your hand. +1 Action.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'miracle_the_library', status: 'placeholder' },
  },
  {
    id: 'miracle_multiplication',
    name: 'Miracle: Multiplication',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'createCard', defId: 'miracle_fruit', to: 'gy', count: 2 }],
    triggers: [],
    text: 'Add 2 Miracle Fruit to your GY.',
    complexity: 'T3',
    subsystems: ['S-TOKEN'],
    notPurchasable: true,
    art: { key: 'miracle_multiplication', status: 'placeholder' },
  },
  {
    id: 'miracle_duplication',
    name: 'Miracle: Duplication',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'copyCard',
        target: { who: 'self', zone: ['library', 'hand', 'gy'], filter: { cost: { gte: 6 } } },
        to: 'gy',
      },
    ],
    triggers: [],
    text: 'Duplicate every card in your deck costing (6) or more.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_duplication', status: 'placeholder' },
  },
  {
    id: 'miracle_diamond_rain',
    name: 'Miracle: Diamond Rain',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [{ op: 'createCard', defId: 'diamond', to: 'hand', count: 2 }],
    triggers: [],
    text: 'Add 2 Diamonds to your hand.',
    complexity: 'T3',
    subsystems: ['S-CORE'],
    notPurchasable: true,
    art: { key: 'miracle_diamond_rain', status: 'placeholder' },
  },
  {
    id: 'miracle_revelation',
    name: 'Miracle: Revelation',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: { actions: 1 },
    effects: [
      {
        op: 'discover',
        pool: { scope: 'entireUniverse', filter: { cost: { gte: 10 } } },
        count: 3,
        pick: 1,
        prompt: 'Discover a card costing (10) or more',
        then: [{ op: 'createCard', defId: { pool: { scope: 'entireUniverse', filter: { cost: { gte: 10 } } } }, to: 'hand' }],
      },
    ],
    triggers: [],
    text: 'Add a card costing (10) or more from the Entire Universe to your hand. +1 Action.',
    complexity: 'T3',
    subsystems: ['S-CODEX'],
    notPurchasable: true,
    art: { key: 'miracle_revelation', status: 'placeholder' },
  },
  {
    id: 'miracle_prophecy',
    name: 'Miracle: Prophecy',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: { prophet: 7 },
    effects: [],
    triggers: [],
    text: '+7 Prophet.',
    complexity: 'T3',
    subsystems: ['S-PROPHET'],
    notPurchasable: true,
    art: { key: 'miracle_prophecy', status: 'placeholder' },
  },
  {
    id: 'miracle_moonfall',
    name: 'Miracle: Moonfall',
    cost: { money: 0 },
    types: ['Action'],
    subtypes: ['Miracle'],
    tags: ['Miracle'],
    rarity: 'mythic',
    keywords: ['Flimsy'],
    stats: {},
    effects: [
      {
        op: 'addToPileTop',
        target: { shop: 'draft', count: 3, pick: 'random', excludeJlore: true },
        defId: 'lunar_fragment',
        count: 1,
        costOverride: 0,
      },
    ],
    triggers: [],
    text: 'Add a (0)-cost Lunar Fragment to the top of 3 random Draft piles.',
    complexity: 'T3',
    subsystems: ['S-SHOP', 'S-TOKEN'],
    notPurchasable: true,
    art: { key: 'miracle_moonfall', status: 'placeholder' },
  },
];

export default cards;
