/**
 * npm run art:manifest
 *
 * Writes docs/ART-MANIFEST.md: every card grouped by rarity and archetype with
 * its art key, current status, assigned artist and animation preset.
 *
 * Placeholders come first on purpose — the art pass wants a worklist, not a
 * spreadsheet, and the top of this file is that worklist.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { AuraDefinition, CardDefinition, Rarity } from '@engine/types';
import { bootstrap } from './bootstrap';

const RARITY_ORDER: string[] = ['basic', 'common', 'rare', 'epic', 'legendary', 'mythic', 'token'];
const STATUS_ORDER: string[] = ['placeholder', 'sketch', 'final'];

function rarityRank(r: Rarity | string): number {
  const i = RARITY_ORDER.indexOf(String(r));
  return i < 0 ? RARITY_ORDER.length : i;
}

/** A card's archetype is its first subsystem: the axis it was designed around. */
function archetypeOf(c: CardDefinition): string {
  if (Array.isArray(c.subsystems) && c.subsystems.length > 0 && c.subsystems[0]) return c.subsystems[0];
  if (Array.isArray(c.subtypes) && c.subtypes.length > 0 && c.subtypes[0]) return c.subtypes[0];
  return 'unsorted';
}

function statusOf(c: CardDefinition | AuraDefinition): string {
  return c.art && c.art.status ? c.art.status : 'placeholder';
}

function keyOf(c: CardDefinition | AuraDefinition): string {
  return c.art && c.art.key ? c.art.key : '(none)';
}

function artistOf(c: CardDefinition | AuraDefinition): string {
  return c.art && c.art.artist ? c.art.artist : '—';
}

function animOf(c: CardDefinition | AuraDefinition): string {
  return c.art && c.art.anim ? '`' + c.art.anim + '`' : '—';
}

function row(cells: (string | number)[]): string {
  return '| ' + cells.join(' | ') + ' |';
}

function tableHeader(cells: string[]): string {
  return row(cells) + '\n' + row(cells.map(() => '---'));
}

function cardRows(list: CardDefinition[]): string[] {
  const out: string[] = [];
  out.push(tableHeader(['card', 'id', 'art key', 'status', 'artist', 'anim']));
  for (const c of list) {
    out.push(row([c.name, '`' + c.id + '`', '`' + keyOf(c) + '`', statusOf(c), artistOf(c), animOf(c)]));
  }
  return out;
}

function main(): void {
  const { cards, auras } = bootstrap();

  const byStatus: Record<string, CardDefinition[]> = { placeholder: [], sketch: [], final: [] };
  for (const c of cards) {
    const s = statusOf(c);
    if (!byStatus[s]) byStatus[s] = [];
    byStatus[s].push(c);
  }

  const out: string[] = [];
  out.push('# Art manifest');
  out.push('');

  const counts: string[] = [];
  for (const s of STATUS_ORDER) counts.push(s + ' ' + (byStatus[s] ? byStatus[s].length : 0));
  for (const s of Object.keys(byStatus)) {
    if (STATUS_ORDER.indexOf(s) < 0) counts.push(s + ' ' + byStatus[s].length);
  }
  out.push(
    '**' +
      cards.length +
      ' cards, ' +
      auras.length +
      ' auras — ' +
      counts.join(', ') +
      '.** Generated by `npm run art:manifest`.',
  );
  out.push('');
  const stillPlaceholder = byStatus['placeholder'] ? byStatus['placeholder'].length : 0;
  out.push(
    stillPlaceholder > 0
      ? 'Placeholders first: everything under **Placeholder** is unstarted work.'
      : 'Every card and aura has art. Regenerate it with `npm run art:generate`, ' +
          'or re-roll one card with `npm run art:generate -- --reroll=<art key>`.',
  );
  out.push('');

  for (const status of STATUS_ORDER.concat(Object.keys(byStatus).filter((s) => STATUS_ORDER.indexOf(s) < 0))) {
    const list = byStatus[status];
    if (!list || list.length === 0) continue;
    out.push('## ' + status.charAt(0).toUpperCase() + status.slice(1) + ' (' + list.length + ')');
    out.push('');

    // Group by rarity, then archetype, both in a stable order.
    const byRarity: Record<string, CardDefinition[]> = {};
    for (const c of list) {
      const r = String(c.rarity);
      if (!byRarity[r]) byRarity[r] = [];
      byRarity[r].push(c);
    }
    const rarities = Object.keys(byRarity).sort((a, b) => rarityRank(a) - rarityRank(b));
    for (const rarity of rarities) {
      const group = byRarity[rarity];
      out.push('### ' + rarity + ' (' + group.length + ')');
      out.push('');
      const byArch: Record<string, CardDefinition[]> = {};
      for (const c of group) {
        const a = archetypeOf(c);
        if (!byArch[a]) byArch[a] = [];
        byArch[a].push(c);
      }
      const archetypes = Object.keys(byArch).sort();
      for (const arch of archetypes) {
        const members = byArch[arch].slice().sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
        out.push('#### ' + arch + ' (' + members.length + ')');
        out.push('');
        for (const line of cardRows(members)) out.push(line);
        out.push('');
      }
    }
  }

  if (auras.length > 0) {
    out.push('## Auras (' + auras.length + ')');
    out.push('');
    const byTier: Record<string, AuraDefinition[]> = {};
    for (const a of auras) {
      const t = String(a.tier);
      if (!byTier[t]) byTier[t] = [];
      byTier[t].push(a);
    }
    for (const tier of ['heroic', 'celestial', 'hypercelestial'].concat(
      Object.keys(byTier).filter((t) => ['heroic', 'celestial', 'hypercelestial'].indexOf(t) < 0),
    )) {
      const group = byTier[tier];
      if (!group || group.length === 0) continue;
      out.push('### ' + tier + ' (' + group.length + ')');
      out.push('');
      out.push(tableHeader(['aura', 'id', 'art key', 'status', 'artist', 'anim']));
      const sorted = group.slice().sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
      for (const a of sorted) {
        out.push(row([a.name, '`' + a.id + '`', '`' + keyOf(a) + '`', statusOf(a), artistOf(a), animOf(a)]));
      }
      out.push('');
    }
  }

  const md = out.join('\n');
  const outPath = resolve(process.cwd(), 'docs', 'ART-MANIFEST.md');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, md, 'utf8');

  process.stdout.write(
    'art:manifest — ' + cards.length + ' cards, ' + auras.length + ' auras (' + counts.join(', ') + ')\n',
  );
  process.stdout.write('wrote ' + outPath + '\n');
}

main();
