/**
 * npm run balance -- --games=500 --players=3 --seed=1
 *
 * Runs a batch of bot matches, ranks the catalog, and writes
 * telemetry/balance-<timestamp>.md. The markdown is the deliverable: it is meant
 * to be pasted into a balance thread and argued with.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, resolve } from 'node:path';
import { simulateManyDetailed } from '@sim/run';
import { aggregate, winsBySeat } from '@sim/telemetry';
import type { BalanceReport } from '@sim/telemetry';
import { bootstrap, fixed, intArg, parseArgs, pct, stamp } from './bootstrap';

function row(cells: (string | number)[]): string {
  return '| ' + cells.join(' | ') + ' |';
}

function header(cells: string[]): string {
  return row(cells) + '\n' + row(cells.map(() => '---'));
}

function renderMarkdown(
  report: BalanceReport,
  seats: Record<string, number>,
  games: number,
  players: number,
  startSeed: number,
  elapsedMs: number,
): string {
  const out: string[] = [];
  const matches = Math.max(1, report.matches);

  out.push('# Balance report');
  out.push('');
  out.push(
    '`' +
      games +
      '` matches, `' +
      players +
      '` players, seeds `' +
      startSeed +
      '`–`' +
      (startSeed + games - 1) +
      '`, ' +
      (elapsedMs / 1000).toFixed(1) +
      's.',
  );
  out.push('');
  out.push('Generated by `npm run balance`. Every number here is measured from bot play, not derived.');
  out.push('');

  out.push('## Summary');
  out.push('');
  out.push(header(['metric', 'value']));
  out.push(row(['matches', report.matches]));
  out.push(row(['mean turns', fixed(report.meanTurns, 1)]));
  out.push(row(['median turns', fixed(report.medianTurns, 1)]));
  out.push(row(['turn range', report.minTurns + '–' + report.maxTurns]));
  out.push(row(['hit 500-turn cap', report.cappedMatches + ' (' + pct(report.cappedMatches / matches) + ')']));
  out.push(row(['total buys', report.totalBuys]));
  out.push(row(['definitions never bought', report.neverBought.length + ' of ' + report.cards.length]));
  out.push(
    row([
      'discover offered / picked',
      report.totalDiscoversOffered +
        ' / ' +
        report.totalDiscoversPicked +
        ' (' +
        pct(report.totalDiscoversOffered ? report.totalDiscoversPicked / report.totalDiscoversOffered : 0) +
        ')',
    ]),
  );
  out.push('');

  out.push('## Match length');
  out.push('');
  out.push(header(['turns', 'matches', 'share']));
  const keys = Object.keys(report.turnHistogram).sort((a, b) => Number.parseInt(a, 10) - Number.parseInt(b, 10));
  for (const k of keys) {
    out.push(row([k, report.turnHistogram[k], pct(report.turnHistogram[k] / matches)]));
  }
  out.push('');
  out.push('### By win-condition variant');
  out.push('');
  out.push(header(['variant', 'matches', 'mean turns', 'min', 'max']));
  for (const v of report.matchLengthByVariant) {
    out.push(row([v.variant, v.matches, fixed(v.meanTurns, 1), v.minTurns, v.maxTurns]));
  }
  out.push('');

  out.push('## End conditions');
  out.push('');
  out.push(header(['reason', 'fired', 'share']));
  const reasons = Object.keys(report.endReasons).sort((a, b) => report.endReasons[b] - report.endReasons[a]);
  for (const r of reasons) {
    out.push(row(['`' + r + '`', report.endReasons[r], pct(report.endReasons[r] / matches)]));
  }
  out.push('');

  out.push('## Seat balance');
  out.push('');
  out.push(header(['seat', 'wins', 'win rate']));
  for (const s of Object.keys(seats).sort()) {
    out.push(row([s, seats[s], pct(seats[s] / matches)]));
  }
  out.push('');

  out.push('## Anomalies');
  out.push('');
  out.push('`seat 1 win rate` well away from `1 / players` under one anomaly is that anomaly warping the table.');
  out.push('');
  out.push(header(['anomaly', 'matches', 'share', 'mean turns', 'seat 1 win', 'shared win', 'mean winning VP']));
  for (const a of report.anomalies) {
    out.push(
      row([
        '`' + a.anomaly + '`',
        a.matches,
        pct(a.share),
        fixed(a.meanTurns, 1),
        pct(a.firstSeatWinRate),
        pct(a.sharedWinRate),
        fixed(a.meanWinningScore, 1),
      ]),
    );
  }
  out.push('');

  const bought = report.cards.filter((c) => c.buys > 0);

  out.push('## Most bought');
  out.push('');
  out.push(header(['card', 'rarity', 'buys', 'per match', 'buy rate', 'win rate when bought', 'mean first buy turn']));
  for (const c of bought.slice(0, 40)) {
    out.push(
      row([
        c.name,
        c.rarity,
        c.buys,
        fixed(c.buysPerMatch, 2),
        pct(c.buyRate),
        pct(c.winRateWhenBought),
        fixed(c.meanFirstBuyTurn, 1),
      ]),
    );
  }
  out.push('');

  out.push('## Least bought (bought at least once)');
  out.push('');
  out.push(header(['card', 'rarity', 'buys', 'buy rate', 'win rate when bought']));
  for (const c of bought.slice(-30).reverse()) {
    out.push(row([c.name, c.rarity, c.buys, pct(c.buyRate), pct(c.winRateWhenBought)]));
  }
  out.push('');

  out.push('## Never bought');
  out.push('');
  out.push(
    report.neverBought.length === 0
      ? 'Every purchasable definition was bought at least once.'
      : '`' + report.neverBought.length + '` purchasable definitions were never bought by any bot:',
  );
  if (report.neverBought.length > 0) {
    out.push('');
    out.push('```');
    for (let i = 0; i < report.neverBought.length; i += 6) {
      out.push(report.neverBought.slice(i, i + 6).join('  '));
    }
    out.push('```');
  }
  out.push('');

  out.push('## Dead Discover cards');
  out.push('');
  out.push('Offered five or more times and taken at most 5% of the time. These are the cards the pool is wasting.');
  out.push('');
  if (report.deadCards.length === 0) {
    out.push('None.');
  } else {
    out.push(header(['card', 'offered', 'picked', 'pick rate']));
    for (const d of report.deadCards.slice(0, 60)) {
      out.push(row([d.name, d.discoverOffered, d.discoverPicked, pct(d.pickRate)]));
    }
  }
  out.push('');

  out.push('## Discover offered vs picked');
  out.push('');
  const offeredCards = report.cards.filter((c) => c.discoverOffered > 0);
  offeredCards.sort((a, b) => b.discoverOffered - a.discoverOffered);
  out.push(header(['card', 'offered', 'picked', 'pick rate']));
  for (const c of offeredCards.slice(0, 60)) {
    out.push(row([c.name, c.discoverOffered, c.discoverPicked, pct(c.pickRate)]));
  }
  out.push('');

  return out.join('\n');
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const games = Math.max(1, intArg(args, 'games', 200));
  const players = Math.max(2, intArg(args, 'players', 2));
  const startSeed = intArg(args, 'seed', 1);

  const { cards } = bootstrap();
  process.stdout.write('balance: ' + games + ' games x ' + players + ' players over ' + cards.length + ' cards...\n');

  const started = Date.now();
  const results = simulateManyDetailed(games, players, startSeed);
  const elapsed = Date.now() - started;

  const report = aggregate(results);
  const seats = winsBySeat(results);
  const md = renderMarkdown(report, seats, games, players, startSeed, elapsed);

  process.stdout.write('\n' + md + '\n');

  const rel = args.out !== undefined && args.out !== 'true' ? args.out : 'telemetry/balance-' + stamp() + '.md';
  const outPath = isAbsolute(rel) ? rel : resolve(process.cwd(), rel);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, md, 'utf8');
  process.stdout.write('\nwrote ' + outPath + '\n');
}

main();
